personal_info = 
{
	nickname = "#$player.name#",
	rank = "#$player.rank#(#$player.exp#)",
	team = "#$player.team#",
	kill_number = #$player.killNum#,
	headshot_number = #$player.headshotNum#,
	death_number = #$player.deathNum#,
	kill_rate = #$player.killRate#,
	victory_number = #$player.victoryNum#,
	victory_rate = #$player.victoryRate#,
	failure_number = #$player.failureNum#,
	flowers = "#$player.flowerTotal#",
}

