package utils
{
	import vo.LevelWeapon;
	import vo.SysItem;
	
	public class SysItemToSysLevelWeapon
	{
	public static function change(sysItem:SysItem,weapon:LevelWeapon):void{
		weapon.itemId=sysItem.id;
		weapon.name=sysItem.name;
		weapon.displayName=sysItem.displayName;
		weapon.resourceStable=sysItem.resourceStable;
		weapon.resourceChangeable=sysItem.resourceChangeable;
		weapon.WId=sysItem.WId;
		weapon.WChangeInTime=sysItem.WChangeInTime;
		weapon.WMoveSpeedOffset=sysItem.WMoveSpeedOffset;
		weapon.WCrossOffset=sysItem.WCrossOffset;
		weapon.WAccuracyDivisor=sysItem.WAccuracyDivisor;
		weapon.WAccuracyOffset=sysItem.WAccuracyOffset;
		weapon.WMaxInaccuracy=sysItem.WMaxInaccuracy;
		weapon.WPenetration=sysItem.WPenetration;
		weapon.WDamage=sysItem.WDamage;
		weapon.WRangeModifier=sysItem.WRangeModifier;
		weapon.WFireTime=sysItem.WFireTime;
		weapon.WReloadTime=sysItem.WReloadTime;
		weapon.WAmmoOneClip=sysItem.WAmmoOneClip;
		weapon.WAmmoCount=sysItem.WAmmoCount;
		weapon.WAutoFire=sysItem.WAutoFire;
		weapon.WTimeToIdle=sysItem.WTimeToIdle;
		weapon.WNormalOffset=sysItem.WNormalOffset;
		weapon.WNormalFactor=sysItem.WNormalFactor;
		weapon.WOnairOffset=sysItem.WOnairOffset;
		weapon.WOnairFactor=sysItem.WOnairFactor;
		weapon.WMoveOffset=sysItem.WMoveOffset;
		weapon.WMoveFactor=sysItem.WMoveFactor;
		weapon.WNormalUpBase=sysItem.WNormalUpBase;
		weapon.WNormalLateralBase=sysItem.WNormalLateralBase;
		weapon.WNormalUpModifier=sysItem.WNormalUpModifier;
		weapon.WNormalLateralModifier=sysItem.WNormalLateralModifier;
		weapon.WNormalUpMax=sysItem.WNormalUpMax;
		weapon.WNormalLateralMax=sysItem.WNormalLateralMax;
		weapon.WNormalDirChange=sysItem.WNormalDirChange;
		weapon.WMoveUpBase=sysItem.WMoveUpBase;
		weapon.WMoveLateralBase=sysItem.WMoveLateralBase;
		weapon.WMoveUpModifier=sysItem.WMoveUpModifier;
		weapon.WMoveLateralModifier=sysItem.WMoveLateralModifier;
		weapon.WMoveUpMax=sysItem.WMoveUpMax;
		weapon.WMoveLateralMax=sysItem.WMoveLateralMax;
		weapon.WMoveDirChange=sysItem.WMoveDirChange;
		weapon.WOnairUpBase=sysItem.WOnairUpBase;
		weapon.WOnairLateralBase=sysItem.WOnairLateralBase;
		weapon.WOnairUpModifier=sysItem.WOnairUpModifier;
		weapon.WOnairLateralModifier=sysItem.WOnairLateralModifier;
		weapon.WOnairUpMax=sysItem.WOnairUpMax;
		weapon.WOnairLateralMax=sysItem.WOnairLateralMax;
		weapon.WOnairDirChange=sysItem.WOnairDirChange;
		weapon.WCrouchUpBase=sysItem.WCrouchUpBase;
		weapon.WCrouchLateralBase=sysItem.WCrouchLateralBase;
		weapon.WCrouchUpModifier=sysItem.WCrouchUpModifier;
		weapon.WCrouchLateralModifier=sysItem.WCrouchLateralModifier;
		weapon.WCrouchUpMax=sysItem.WCrouchUpMax;
		weapon.WCrouchLateralMax=sysItem.WCrouchLateralMax;
		weapon.WCrouchDirChange=sysItem.WCrouchDirChange;
		weapon.WUpModifier=sysItem.WUpModifier;
		weapon.WStabTime=sysItem.WStabTime;
		weapon.WStabLightTime=sysItem.WStabLightTime;
		weapon.WStabHurt=sysItem.WStabHurt;
		weapon.WStabLightHurt=sysItem.WStabLightHurt;
		weapon.WExplodeTime=sysItem.WExplodeTime;
		weapon.WReadyTime=sysItem.WReadyTime;
		weapon.WThrowOutTime=sysItem.WThrowOutTime;
		weapon.WHurtRange=sysItem.WHurtRange;
		weapon.WHurt=sysItem.WHurt;
		weapon.WShootBulletCount=sysItem.WShootBulletCount;
		weapon.WSpread=sysItem.WSpread;
		weapon.WFireMaxSpeed=sysItem.WFireMaxSpeed;
		weapon.WFireStartSpeed=sysItem.WFireStartSpeed;
		weapon.WFireAceleration=sysItem.WFireAceleration;
		weapon.WFireResistance=sysItem.WFireResistance;
		weapon.WRangeStart=sysItem.WRangeStart;
		weapon.WRangeEnd=sysItem.WRangeEnd;
		weapon.WAccuracyTime=sysItem.WAccuracyTime;
		weapon.WAccuracyTimeModefier=sysItem.WAccuracyTimeModefier;
		weapon.WMaxAccuracy=sysItem.WMaxAccuracy;
		weapon.WMinAccuracy=sysItem.WMinAccuracy;
		weapon.WCrossLengthBase=sysItem.WCrossLengthBase;
		weapon.WCrossLengthFactor=sysItem.WCrossLengthFactor;
		weapon.WCrossDistanceBase=sysItem.WCrossDistanceBase;
		weapon.WCrossDistanceFactor=sysItem.WCrossDistanceFactor;
		weapon.WXOffset=sysItem.WXOffset;
		weapon.WSightNormalOffset=sysItem.WSightNormalOffset;
		weapon.WSightOnairOffset=sysItem.WSightOnairOffset;
		weapon.WSightMoveOffset=sysItem.WSightMoveOffset;
		weapon.WStabDistance=sysItem.WStabDistance;
		weapon.WStabLightDistance=sysItem.WStabLightDistance;
		weapon.WStabWidth=sysItem.WStabWidth;
		weapon.WBackFactor=sysItem.WBackFactor;
		weapon.WFlashRangeStart=sysItem.WFlashRangeStart;
		weapon.WFlashRangeEnd=sysItem.WFlashRangeEnd;
		weapon.WFlashBackFactor=sysItem.WFlashBackFactor;
		weapon.WTimeMax=sysItem.WTimeMax;
		weapon.WTimeFade=sysItem.WTimeFade;
		weapon.WTime=sysItem.WTime;
		weapon.WHitSpeed=sysItem.WHitSpeed;
	weapon.WHitAcceleration=sysItem.WHitAcceleration;
	weapon.WHitDistance=sysItem.WHitDistance;
	
	weapon.WSightInfo=sysItem.WSightInfo;
	}

	}
}