package com.pearl.fcw.utils.smarty4j;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.lilystudio.smarty4j.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.pearl.fcw.utils.O2oUtil;
import com.pearl.fcw.utils.Smarty4jUtil.Ctx;

public class TeamItemList implements Ctx {
private Logger logger = LoggerFactory.getLogger(getClass());

@SuppressWarnings({ "unchecked", "rawtypes" })
public String get(Context context) throws Exception {
StringBuilder sb = new StringBuilder();
sb.append("teamResourceWar={ ");
sb.append("\r\n");
sb.append("	placeLevel=");
sb.append(context.get("placeLevel"));
sb.append(", ");
sb.append("\r\n");
sb.append("	isLeader=");
sb.append(context.get("isLeader"));
sb.append(", ");
sb.append("\r\n");
sb.append("	resoucesNum=");
sb.append(context.get("resoucesNum"));
sb.append(", ");
sb.append("\r\n");
sb.append("	time = ");
sb.append(context.get("time"));
sb.append(", ");
sb.append("\r\n");
sb.append("	fc=");
sb.append(context.get("fc"));
sb.append(", ");
sb.append("\r\n");
sb.append("	playerRes=");
sb.append(context.get("playerRes"));
sb.append(", ");
sb.append("\r\n");
sb.append("	teamStorage={ ");
sb.append("\r\n");
if( O2oUtil.compare(context.get("storageType"),"==",1) || O2oUtil.compare(context.get("storageType"),"==",5) ){
if( O2oUtil.compare(context.get("storageType"),"==",1) ){
sb.append("				defense={ ");
sb.append("\r\n");
sb.append("					curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("					pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList256 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList256=(List<?>)context.get("itemList");
else if (context.get("itemList") instanceof int[]) itemList256=Stream.of((int[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof long[]) itemList256=Stream.of((long[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof float[]) itemList256=Stream.of((float[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof double[]) itemList256=Stream.of((double[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof byte[]) itemList256=Stream.of((byte[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof String[]) itemList256=Stream.of((String[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList").getClass().isArray()) itemList256=Stream.of(context.get("itemList")).collect(Collectors.toList());
}
itemList256.forEach(teamItem->{
try{
sb.append("					{ ");
sb.append("\r\n");
sb.append("						isEvolve=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"oilOrWallUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("						level=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("						teamItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						sysItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						display = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						name = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						description = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						maxquantity=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						buycd=\"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						durable = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"durable"));
sb.append(", ");
sb.append("\r\n");
sb.append("						resteamprice={ ");
sb.append("\r\n");
sb.append("							id=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unittype=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("							cost=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unit=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("						},	 ");
sb.append("\r\n");
sb.append("						resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList30 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList30=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof int[]) teamItemsysItemresTeamPricesList30=Stream.of((int[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof long[]) teamItemsysItemresTeamPricesList30=Stream.of((long[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof float[]) teamItemsysItemresTeamPricesList30=Stream.of((float[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof double[]) teamItemsysItemresTeamPricesList30=Stream.of((double[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof byte[]) teamItemsysItemresTeamPricesList30=Stream.of((byte[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof String[]) teamItemsysItemresTeamPricesList30=Stream.of((String[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList30=Stream.of(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList30.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e2){
logger.error(e2.toString());
}
});
sb.append("						},	    					 ");
sb.append("\r\n");
sb.append("						performance={ ");
sb.append("\r\n");
sb.append("							hp={ ");
sb.append("\r\n");
sb.append("								property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("								level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("								value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("								curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("								maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							}, ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
}catch(Exception e2){
logger.error(e2.toString());
}
});
sb.append("				}, ");
sb.append("\r\n");
}
sb.append("			 ");
sb.append("\r\n");
if( O2oUtil.compare(context.get("storageType"),"==",5) ){
sb.append("				machine={ ");
sb.append("\r\n");
sb.append("					curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("					pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList451 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList451=(List<?>)context.get("itemList");
else if (context.get("itemList") instanceof int[]) itemList451=Stream.of((int[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof long[]) itemList451=Stream.of((long[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof float[]) itemList451=Stream.of((float[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof double[]) itemList451=Stream.of((double[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof byte[]) itemList451=Stream.of((byte[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof String[]) itemList451=Stream.of((String[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList").getClass().isArray()) itemList451=Stream.of(context.get("itemList")).collect(Collectors.toList());
}
itemList451.forEach(teamItem->{
try{
sb.append("					{ ");
sb.append("\r\n");
sb.append("						isEvolve=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"oilOrWallUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("						level=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("						teamItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						sysItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						display = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						name = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						description = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						maxquantity=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						buycd=\"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						resteamprice={ ");
sb.append("\r\n");
sb.append("							id=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unittype=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("							cost=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unit=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("						},	 ");
sb.append("\r\n");
sb.append("						resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList240 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList240=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof int[]) teamItemsysItemresTeamPricesList240=Stream.of((int[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof long[]) teamItemsysItemresTeamPricesList240=Stream.of((long[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof float[]) teamItemsysItemresTeamPricesList240=Stream.of((float[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof double[]) teamItemsysItemresTeamPricesList240=Stream.of((double[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof byte[]) teamItemsysItemresTeamPricesList240=Stream.of((byte[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof String[]) teamItemsysItemresTeamPricesList240=Stream.of((String[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList240=Stream.of(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList240.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e4){
logger.error(e4.toString());
}
});
sb.append("						}, ");
sb.append("\r\n");
sb.append("						performance={ ");
sb.append("\r\n");
sb.append("							hp={ ");
sb.append("\r\n");
sb.append("								property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("								level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("								value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("								curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("								maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							}, ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
}catch(Exception e4){
logger.error(e4.toString());
}
});
sb.append("				}, ");
sb.append("\r\n");
}
}
if( O2oUtil.compare(context.get("storageType"),"==",2) ){
sb.append("			attack={ ");
sb.append("\r\n");
sb.append("				curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("				pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList453 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList453=(List<?>)context.get("itemList");
else if (context.get("itemList") instanceof int[]) itemList453=Stream.of((int[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof long[]) itemList453=Stream.of((long[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof float[]) itemList453=Stream.of((float[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof double[]) itemList453=Stream.of((double[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof byte[]) itemList453=Stream.of((byte[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList") instanceof String[]) itemList453=Stream.of((String[])context.get("itemList")).collect(Collectors.toList());
else if (context.get("itemList").getClass().isArray()) itemList453=Stream.of(context.get("itemList")).collect(Collectors.toList());
}
itemList453.forEach(teamItem->{
try{
sb.append("				{ ");
sb.append("\r\n");
sb.append("					isEvolve=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"towerIsUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("					level=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("					teamItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("					sysItemId = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("					display = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					name = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					description = \"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					maxquantity=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("					value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("					buycd=\"");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					durable = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"durable"));
sb.append(", ");
sb.append("\r\n");
sb.append("					bullet = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"bullet"));
sb.append(", ");
sb.append("\r\n");
sb.append("					resteamprice={ ");
sb.append("\r\n");
sb.append("						id=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						unittype=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("						cost=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("						unit=");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("					},		 ");
sb.append("\r\n");
sb.append("					resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList580 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList580=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof int[]) teamItemsysItemresTeamPricesList580=Stream.of((int[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof long[]) teamItemsysItemresTeamPricesList580=Stream.of((long[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof float[]) teamItemsysItemresTeamPricesList580=Stream.of((float[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof double[]) teamItemsysItemresTeamPricesList580=Stream.of((double[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof byte[]) teamItemsysItemresTeamPricesList580=Stream.of((byte[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof String[]) teamItemsysItemresTeamPricesList580=Stream.of((String[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList580=Stream.of(O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList580.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jProperty(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e6){
logger.error(e6.toString());
}
});
sb.append("					}, ");
sb.append("\r\n");
sb.append("					performance={ ");
sb.append("\r\n");
sb.append("						power={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property1.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property1.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property1.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property1.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property1.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						fireSpeed={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property2.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property2.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property2.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property2.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property2.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						hp={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						fireDistance={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property4.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property4.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property4.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property4.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property4.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						rotateSpeed={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property5.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property5.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property5.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property5.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jProperty(teamItem,"property5.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
sb.append("				}, ");
sb.append("\r\n");
}catch(Exception e6){
logger.error(e6.toString());
}
});
sb.append("			}, ");
sb.append("\r\n");
}
if( O2oUtil.compare(context.get("storageType"),"==",3) ){
sb.append("			scene={}, ");
sb.append("\r\n");
}
sb.append("	}, ");
sb.append("\r\n");
sb.append("} ");
sb.append("\r\n");
return sb.toString();
}

}