CREATE TABLE `CMS_NEWS` (
  `NEWS_ID_B` bigint(20) NOT NULL COMMENT '表主键--新闻编号',
  `NEWS_COLUMN_ID_B` bigint(20) DEFAULT NULL COMMENT '栏目编号（CMS_NEWS_COLUMN 表主键）',
  `HEADLINE_V` varchar(50) DEFAULT NULL COMMENT '正标题',
  `SUBHEAD_V` varchar(150) DEFAULT NULL COMMENT '副标题',
  `CONTENT_T` text COMMENT '新闻内容',
  `AUTHOR_V` varchar(32) DEFAULT NULL COMMENT '作者',
  `TOP_LEVEL_I` int(11) DEFAULT NULL COMMENT '置顶级别',
  `PRIORITY_LEVEL_I` int(4) DEFAULT NULL COMMENT '显示优先级',
  `HEADLINE_STATUS_I` int(1) DEFAULT NULL COMMENT '是否头条：1-是；0-不是',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '新闻状态：1-显示；0-不显示',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  `TYPE_I` int(4) DEFAULT NULL COMMENT '新闻类型：1-CMS；2-游戏；3-媒体',
  `THUMBNAILS_V` varchar(100) DEFAULT NULL COMMENT '缩略图',
  PRIMARY KEY (`NEWS_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='新闻资讯表';

CREATE TABLE `CMS_NEWS_COLUMN` (
  `NEWS_COLUMN_ID_B` bigint(20) NOT NULL COMMENT '表主键--栏目编号',
  `COLUMN_NAME_V` varchar(64) DEFAULT NULL COMMENT '栏目名称',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '栏目状态：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`NEWS_COLUMN_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资讯栏目表';

CREATE TABLE `PARTNER` (
  `ID_B` bigint(20) NOT NULL COMMENT '表主键',
  `PARTNER_ID_V` varchar(20) DEFAULT NULL COMMENT '联运商ID',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '联运商状态：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '记录版本号',
  PRIMARY KEY (`ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='联运商列表';

CREATE TABLE `PARTNER_USER` (
  `USER_ID_B` bigint(20) NOT NULL COMMENT '表主键',
  `PARTNER_ID_V` varchar(20) DEFAULT NULL COMMENT '联运商ID',
  `GAME_ACCOUNT_V` varchar(45) DEFAULT NULL COMMENT '玩家账号',
  `PASSWORD_V` varchar(50) DEFAULT NULL COMMENT '密码',
  `EMAIL_V` varchar(50) DEFAULT NULL COMMENT 'email',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '用户状态：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '记录版本号',
  PRIMARY KEY (`USER_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='联运商接入用户表';

CREATE TABLE `WEBCAFE_IP_LIST` (
  `WEBCAF_ID_B` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '表主键',
  `WEBCAF_IP` varchar(56) DEFAULT NULL COMMENT '网吧IP',
  `WEBCAF_TYPE` varchar(45) DEFAULT NULL COMMENT '网吧类别，1铜,2银,3金,',
  PRIMARY KEY (`WEBCAF_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='IP表';

CREATE TABLE `QUESTION` (
  `QUESTION_ID_B` bigint(20) NOT NULL COMMENT '表主键',
  `QUESTION_INFO_V` varchar(100) DEFAULT NULL COMMENT '问题描述',
  `ORDER_BY_ID_T` tinyint(4) DEFAULT NULL COMMENT '问题显示时的顺序',
  `STATUS_T` tinyint(4) DEFAULT NULL COMMENT '问题是否有效：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`QUESTION_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='安全问题';

CREATE TABLE `USERS` (
  `USER_ID_B` bigint(20) NOT NULL COMMENT '用户主键',
  `USER_NAME_V` varchar(45) DEFAULT NULL COMMENT '用户名',
  `PASSWORD_V` varchar(20) DEFAULT NULL COMMENT '密码',
  `ID_NAME_V` varchar(45) DEFAULT NULL COMMENT '真实姓名',
  `ID_NUMBER_V` varchar(45) DEFAULT NULL COMMENT '身份证号',
  `STATUS_T` tinyint(4) DEFAULT NULL COMMENT '用户状态',
  `BALANCE_I` int(11) DEFAULT NULL COMMENT '余额',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  `EMAIL_V` varchar(20) DEFAULT NULL COMMENT '电子邮箱',
  `MOBILE_V` varchar(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL_STATUS_T` tinyint(4) DEFAULT NULL COMMENT '邮箱状态：1-邮箱已绑定，0-邮箱未绑定',
  `MOBILE_STATUS_T` tinyint(4) DEFAULT NULL COMMENT '手机状态：1-手机已绑定，0-手机未绑定',
  `QUESTION_ID_B` bigint(20) DEFAULT NULL COMMENT 'QUESTION表的主键',
  `ANSWER_V` varchar(100) DEFAULT NULL COMMENT '安全问题的答案',
  PRIMARY KEY (`USER_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';


-- 初始化语句
INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (1, '问题1：我是什么星座的？', 1, 1, now(), now(), 1);

INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (2, '问题2：我的宠物是？', 2, 1, now(), now(), 1);

INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (3, '问题3：我的豪宅在哪里？', 3, 1, now(), now(), 1);

INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (1, '游戏攻略', 1, now(), now(), 1);

INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (2, '游戏试玩', 1, now(), now(), 1);

INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (3, '游戏MM', 1, now(), now(), 1);

INSERT INTO PARTNER
(ID_B, PARTNER_ID_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
values (1, 'partner_id_1', 1, now(), now(), 1);

insert into PARTNER
(ID_B, PARTNER_ID_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
values (2, 'partner_id_2', 1, now(), now(), 1);

insert into PARTNER
(ID_B, PARTNER_ID_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
values (3, 'partner_id_3', 0, now(), now(), 1);

create index index_partnerid on PARTNER_USER(PARTNER_ID_V);
create index index_gameaccount on PARTNER_USER(GAME_ACCOUNT_V);
