pList0={#foreach from=$pList0 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}
pList1={#foreach from=$pList1 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}
pList2={#foreach from=$pList2 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}
pList3={#foreach from=$pList3 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}
pList4={#foreach from=$pList4 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}
pList5={#foreach from=$pList5 item=p#
{#$p.playerId#,"#$p.name#",},
#/foreach#}