SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `ohtwooh` ;
CREATE SCHEMA IF NOT EXISTS `ohtwooh` DEFAULT CHARACTER SET utf8;

-- -----------------------------------------------------
-- Table `ohtwooh`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`USER` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_NAME` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NOT NULL ,
  `DELETED` CHAR(1) NOT NULL DEFAULT 'N' ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_CHARACTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_CHARACTER` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_CHARACTER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `GENDER` CHAR(1) NOT NULL ,
  `RUN_SPEED` FLOAT NULL ,
  `WALK_SPEED` FLOAT NULL ,
  `CROUCH_SPEED` FLOAT NULL ,
  `ACCEL_SPEED` FLOAT NULL ,
  `JUMP_SPEED` FLOAT NULL ,
  `THROW_SPEED` FLOAT NULL ,
  `RESOURCE_P` VARCHAR(100) NULL ,
  `RESOURCE_T` VARCHAR(100) NULL ,
  `IS_DEFAULT` CHAR(1) NOT NULL DEFAULT 'N' ,
  `IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N' ,
  `COST` INT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`PLAYER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`PLAYER` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`PLAYER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `SYS_CHARACTER_ID` INT NOT NULL ,
  `USER_ID` INT NOT NULL ,
  `NAME` VARCHAR(40) NOT NULL ,
  `TEAM_ID` INT NOT NULL DEFAULT 0 ,
  `LABOR_UNION_ID` INT NOT NULL DEFAULT 0 ,
  `GENDER` CHAR(1) NOT NULL ,
  `RESOURCE_T` VARCHAR(100) NULL ,
  `RESOURCE_P` VARCHAR(100) NULL ,
  `IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N' ,
  `G_POINT` INT UNSIGNED NOT NULL DEFAULT 0 ,
  `CREDIT` INT UNSIGNED NOT NULL DEFAULT 0 ,
  `EXP` INT UNSIGNED NOT NULL DEFAULT 0 ,
  `RANK` INT NOT NULL DEFAULT 1 ,
  `W_PACK_SIZE` TINYINT NOT NULL DEFAULT 2 ,
  `C_PACK_SIZE` TINYINT NOT NULL DEFAULT 1 ,
  `LAST_GAME_SIDE` TINYINT NULL DEFAULT 0 ,
  `LAST_LOGIN_TIME` DATETIME NULL ,
  `LAST_LOGIN_IP` VARCHAR(45) NULL ,
  `FLOWER_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `FLOWER_TODAY` INT UNSIGNED NULL DEFAULT 0 ,
  `FLOWER_LAST_TIME` DATETIME NULL ,
  `GENERAL_SCORE` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_DEAD` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_HEAD_SHOT` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_GRENADE_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_KNIFE_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_HIT_POINT` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_WIN` INT UNSIGNED NULL DEFAULT 0 ,
  `GENERAL_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_SCORE` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_DEAD` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_HEAD_SHOT` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_GRENADE_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_KNIFE_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_HIT_POINT` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_WIN` INT UNSIGNED NULL DEFAULT 0 ,
  `TEAM_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `BIO_SCORE` INT UNSIGNED NULL DEFAULT 0 ,
  `BIO_INFECT` INT UNSIGNED NULL DEFAULT 0 ,
  `BIO_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `FLAG_SCORE` INT UNSIGNED NULL DEFAULT 0 ,
  `FLAG_SUCCEED` INT UNSIGNED NULL DEFAULT 0 ,
  `FLAG_RETURN` INT UNSIGNED NULL DEFAULT 0 ,
  `FLAG_WIN` INT UNSIGNED NULL DEFAULT 0 ,
  `FLAG_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `BLAST_SCORE` INT UNSIGNED NULL DEFAULT 0 ,
  `BLAST_SUCCEED` INT UNSIGNED NULL DEFAULT 0 ,
  `BLAST_DISABLE` INT UNSIGNED NULL DEFAULT 0 ,
  `BLAST_WIN` INT UNSIGNED NULL DEFAULT 0 ,
  `BLAST_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_GP_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_CR_TOTAL` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_GRENADE_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_DROP_KILL` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_WEAPON_MOD` INT UNSIGNED NULL DEFAULT 0 ,
  `FUN_DEAD` INT UNSIGNED NULL DEFAULT 0 ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PLAYER_USER1` (`USER_ID` ASC) ,
  INDEX `fk_PLAYER_SYS_CHARACTER1` (`SYS_CHARACTER_ID` ASC) ,
  INDEX `idx_PLAYER_NAME` (`NAME` ASC) ,
  INDEX `idx_GENERAL_SCORE` (`GENERAL_SCORE` ASC) ,
  INDEX `idx_TEAM_SCORE` (`TEAM_SCORE` ASC) ,
  INDEX `idx_BIO_SCORE` (`BIO_SCORE` ASC) ,
  INDEX `idx_FLAG_SCORE` (`FLAG_SCORE` ASC) ,
  INDEX `idx_BLAST_SCORE` (`BLAST_SCORE` ASC) ,
  INDEX `idx_FUN_GP_TOTAL` (`FUN_GP_TOTAL` ASC) ,
  INDEX `idx_FUN_CR_TOTAL` (`FUN_CR_TOTAL` ASC) ,
  INDEX `idx_FUN_GRENADE_KILL` (`FUN_GRENADE_KILL` ASC) ,
  INDEX `idx_FUN_DROP_KILL` (`FUN_DROP_KILL` ASC) ,
  INDEX `idx_FUN_WEAPON_MOD` (`FUN_WEAPON_MOD` ASC) ,
  INDEX `idx_FUN_DEAD` (`FUN_DEAD` ASC) ,
  CONSTRAINT `fk_PLAYER_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `ohtwooh`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_SYS_CHARACTER1`
    FOREIGN KEY (`SYS_CHARACTER_ID` )
    REFERENCES `ohtwooh`.`SYS_CHARACTER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_ITEM` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_ITEM` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(40) NOT NULL ,
  `DISPLAY_NAME` VARCHAR(40) NULL ,
  `RESOURCE_STABLE` VARCHAR(100) NULL ,
  `RESOURCE_CHANGEABLE` VARCHAR(100) NULL ,
  `TYPE` TINYINT NOT NULL COMMENT 'Type:\n1. COSTUME\n2. WEAPON\n3. WEAPON_PART\n4. ITEM\n5. PACKAGE\n' ,
  `SUB_TYPE` TINYINT NOT NULL ,
  `CURRENCY` TINYINT NOT NULL COMMENT '0 GP\n1 CR' ,
  `UNIT_TYPE` TINYINT NOT NULL COMMENT '0 Permanent\n1 Damage Based\n2 Unit Based\n3 Time Based' ,
  `COST1` INT NOT NULL DEFAULT 0 ,
  `UNIT1` TINYINT NULL DEFAULT 0 ,
  `COST2` INT NULL DEFAULT 0 ,
  `UNIT2` TINYINT NULL DEFAULT 0 ,
  `COST3` INT NULL DEFAULT 0 ,
  `UNIT3` TINYINT NULL DEFAULT 0 ,
  `COST4` INT NULL DEFAULT 0 ,
  `UNIT4` TINYINT NULL DEFAULT 0 ,
  `COST5` INT NULL DEFAULT 0 ,
  `UNIT5` TINYINT NULL DEFAULT 0 ,
  `LEVEL` TINYINT NULL DEFAULT 1 ,
  `IS_DELETED` CHAR(1) NULL DEFAULT 'N' ,
  `MODIFIED_DESC` CHAR(20) NULL ,
  `DESCRIPTION` VARCHAR(200) NULL ,
  `W_ID` INT NOT NULL ,
  `W_CHANGE_IN_TIME` FLOAT NULL ,
  `W_MOVE_SPEED_OFFSET` FLOAT NULL ,
  `W_CROSS_OFFSET` FLOAT NULL ,
  `W_CROSS_LENGTH_BASE` FLOAT NULL ,
  `W_CROSS_LENGTH_FACTOR` FLOAT NULL ,
  `W_CROSS_DISTANCE_BASE` FLOAT NULL ,
  `W_CROSS_DISTANCE_FACTOR` FLOAT NULL ,
  `W_ACCURACY_DIVISOR` INT NULL ,
  `W_ACCURACY_OFFSET` FLOAT NULL ,
  `W_MAX_INACCURACY` FLOAT NULL ,
  `W_PENETRATION` INT NULL ,
  `W_DAMAGE` INT NULL ,
  `W_RANGE_MODIFIER` FLOAT NULL ,
  `W_RANGE_START` FLOAT NULL ,
  `W_RANGE_END` FLOAT NULL ,
  `W_FIRE_TIME` FLOAT NULL ,
  `W_RELOAD_TIME` FLOAT NULL ,
  `W_ZOOM_TIME` FLOAT NULL ,
  `W_ZOOM_VALUE` FLOAT NULL ,
  `W_AMMO_ONE_CLIP` INT NULL ,
  `W_AMMO_COUNT` INT NULL ,
  `W_AUTO_FIRE` TINYINT NULL ,
  `W_TIME_TO_IDLE` FLOAT NULL ,
  `W_NORMAL_OFFSET` FLOAT NULL ,
  `W_NORMAL_FACTOR` FLOAT NULL ,
  `W_ONAIR_OFFSET` FLOAT NULL ,
  `W_ONAIR_FACTOR` FLOAT NULL ,
  `W_MOVE_OFFSET` FLOAT NULL ,
  `W_MOVE_FACTOR` FLOAT NULL ,
  `W_NORMAL_UP_BASE` FLOAT NULL ,
  `W_NORMAL_LATERAL_BASE` FLOAT NULL ,
  `W_NORMAL_UP_MODIFIER` FLOAT NULL ,
  `W_NORMAL_LATERAL_MODIFIER` FLOAT NULL ,
  `W_NORMAL_UP_MAX` FLOAT NULL ,
  `W_NORMAL_LATERAL_MAX` FLOAT NULL ,
  `W_NORMAL_DIR_CHANGE` FLOAT NULL ,
  `W_MOVE_UP_BASE` FLOAT NULL ,
  `W_MOVE_LATERAL_BASE` FLOAT NULL ,
  `W_MOVE_UP_MODIFIER` FLOAT NULL ,
  `W_MOVE_LATERAL_MODIFIER` FLOAT NULL ,
  `W_MOVE_UP_MAX` FLOAT NULL ,
  `W_MOVE_LATERAL_MAX` FLOAT NULL ,
  `W_MOVE_DIR_CHANGE` FLOAT NULL ,
  `W_ONAIR_UP_BASE` FLOAT NULL ,
  `W_ONAIR_LATERAL_BASE` FLOAT NULL ,
  `W_ONAIR_UP_MODIFIER` FLOAT NULL ,
  `W_ONAIR_LATERAL_MODIFIER` FLOAT NULL ,
  `W_ONAIR_UP_MAX` FLOAT NULL ,
  `W_ONAIR_LATERAL_MAX` FLOAT NULL ,
  `W_ONAIR_DIR_CHANGE` FLOAT NULL ,
  `W_CROUCH_UP_BASE` FLOAT NULL ,
  `W_CROUCH_LATERAL_BASE` FLOAT NULL ,
  `W_CROUCH_UP_MODIFIER` FLOAT NULL ,
  `W_CROUCH_LATERAL_MODIFIER` FLOAT NULL ,
  `W_CROUCH_UP_MAX` FLOAT NULL ,
  `W_CROUCH_LATERAL_MAX` FLOAT NULL ,
  `W_CROUCH_DIR_CHANGE` FLOAT NULL ,
  `W_UP_MODIFIER` FLOAT NULL ,
  `W_ACCURACY_TIME` FLOAT NULL ,
  `W_ACCURACY_TIME_MODIFIER` FLOAT NULL ,
  `W_MAX_ACCURACY` FLOAT NULL ,
  `W_MIN_ACCURACY` FLOAT NULL ,
  `W_SHOOT_BULLET_COUNT` INT NULL ,
  `W_SPREAD` FLOAT NULL ,
  `W_FIRE_MAX_SPEED` FLOAT NULL ,
  `W_FIRE_START_SPEED` FLOAT NULL ,
  `W_FIRE_ACELERATION` FLOAT NULL ,
  `W_FIRE_RESISTANCE` FLOAT NULL ,
  `W_STAB_TIME` FLOAT NULL ,
  `W_STAB_LIGHT_TIME` FLOAT NULL ,
  `W_STAB_HURT` FLOAT NULL ,
  `W_STAB_LIGHT_HURT` FLOAT NULL ,
  `W_EXPLODE_TIME` FLOAT NULL ,
  `W_READY_TIME` FLOAT NULL ,
  `W_THROW_OUT_TIME` FLOAT NULL ,
  `W_HURT_RANGE` FLOAT NULL ,
  `W_HURT` FLOAT NULL ,
  `C_ID` TINYINT NOT NULL DEFAULT 0 ,
  `C_SIDE` TINYINT NULL ,
  `C_GENDER` CHAR(1) NULL ,
  `P_SUITABLE` VARCHAR(45) NULL ,
  `I_BUFF_ID` TINYINT NULL ,
  `I_VALUE` FLOAT NULL DEFAULT 0 ,
  `I_ID` TINYINT NULL ,
  `W_MAX_LENGTH` TINYINT UNSIGNED NULL ,
  `W_X_OFFSET` TINYINT NULL ,
  `W_SIGHT_NORMAL_OFFSET` FLOAT NULL ,
  `W_SIGHT_ONAIR_OFFSET` FLOAT NULL ,
  `W_SIGHT_MOVE_OFFSET` FLOAT NULL ,
  `W_STAB_DISTANCE` FLOAT NULL ,
  `W_STAB_LIGHT_DISTANCE` FLOAT NULL ,
  `W_STAB_WIDTH` FLOAT NULL ,
  `W_BACK_FACTOR` FLOAT NULL ,
  `W_FLASH_RANGE_START` FLOAT NULL ,
  `W_FLASH_RANGE_END` FLOAT NULL ,
  `W_FLASH_BACK_FACTOR` FLOAT NULL ,
  `W_TIME_MAX` FLOAT NULL ,
  `W_TIME_FADE` FLOAT NULL ,
  `W_TIME` FLOAT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`PLAYER_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`PLAYER_ITEM` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`PLAYER_ITEM` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `PLAYER_ID` INT NOT NULL ,
  `ITEM_ID` INT NOT NULL ,
  `CURRENCY` TINYINT NOT NULL ,
  `UNIT_TYPE` TINYINT NOT NULL ,
  `QUANTITY` TINYINT NOT NULL DEFAULT 1 ,
  `DURABLE` TINYINT NULL DEFAULT 100 ,
  `VALID_TIME` DATETIME NULL ,
  `EXPIRE_TIME` DATETIME NULL ,
  `IS_BIND` CHAR(1) NULL ,
  `IS_DEFAULT` CHAR(1) NULL DEFAULT 'N' ,
  `IS_GIFT` CHAR(1) NULL DEFAULT 'N' ,
  `MODIFIED_DESC` VARCHAR(20) NULL ,
  `IS_DELETED` CHAR(1) NULL DEFAULT 'N' ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PLAYER_ITEM_ITEM1` (`ITEM_ID` ASC) ,
  INDEX `fk_PLAYER_ITEM_PLAYER1` (`PLAYER_ID` ASC) ,
  INDEX `fk_PLAYER_ITEM_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `fk_PLAYER_ITEM_ITEM1`
    FOREIGN KEY (`ITEM_ID` )
    REFERENCES `ohtwooh`.`SYS_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_ITEM_PLAYER1`
    FOREIGN KEY (`PLAYER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_ITEM_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `ohtwooh`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`FRIEND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`FRIEND` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`FRIEND` (
  `USER_ID` INT NOT NULL ,
  `PLAYER_ID` INT NOT NULL ,
  `FRIEND_ID` INT NOT NULL ,
  `IS_BLACK_LIST` CHAR(1) NOT NULL DEFAULT 'N' ,
  PRIMARY KEY (`PLAYER_ID`, `FRIEND_ID`, `USER_ID`) ,
  INDEX `fk_FRIEND_PLAYER1` (`PLAYER_ID` ASC) ,
  INDEX `fk_FRIEND_PLAYER2` (`FRIEND_ID` ASC) ,
  INDEX `fk_FRIEND_IS_BLACK_LIST_INDEX` (`IS_BLACK_LIST` ASC) ,
  INDEX `fk_FRIEND_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `fk_FRIEND_PLAYER1`
    FOREIGN KEY (`PLAYER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FRIEND_PLAYER2`
    FOREIGN KEY (`FRIEND_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FRIEND_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `ohtwooh`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`MESSAGE` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`MESSAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `SENDER_ID` INT NOT NULL ,
  `RECEIVER_ID` INT NOT NULL ,
  `SUBJECT` VARCHAR(45) NULL ,
  `CONTENT` VARCHAR(300) NULL ,
  `CREATED_TIME` DATETIME NULL ,
  `OPEN` CHAR(1) NULL DEFAULT 'N' ,
  `IS_DELETED` CHAR(1) NULL DEFAULT 'N' ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_MESSAGE_PLAYER1` (`SENDER_ID` ASC) ,
  INDEX `fk_MESSAGE_PLAYER2` (`RECEIVER_ID` ASC) ,
  CONSTRAINT `fk_MESSAGE_PLAYER1`
    FOREIGN KEY (`SENDER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESSAGE_PLAYER2`
    FOREIGN KEY (`RECEIVER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`TEAM` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`TEAM` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(10) NOT NULL ,
  `DECLARATION` VARCHAR(20) NULL ,
  `DESCRIPTION` VARCHAR(50) NULL ,
  `BOARD` VARCHAR(50) NULL ,
  `LOGO` VARCHAR(40) NULL ,
  `SIZE` TINYINT NULL DEFAULT 20 ,
  `KILL` INT NULL DEFAULT 0 ,
  `HEAD_SHOT` INT NULL DEFAULT 0 ,
  `GAME_WIN` INT NULL DEFAULT 0 ,
  `GAME_TOTAL` INT NULL DEFAULT 0 ,
  `CHALLENGE_WIN` INT NULL DEFAULT 0 ,
  `CHALLENGE_TOTAL` INT NULL DEFAULT 0 ,
  `CREATED_TIME` DATETIME NULL ,
  `DELETED` CHAR(1) NULL DEFAULT 'N' ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`LOG` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `PLAYER_ID` INT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`ITEM_MOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`ITEM_MOD` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`ITEM_MOD` (
  `CHILD_ITEM_ID` INT NOT NULL ,
  `PARENT_ITEM_ID` INT NOT NULL ,
  `SEQ` TINYINT NOT NULL ,
  INDEX `fk_ITEM_MOD_PLAYER_ITEM1` (`PARENT_ITEM_ID` ASC) ,
  INDEX `fk_ITEM_MOD_PLAYER_ITEM2` (`CHILD_ITEM_ID` ASC) ,
  PRIMARY KEY (`CHILD_ITEM_ID`, `PARENT_ITEM_ID`, `SEQ`) ,
  CONSTRAINT `fk_ITEM_MOD_PLAYER_ITEM1`
    FOREIGN KEY (`PARENT_ITEM_ID` )
    REFERENCES `ohtwooh`.`PLAYER_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_MOD_PLAYER_ITEM2`
    FOREIGN KEY (`CHILD_ITEM_ID` )
    REFERENCES `ohtwooh`.`PLAYER_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_PACKAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_PACKAGE` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_PACKAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `PACKAGE_ID` INT NOT NULL ,
  `ITEM_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PACKAGE_ITEM_ITEM2` (`PACKAGE_ID` ASC) ,
  INDEX `fk_PACKAGE_ITEM_ITEM1` (`ITEM_ID` ASC) ,
  CONSTRAINT `fk_PACKAGE_ITEM_ITEM2`
    FOREIGN KEY (`PACKAGE_ID` )
    REFERENCES `ohtwooh`.`SYS_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACKAGE_ITEM_ITEM1`
    FOREIGN KEY (`ITEM_ID` )
    REFERENCES `ohtwooh`.`SYS_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`MESSAGE_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`MESSAGE_ITEM` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`MESSAGE_ITEM` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `MESSAGE_ID` INT NOT NULL ,
  `PLAYER_ITEM_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_MESSAGE_ITEM_MESSAGE1` (`MESSAGE_ID` ASC) ,
  INDEX `fk_MESSAGE_ITEM_PLAYER_ITEM1` (`PLAYER_ITEM_ID` ASC) ,
  CONSTRAINT `fk_MESSAGE_ITEM_MESSAGE1`
    FOREIGN KEY (`MESSAGE_ID` )
    REFERENCES `ohtwooh`.`MESSAGE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESSAGE_ITEM_PLAYER_ITEM1`
    FOREIGN KEY (`PLAYER_ITEM_ID` )
    REFERENCES `ohtwooh`.`PLAYER_ITEM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`PLAYER_PACK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`PLAYER_PACK` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`PLAYER_PACK` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `PLAYER_ID` INT NOT NULL ,
  `PLAYER_ITEM_ID` INT NULL ,
  `TYPE` CHAR(1) NULL ,
  `PACK_ID` SMALLINT NOT NULL ,
  `SEQ` SMALLINT NOT NULL ,
  `SIDE` TINYINT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PLAYER_PACK_PLAYER1` (`PLAYER_ID` ASC) ,
  UNIQUE INDEX `fk_PLAYER_PACK_PLAYER_ITEM_UNIQUE` (`PLAYER_ITEM_ID` ASC) ,
  INDEX `fk_PLAYER_PACK_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `fk_PLAYER_PACK_PLAYER1`
    FOREIGN KEY (`PLAYER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_PACK_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `ohtwooh`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SERVER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SERVER` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SERVER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_CHARACTER_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_CHARACTER_LOG` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_CHARACTER_LOG` (
  `GENDER` CHAR(1) NOT NULL ,
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CHARACTER_ID` INT NOT NULL ,
  `RUN_SPEED` FLOAT NULL ,
  `WALK_SPEED` FLOAT NULL ,
  `ACCEL_SPEED` TINYINT NULL ,
  `CROUCH_SPEED` FLOAT NULL ,
  `JUMP_SPEED` FLOAT NULL ,
  `THROW_SPEED` FLOAT NULL ,
  `RESOURCE_P` VARCHAR(100) NULL ,
  `RESOURCE_T` VARCHAR(100) NULL ,
  `IS_DEFAULT` CHAR(1) NOT NULL DEFAULT 'N' ,
  `COST` TINYINT NULL ,
  `VERSION` INT NOT NULL ,
  `CREATED_TIME` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`PLAYER_BUFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`PLAYER_BUFF` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`PLAYER_BUFF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `PLAYER_ID` INT NOT NULL ,
  `PLAYER_ITEM_ID` INT NULL ,
  `BUFF_ID` SMALLINT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_PLAYER_BUFF_PLAYER1` (`PLAYER_ID` ASC) ,
  UNIQUE INDEX `fk_PLAYER_BUFF_PLAYER_ITEM_UNIQUE` (`PLAYER_ITEM_ID` ASC) ,
  INDEX `fk_PLAYER_BUFF_USER1` (`USER_ID` ASC) ,
  CONSTRAINT `fk_PLAYER_BUFF_PLAYER1`
    FOREIGN KEY (`PLAYER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_BUFF_USER1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `ohtwooh`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_ITEM_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_ITEM_LOG` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_ITEM_LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(40) NOT NULL ,
  `DISPLAY_NAME` VARCHAR(40) NULL ,
  `RESOURCE_STABLE` VARCHAR(100) NULL ,
  `RESOURCE_CHANGEABLE` VARCHAR(100) NULL ,
  `TYPE` TINYINT NOT NULL COMMENT 'Type:\n1. COSTUME\n2. WEAPON\n3. WEAPON_PART\n4. ITEM\n5. PACKAGE\n' ,
  `SUB_TYPE` TINYINT NOT NULL ,
  `CURRENCY` TINYINT NOT NULL COMMENT '0 GP\n1 CR' ,
  `UNIT_TYPE` TINYINT NOT NULL COMMENT '0 Permanent\n1 Damage Based\n2 Unit Based\n3 Time Based' ,
  `COST1` INT NOT NULL DEFAULT 0 ,
  `UNIT1` TINYINT NULL DEFAULT 0 ,
  `COST2` INT NULL DEFAULT 0 ,
  `UNIT2` TINYINT NULL DEFAULT 0 ,
  `COST3` INT NULL DEFAULT 0 ,
  `UNIT3` TINYINT NULL DEFAULT 0 ,
  `COST4` INT NULL DEFAULT 0 ,
  `UNIT4` TINYINT NULL DEFAULT 0 ,
  `COST5` INT NULL DEFAULT 0 ,
  `UNIT5` TINYINT NULL DEFAULT 0 ,
  `LEVEL` TINYINT NULL DEFAULT 1 ,
  `IS_DELETED` CHAR(1) NULL DEFAULT 'N' ,
  `MODIFIED_DESC` CHAR(20) NULL ,
  `DESCRIPTION` VARCHAR(200) NULL ,
  `W_ID` INT NOT NULL ,
  `W_CHANGE_IN_TIME` FLOAT NULL ,
  `W_MOVE_SPEED_OFFSET` FLOAT NULL ,
  `W_CROSS_OFFSET` FLOAT NULL ,
  `W_CROSS_LENGTH_BASE` FLOAT NULL ,
  `W_CROSS_LENGTH_FACTOR` FLOAT NULL ,
  `W_CROSS_DISTANCE_BASE` FLOAT NULL ,
  `W_CROSS_DISTANCE_FACTOR` FLOAT NULL ,
  `W_ACCURACY_DIVISOR` INT NULL ,
  `W_ACCURACY_OFFSET` FLOAT NULL ,
  `W_MAX_INACCURACY` FLOAT NULL ,
  `W_PENETRATION` INT NULL ,
  `W_DAMAGE` INT NULL ,
  `W_RANGE_MODIFIER` FLOAT NULL ,
  `W_RANGE_START` FLOAT NULL ,
  `W_RANGE_END` FLOAT NULL ,
  `W_FIRE_TIME` FLOAT NULL ,
  `W_RELOAD_TIME` FLOAT NULL ,
  `W_ZOOM_TIME` FLOAT NULL ,
  `W_ZOOM_VALUE` FLOAT NULL ,
  `W_AMMO_ONE_CLIP` INT NULL ,
  `W_AMMO_COUNT` INT NULL ,
  `W_AUTO_FIRE` TINYINT NULL ,
  `W_TIME_TO_IDLE` FLOAT NULL ,
  `W_NORMAL_OFFSET` FLOAT NULL ,
  `W_NORMAL_FACTOR` FLOAT NULL ,
  `W_ONAIR_OFFSET` FLOAT NULL ,
  `W_ONAIR_FACTOR` FLOAT NULL ,
  `W_MOVE_OFFSET` FLOAT NULL ,
  `W_MOVE_FACTOR` FLOAT NULL ,
  `W_NORMAL_UP_BASE` FLOAT NULL ,
  `W_NORMAL_LATERAL_BASE` FLOAT NULL ,
  `W_NORMAL_UP_MODIFIER` FLOAT NULL ,
  `W_NORMAL_LATERAL_MODIFIER` FLOAT NULL ,
  `W_NORMAL_UP_MAX` FLOAT NULL ,
  `W_NORMAL_LATERAL_MAX` FLOAT NULL ,
  `W_NORMAL_DIR_CHANGE` FLOAT NULL ,
  `W_MOVE_UP_BASE` FLOAT NULL ,
  `W_MOVE_LATERAL_BASE` FLOAT NULL ,
  `W_MOVE_UP_MODIFIER` FLOAT NULL ,
  `W_MOVE_LATERAL_MODIFIER` FLOAT NULL ,
  `W_MOVE_UP_MAX` FLOAT NULL ,
  `W_MOVE_LATERAL_MAX` FLOAT NULL ,
  `W_MOVE_DIR_CHANGE` FLOAT NULL ,
  `W_ONAIR_UP_BASE` FLOAT NULL ,
  `W_ONAIR_LATERAL_BASE` FLOAT NULL ,
  `W_ONAIR_UP_MODIFIER` FLOAT NULL ,
  `W_ONAIR_LATERAL_MODIFIER` FLOAT NULL ,
  `W_ONAIR_UP_MAX` FLOAT NULL ,
  `W_ONAIR_LATERAL_MAX` FLOAT NULL ,
  `W_ONAIR_DIR_CHANGE` FLOAT NULL ,
  `W_CROUCH_UP_BASE` FLOAT NULL ,
  `W_CROUCH_LATERAL_BASE` FLOAT NULL ,
  `W_CROUCH_UP_MODIFIER` FLOAT NULL ,
  `W_CROUCH_LATERAL_MODIFIER` FLOAT NULL ,
  `W_CROUCH_UP_MAX` FLOAT NULL ,
  `W_CROUCH_LATERAL_MAX` FLOAT NULL ,
  `W_CROUCH_DIR_CHANGE` FLOAT NULL ,
  `W_UP_MODIFIER` FLOAT NULL ,
  `W_ACCURACY_TIME` FLOAT NULL ,
  `W_ACCURACY_TIME_MODIFIER` FLOAT NULL ,
  `W_MAX_ACCURACY` FLOAT NULL ,
  `W_MIN_ACCURACY` FLOAT NULL ,
  `W_SHOOT_BULLET_COUNT` INT NULL ,
  `W_SPREAD` FLOAT NULL ,
  `W_FIRE_MAX_SPEED` FLOAT NULL ,
  `W_FIRE_START_SPEED` FLOAT NULL ,
  `W_FIRE_ACELERATION` FLOAT NULL ,
  `W_FIRE_RESISTANCE` FLOAT NULL ,
  `W_STAB_TIME` FLOAT NULL ,
  `W_STAB_LIGHT_TIME` FLOAT NULL ,
  `W_STAB_HURT` FLOAT NULL ,
  `W_STAB_LIGHT_HURT` FLOAT NULL ,
  `W_EXPLODE_TIME` FLOAT NULL ,
  `W_READY_TIME` FLOAT NULL ,
  `W_THROW_OUT_TIME` FLOAT NULL ,
  `W_HURT_RANGE` FLOAT NULL ,
  `W_HURT` FLOAT NULL ,
  `C_ID` TINYINT NOT NULL DEFAULT 0 ,
  `C_SIDE` TINYINT NULL ,
  `C_GENDER` CHAR(1) NULL ,
  `P_SUITABLE` VARCHAR(45) NULL ,
  `I_BUFF_ID` TINYINT NULL ,
  `I_VALUE` FLOAT NULL DEFAULT 0 ,
  `I_ID` TINYINT NULL ,
  `W_MAX_LENGTH` TINYINT UNSIGNED NULL ,
  `W_X_OFFSET` TINYINT NULL ,
  `W_SIGHT_NORMAL_OFFSET` FLOAT NULL ,
  `W_SIGHT_ONAIR_OFFSET` FLOAT NULL ,
  `W_SIGHT_MOVE_OFFSET` FLOAT NULL ,
  `W_STAB_DISTANCE` FLOAT NULL ,
  `W_STAB_LIGHT_DISTANCE` FLOAT NULL ,
  `W_STAB_WIDTH` FLOAT NULL ,
  `W_BACK_FACTOR` FLOAT NULL ,
  `W_FLASH_RANGE_START` FLOAT NULL ,
  `W_FLASH_RANGE_END` FLOAT NULL ,
  `W_FLASH_BACK_FACTOR` FLOAT NULL ,
  `W_TIME_MAX` FLOAT NULL ,
  `W_TIME_FADE` FLOAT NULL ,
  `W_TIME` FLOAT NULL ,
  `ITEM_ID` INT NOT NULL ,
  `VERSION` INT NULL DEFAULT 0 ,
  `CREATED_TIME` DATETIME NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`CHANNEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`CHANNEL` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`CHANNEL` (
  `ID` INT NOT NULL ,
  `SERVER_ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  INDEX `fk_CHANNEL_SERVER1` (`SERVER_ID` ASC) ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `fk_CHANNEL_SERVER1`
    FOREIGN KEY (`SERVER_ID` )
    REFERENCES `ohtwooh`.`SERVER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`ITEM_ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`ITEM_ORDER` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`ITEM_ORDER` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CONTEXT_ID` VARCHAR(64) NULL ,
  `PAYTYPE` VARCHAR(32) NULL ,
  `O2O_USER_ID` INT NULL ,
  `PLAYER_ID` INT NULL ,
  `STATE` VARCHAR(64) NULL ,
  `AMOUNT` INT NULL ,
  `LASTMODIFYTIME` DATETIME NULL ,
  `GOODS_INFO` VARCHAR(256) NULL ,
  `ENDPOINT_IP` VARCHAR(32) NULL ,
  `AREAID` INT NULL ,
  `GROUPID` INT NULL ,
  `SDO_USER_ID` VARCHAR(32) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_RANK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_RANK` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_RANK` (
  `ID` INT NOT NULL ,
  `TITLE` VARCHAR(20) NOT NULL ,
  `EXP` INT NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_LEVEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_LEVEL` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_LEVEL` (
  `ID` TINYINT NOT NULL AUTO_INCREMENT ,
  `TYPE` TINYINT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `START_POINTS` VARCHAR(512) NULL COMMENT 'teamid,x,y,z,rotate;' ,
  `BLAST_POINTS` VARCHAR(50) NULL COMMENT 'x,y,z;' ,
  `FLAG_POINTS` VARCHAR(50) NULL COMMENT 'teamid,x,y,z,rotate;' ,
  `WEAPON_POINTS` VARCHAR(512) NULL COMMENT 'weaponid,x,y,z,rotate;' ,
  `SUPPLY_POINTS` VARCHAR(512) NULL COMMENT 'x,y,z;' ,
  `SUPPLIES` VARCHAR(512) NULL COMMENT 'teamid,type,name,value;' ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `UNI_TYPE_NAME` (`TYPE` ASC, `NAME` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_LEVEL_WEAPON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_LEVEL_WEAPON` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_LEVEL_WEAPON` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `SYS_ITEM_ID` INT NULL ,
  `SYS_LEVEL_ID` TINYINT NOT NULL ,
  `NAME` VARCHAR(40) NOT NULL ,
  `DISPLAY_NAME` VARCHAR(40) NULL ,
  `RESOURCE_STABLE` VARCHAR(100) NULL ,
  `RESOURCE_CHANGEABLE` VARCHAR(100) NULL ,
  `DESCRIPTION` VARCHAR(200) NULL ,
  `W_ID` INT NOT NULL ,
  `W_CHANGE_IN_TIME` FLOAT NULL ,
  `W_MOVE_SPEED_OFFSET` FLOAT NULL ,
  `W_CROSS_OFFSET` FLOAT NULL ,
  `W_CROSS_LENGTH_BASE` FLOAT NULL ,
  `W_CROSS_LENGTH_FACTOR` FLOAT NULL ,
  `W_CROSS_DISTANCE_BASE` FLOAT NULL ,
  `W_CROSS_DISTANCE_FACTOR` FLOAT NULL ,
  `W_ACCURACY_DIVISOR` INT NULL ,
  `W_ACCURACY_OFFSET` FLOAT NULL ,
  `W_MAX_INACCURACY` FLOAT NULL ,
  `W_PENETRATION` INT NULL ,
  `W_DAMAGE` INT NULL ,
  `W_RANGE_MODIFIER` FLOAT NULL ,
  `W_RANGE_START` FLOAT NULL ,
  `W_RANGE_END` FLOAT NULL ,
  `W_FIRE_TIME` FLOAT NULL ,
  `W_RELOAD_TIME` FLOAT NULL ,
  `W_ZOOM_TIME` FLOAT NULL ,
  `W_ZOOM_VALUE` FLOAT NULL ,
  `W_AMMO_ONE_CLIP` INT NULL ,
  `W_AMMO_COUNT` INT NULL ,
  `W_AUTO_FIRE` TINYINT NULL ,
  `W_TIME_TO_IDLE` FLOAT NULL ,
  `W_NORMAL_OFFSET` FLOAT NULL ,
  `W_NORMAL_FACTOR` FLOAT NULL ,
  `W_ONAIR_OFFSET` FLOAT NULL ,
  `W_ONAIR_FACTOR` FLOAT NULL ,
  `W_MOVE_OFFSET` FLOAT NULL ,
  `W_MOVE_FACTOR` FLOAT NULL ,
  `W_NORMAL_UP_BASE` FLOAT NULL ,
  `W_NORMAL_LATERAL_BASE` FLOAT NULL ,
  `W_NORMAL_UP_MODIFIER` FLOAT NULL ,
  `W_NORMAL_LATERAL_MODIFIER` FLOAT NULL ,
  `W_NORMAL_UP_MAX` FLOAT NULL ,
  `W_NORMAL_LATERAL_MAX` FLOAT NULL ,
  `W_NORMAL_DIR_CHANGE` FLOAT NULL ,
  `W_MOVE_UP_BASE` FLOAT NULL ,
  `W_MOVE_LATERAL_BASE` FLOAT NULL ,
  `W_MOVE_UP_MODIFIER` FLOAT NULL ,
  `W_MOVE_LATERAL_MODIFIER` FLOAT NULL ,
  `W_MOVE_UP_MAX` FLOAT NULL ,
  `W_MOVE_LATERAL_MAX` FLOAT NULL ,
  `W_MOVE_DIR_CHANGE` FLOAT NULL ,
  `W_ONAIR_UP_BASE` FLOAT NULL ,
  `W_ONAIR_LATERAL_BASE` FLOAT NULL ,
  `W_ONAIR_UP_MODIFIER` FLOAT NULL ,
  `W_ONAIR_LATERAL_MODIFIER` FLOAT NULL ,
  `W_ONAIR_UP_MAX` FLOAT NULL ,
  `W_ONAIR_LATERAL_MAX` FLOAT NULL ,
  `W_ONAIR_DIR_CHANGE` FLOAT NULL ,
  `W_CROUCH_UP_BASE` FLOAT NULL ,
  `W_CROUCH_LATERAL_BASE` FLOAT NULL ,
  `W_CROUCH_UP_MODIFIER` FLOAT NULL ,
  `W_CROUCH_LATERAL_MODIFIER` FLOAT NULL ,
  `W_CROUCH_UP_MAX` FLOAT NULL ,
  `W_CROUCH_LATERAL_MAX` FLOAT NULL ,
  `W_CROUCH_DIR_CHANGE` FLOAT NULL ,
  `W_UP_MODIFIER` FLOAT NULL ,
  `W_ACCURACY_TIME` FLOAT NULL ,
  `W_ACCURACY_TIME_MODIFIER` FLOAT NULL ,
  `W_MAX_ACCURACY` FLOAT NULL ,
  `W_MIN_ACCURACY` FLOAT NULL ,
  `W_SHOOT_BULLET_COUNT` INT NULL ,
  `W_SPREAD` FLOAT NULL ,
  `W_FIRE_MAX_SPEED` FLOAT NULL ,
  `W_FIRE_START_SPEED` FLOAT NULL ,
  `W_FIRE_ACELERATION` FLOAT NULL ,
  `W_FIRE_RESISTANCE` FLOAT NULL ,
  `W_STAB_TIME` FLOAT NULL ,
  `W_STAB_LIGHT_TIME` FLOAT NULL ,
  `W_STAB_HURT` FLOAT NULL ,
  `W_STAB_LIGHT_HURT` FLOAT NULL ,
  `W_EXPLODE_TIME` FLOAT NULL ,
  `W_READY_TIME` FLOAT NULL ,
  `W_THROW_OUT_TIME` FLOAT NULL ,
  `W_HURT_RANGE` FLOAT NULL ,
  `W_HURT` FLOAT NULL ,
  `W_MAX_LENGTH` TINYINT UNSIGNED NULL ,
  `W_X_OFFSET` TINYINT NULL ,
  `W_SIGHT_NORMAL_OFFSET` BINARY NULL ,
  `W_SIGHT_ONAIR_OFFSET` FLOAT NULL ,
  `W_SIGHT_MOVE_OFFSET` FLOAT NULL ,
  `W_STAB_DISTANCE` FLOAT NULL ,
  `W_STAB_LIGHT_DISTANCE` FLOAT NULL ,
  `W_STAB_WIDTH` FLOAT NULL ,
  `W_BACK_FACTOR` FLOAT NULL ,
  `W_FLASH_RANGE_START` FLOAT NULL ,
  `W_FLASH_RANGE_END` FLOAT NULL ,
  `W_FLASH_BACK_FACTOR` FLOAT NULL ,
  `W_TIME_MAX` FLOAT NULL ,
  `W_TIME_FADE` FLOAT NULL ,
  `W_TIME` FLOAT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SYS_LEVEL_WEAPON_SYS_LEVEL1` (`SYS_LEVEL_ID` ASC) ,
  CONSTRAINT `fk_SYS_LEVEL_WEAPON_SYS_LEVEL1`
    FOREIGN KEY (`SYS_LEVEL_ID` )
    REFERENCES `ohtwooh`.`SYS_LEVEL` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`PLAYER_TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`PLAYER_TEAM` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`PLAYER_TEAM` (
  `PLAYER_ID` INT NOT NULL ,
  `TEAM_ID` INT NOT NULL ,
  `JOB` TINYINT NULL DEFAULT 1 ,
  `KILL` INT NULL DEFAULT 0 ,
  `DEAD` INT NULL DEFAULT 0 ,
  `CREATED_TIME` DATETIME NULL ,
  `APPROVED` CHAR(1) NULL DEFAULT 'N' ,
  PRIMARY KEY (`PLAYER_ID`) ,
  INDEX `fk_PLAYER_TEAM_PLAYER1` (`PLAYER_ID` ASC) ,
  INDEX `fk_PLAYER_TEAM_TEAM1` (`TEAM_ID` ASC) ,
  CONSTRAINT `fk_PLAYER_TEAM_PLAYER1`
    FOREIGN KEY (`PLAYER_ID` )
    REFERENCES `ohtwooh`.`PLAYER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYER_TEAM_TEAM1`
    FOREIGN KEY (`TEAM_ID` )
    REFERENCES `ohtwooh`.`TEAM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`ALLY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`ALLY` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`ALLY` (
  `TEAM_ID` INT NOT NULL ,
  `ALLY_ID` INT NOT NULL ,
  PRIMARY KEY (`TEAM_ID`, `ALLY_ID`) ,
  INDEX `fk_ALLY_TEAM1` (`TEAM_ID` ASC) ,
  INDEX `fk_ALLY_TEAM2` (`ALLY_ID` ASC) ,
  CONSTRAINT `fk_ALLY_TEAM1`
    FOREIGN KEY (`TEAM_ID` )
    REFERENCES `ohtwooh`.`TEAM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALLY_TEAM2`
    FOREIGN KEY (`ALLY_ID` )
    REFERENCES `ohtwooh`.`TEAM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`TEAM_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`TEAM_HISTORY` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`TEAM_HISTORY` (
  `TEAM_ID` INT NOT NULL ,
  `OPPONENT` VARCHAR(10) NULL ,
  `ATTENDEES` VARCHAR(100) NULL COMMENT 'name,name,name' ,
  `RESULT` CHAR(1) NULL DEFAULT 0 COMMENT '0 lose | 1 win' ,
  `CREATED_TIME` DATETIME NULL )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_MODE_CONFIG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_MODE_CONFIG` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_MODE_CONFIG` (
  `TYPE` TINYINT NOT NULL COMMENT '0: team;  1: blast;  2: flag;  3: bio;' ,
  `CONFIG` TEXT NULL ,
  UNIQUE INDEX `TYPE_UNIQUE` (`TYPE` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ohtwooh`.`SYS_CONFIG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ohtwooh`.`SYS_CONFIG` ;

CREATE  TABLE IF NOT EXISTS `ohtwooh`.`SYS_CONFIG` (
  `KEY` VARCHAR(40) NOT NULL ,
  `VALUE` VARCHAR(100) NULL ,
  PRIMARY KEY (`KEY`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
