// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/status.proto

package com.pearl.fcw.proto.enums;

/**
 * <pre>
 *客户端模块状态(对应Player的tutorial字段)
 * </pre>
 *
 * Protobuf enum {@code fcw.proto.enums.status.EClientModuleStatus}
 */
public enum EClientModuleStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *关闭
   * </pre>
   *
   * <code>MODULE_CLOSE = 0;</code>
   */
  MODULE_CLOSE(0),
  /**
   * <pre>
   *完成
   * </pre>
   *
   * <code>MODULE_FLASH = 1;</code>
   */
  MODULE_FLASH(1),
  /**
   * <pre>
   *开启
   * </pre>
   *
   * <code>MODULE_OPEN = 2;</code>
   */
  MODULE_OPEN(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *关闭
   * </pre>
   *
   * <code>MODULE_CLOSE = 0;</code>
   */
  public static final int MODULE_CLOSE_VALUE = 0;
  /**
   * <pre>
   *完成
   * </pre>
   *
   * <code>MODULE_FLASH = 1;</code>
   */
  public static final int MODULE_FLASH_VALUE = 1;
  /**
   * <pre>
   *开启
   * </pre>
   *
   * <code>MODULE_OPEN = 2;</code>
   */
  public static final int MODULE_OPEN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EClientModuleStatus valueOf(int value) {
    return forNumber(value);
  }

  public static EClientModuleStatus forNumber(int value) {
    switch (value) {
      case 0: return MODULE_CLOSE;
      case 1: return MODULE_FLASH;
      case 2: return MODULE_OPEN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EClientModuleStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EClientModuleStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EClientModuleStatus>() {
          public EClientModuleStatus findValueByNumber(int number) {
            return EClientModuleStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pearl.fcw.proto.enums.ApiProto.getDescriptor()
        .getEnumTypes().get(3);
  }

  private static final EClientModuleStatus[] VALUES = values();

  public static EClientModuleStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EClientModuleStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fcw.proto.enums.status.EClientModuleStatus)
}

