// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/type.proto

package com.pearl.fcw.proto.enums;

/**
 * <pre>
 *客户端模块类型，对应Player的tutorial字段
 * </pre>
 *
 * Protobuf enum {@code fcw.proto.enums.type.EClientModuleType}
 */
public enum EClientModuleType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *任务系统 
   * </pre>
   *
   * <code>MODULE_MISSION = 0;</code>
   */
  MODULE_MISSION(0),
  /**
   * <pre>
   *每日任务
   * </pre>
   *
   * <code>MODULE_DAILY_MISSION = 1;</code>
   */
  MODULE_DAILY_MISSION(1),
  /**
   * <pre>
   *合成
   * </pre>
   *
   * <code>MODULE_COMPOSE = 2;</code>
   */
  MODULE_COMPOSE(2),
  /**
   * <pre>
   *在线时长
   * </pre>
   *
   * <code>MODULE_ONLINE = 3;</code>
   */
  MODULE_ONLINE(3),
  /**
   * <pre>
   *博彩
   * </pre>
   *
   * <code>MODULE_PRESENT = 4;</code>
   */
  MODULE_PRESENT(4),
  /**
   * <pre>
   *每日签到
   * </pre>
   *
   * <code>MODULE_DAILY_CHECK = 5;</code>
   */
  MODULE_DAILY_CHECK(5),
  /**
   * <pre>
   *免费兑换区
   * </pre>
   *
   * <code>MODULE_FREECHANGE = 6;</code>
   */
  MODULE_FREECHANGE(6),
  /**
   * <pre>
   *打靶场
   * </pre>
   *
   * <code>MODULE_SHOT = 7;</code>
   */
  MODULE_SHOT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *任务系统 
   * </pre>
   *
   * <code>MODULE_MISSION = 0;</code>
   */
  public static final int MODULE_MISSION_VALUE = 0;
  /**
   * <pre>
   *每日任务
   * </pre>
   *
   * <code>MODULE_DAILY_MISSION = 1;</code>
   */
  public static final int MODULE_DAILY_MISSION_VALUE = 1;
  /**
   * <pre>
   *合成
   * </pre>
   *
   * <code>MODULE_COMPOSE = 2;</code>
   */
  public static final int MODULE_COMPOSE_VALUE = 2;
  /**
   * <pre>
   *在线时长
   * </pre>
   *
   * <code>MODULE_ONLINE = 3;</code>
   */
  public static final int MODULE_ONLINE_VALUE = 3;
  /**
   * <pre>
   *博彩
   * </pre>
   *
   * <code>MODULE_PRESENT = 4;</code>
   */
  public static final int MODULE_PRESENT_VALUE = 4;
  /**
   * <pre>
   *每日签到
   * </pre>
   *
   * <code>MODULE_DAILY_CHECK = 5;</code>
   */
  public static final int MODULE_DAILY_CHECK_VALUE = 5;
  /**
   * <pre>
   *免费兑换区
   * </pre>
   *
   * <code>MODULE_FREECHANGE = 6;</code>
   */
  public static final int MODULE_FREECHANGE_VALUE = 6;
  /**
   * <pre>
   *打靶场
   * </pre>
   *
   * <code>MODULE_SHOT = 7;</code>
   */
  public static final int MODULE_SHOT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EClientModuleType valueOf(int value) {
    return forNumber(value);
  }

  public static EClientModuleType forNumber(int value) {
    switch (value) {
      case 0: return MODULE_MISSION;
      case 1: return MODULE_DAILY_MISSION;
      case 2: return MODULE_COMPOSE;
      case 3: return MODULE_ONLINE;
      case 4: return MODULE_PRESENT;
      case 5: return MODULE_DAILY_CHECK;
      case 6: return MODULE_FREECHANGE;
      case 7: return MODULE_SHOT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EClientModuleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EClientModuleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EClientModuleType>() {
          public EClientModuleType findValueByNumber(int number) {
            return EClientModuleType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pearl.fcw.proto.enums.ApiProto.getDescriptor()
        .getEnumTypes().get(4);
  }

  private static final EClientModuleType[] VALUES = values();

  public static EClientModuleType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EClientModuleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fcw.proto.enums.type.EClientModuleType)
}

