// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/status.proto

package com.pearl.fcw.proto.enums;

/**
 * <pre>
 *玩家支付状态
 * </pre>
 *
 * Protobuf enum {@code fcw.proto.enums.status.EPayStatus}
 */
public enum EPayStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *支付成功
   * </pre>
   *
   * <code>PAY_SUCCESS = 0;</code>
   */
  PAY_SUCCESS(0),
  /**
   * <pre>
   *支付失败
   * </pre>
   *
   * <code>PAY_FAIL = 1;</code>
   */
  PAY_FAIL(1),
  /**
   * <pre>
   *货币不足
   * </pre>
   *
   * <code>PAY_NOT_ENOUGH = 2;</code>
   */
  PAY_NOT_ENOUGH(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *支付成功
   * </pre>
   *
   * <code>PAY_SUCCESS = 0;</code>
   */
  public static final int PAY_SUCCESS_VALUE = 0;
  /**
   * <pre>
   *支付失败
   * </pre>
   *
   * <code>PAY_FAIL = 1;</code>
   */
  public static final int PAY_FAIL_VALUE = 1;
  /**
   * <pre>
   *货币不足
   * </pre>
   *
   * <code>PAY_NOT_ENOUGH = 2;</code>
   */
  public static final int PAY_NOT_ENOUGH_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EPayStatus valueOf(int value) {
    return forNumber(value);
  }

  public static EPayStatus forNumber(int value) {
    switch (value) {
      case 0: return PAY_SUCCESS;
      case 1: return PAY_FAIL;
      case 2: return PAY_NOT_ENOUGH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EPayStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EPayStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EPayStatus>() {
          public EPayStatus findValueByNumber(int number) {
            return EPayStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pearl.fcw.proto.enums.ApiProto.getDescriptor()
        .getEnumTypes().get(6);
  }

  private static final EPayStatus[] VALUES = values();

  public static EPayStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EPayStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fcw.proto.enums.status.EPayStatus)
}

