// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/type.proto

package com.pearl.fcw.proto.enums;

/**
 * <pre>
 *页游整合后的任务在客户端显示的类型(sysQuest.uiType)
 * </pre>
 *
 * Protobuf enum {@code fcw.proto.enums.type.EQuestUiType}
 */
public enum EQuestUiType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>QUEST_UI_NONE = 0;</code>
   */
  QUEST_UI_NONE(0),
  /**
   * <pre>
   *老成就
   * </pre>
   *
   * <code>AULD_ACHIEVEMENT = 1;</code>
   */
  AULD_ACHIEVEMENT(1),
  /**
   * <pre>
   *老任务
   * </pre>
   *
   * <code>AULD_MISSION = 2;</code>
   */
  AULD_MISSION(2),
  /**
   * <pre>
   *新手引导
   * </pre>
   *
   * <code>NEW_GUIDE = 3;</code>
   */
  NEW_GUIDE(3),
  /**
   * <pre>
   *在线时长
   * </pre>
   *
   * <code>ONLINE_INTERVAL = 4;</code>
   */
  ONLINE_INTERVAL(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>QUEST_UI_NONE = 0;</code>
   */
  public static final int QUEST_UI_NONE_VALUE = 0;
  /**
   * <pre>
   *老成就
   * </pre>
   *
   * <code>AULD_ACHIEVEMENT = 1;</code>
   */
  public static final int AULD_ACHIEVEMENT_VALUE = 1;
  /**
   * <pre>
   *老任务
   * </pre>
   *
   * <code>AULD_MISSION = 2;</code>
   */
  public static final int AULD_MISSION_VALUE = 2;
  /**
   * <pre>
   *新手引导
   * </pre>
   *
   * <code>NEW_GUIDE = 3;</code>
   */
  public static final int NEW_GUIDE_VALUE = 3;
  /**
   * <pre>
   *在线时长
   * </pre>
   *
   * <code>ONLINE_INTERVAL = 4;</code>
   */
  public static final int ONLINE_INTERVAL_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EQuestUiType valueOf(int value) {
    return forNumber(value);
  }

  public static EQuestUiType forNumber(int value) {
    switch (value) {
      case 0: return QUEST_UI_NONE;
      case 1: return AULD_ACHIEVEMENT;
      case 2: return AULD_MISSION;
      case 3: return NEW_GUIDE;
      case 4: return ONLINE_INTERVAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EQuestUiType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EQuestUiType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EQuestUiType>() {
          public EQuestUiType findValueByNumber(int number) {
            return EQuestUiType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pearl.fcw.proto.enums.ApiProto.getDescriptor()
        .getEnumTypes().get(27);
  }

  private static final EQuestUiType[] VALUES = values();

  public static EQuestUiType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EQuestUiType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fcw.proto.enums.type.EQuestUiType)
}

