// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums/type.proto

package com.pearl.fcw.proto.enums;

/**
 * <pre>
 *物品消耗类型。对应sysItem的unitType
 * </pre>
 *
 * Protobuf enum {@code fcw.proto.enums.type.EUnitType}
 */
public enum EUnitType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *永久
   * </pre>
   *
   * <code>FOREVER = 0;</code>
   */
  FOREVER(0),
  /**
   * <pre>
   *基于数量
   * </pre>
   *
   * <code>QUANTITY = 1;</code>
   */
  QUANTITY(1),
  /**
   * <pre>
   *基于时间
   * </pre>
   *
   * <code>TIME = 2;</code>
   */
  TIME(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *永久
   * </pre>
   *
   * <code>FOREVER = 0;</code>
   */
  public static final int FOREVER_VALUE = 0;
  /**
   * <pre>
   *基于数量
   * </pre>
   *
   * <code>QUANTITY = 1;</code>
   */
  public static final int QUANTITY_VALUE = 1;
  /**
   * <pre>
   *基于时间
   * </pre>
   *
   * <code>TIME = 2;</code>
   */
  public static final int TIME_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EUnitType valueOf(int value) {
    return forNumber(value);
  }

  public static EUnitType forNumber(int value) {
    switch (value) {
      case 0: return FOREVER;
      case 1: return QUANTITY;
      case 2: return TIME;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EUnitType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EUnitType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EUnitType>() {
          public EUnitType findValueByNumber(int number) {
            return EUnitType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.pearl.fcw.proto.enums.ApiProto.getDescriptor()
        .getEnumTypes().get(13);
  }

  private static final EUnitType[] VALUES = values();

  public static EUnitType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EUnitType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fcw.proto.enums.type.EUnitType)
}

