// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * Protobuf type {@code fcw.proto.model.ProtoSysItemGunProperty}
 */
public  final class ProtoSysItemGunProperty extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoSysItemGunProperty)
    ProtoSysItemGunPropertyOrBuilder {
  // Use ProtoSysItemGunProperty.newBuilder() to construct.
  private ProtoSysItemGunProperty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoSysItemGunProperty() {
    color_ = 0;
    basePropertyStr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoSysItemGunProperty(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            color_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            basePropertyStr_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemGunProperty_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemGunProperty_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoSysItemGunProperty.class, com.pearl.fcw.proto.model.ProtoSysItemGunProperty.Builder.class);
  }

  public static final int COLOR_FIELD_NUMBER = 1;
  private int color_;
  /**
   * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
   */
  public int getColorValue() {
    return color_;
  }
  /**
   * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
   */
  public com.pearl.fcw.proto.enums.EItemColor getColor() {
    com.pearl.fcw.proto.enums.EItemColor result = com.pearl.fcw.proto.enums.EItemColor.forNumber(color_);
    return result == null ? com.pearl.fcw.proto.enums.EItemColor.UNRECOGNIZED : result;
  }

  public static final int BASEPROPERTYSTR_FIELD_NUMBER = 2;
  private volatile java.lang.Object basePropertyStr_;
  /**
   * <pre>
   *似乎没有用
   * </pre>
   *
   * <code>optional string basePropertyStr = 2;</code>
   */
  public java.lang.String getBasePropertyStr() {
    java.lang.Object ref = basePropertyStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      basePropertyStr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *似乎没有用
   * </pre>
   *
   * <code>optional string basePropertyStr = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBasePropertyStrBytes() {
    java.lang.Object ref = basePropertyStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      basePropertyStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (color_ != com.pearl.fcw.proto.enums.EItemColor.TRANSPARENT.getNumber()) {
      output.writeEnum(1, color_);
    }
    if (!getBasePropertyStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, basePropertyStr_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (color_ != com.pearl.fcw.proto.enums.EItemColor.TRANSPARENT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, color_);
    }
    if (!getBasePropertyStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, basePropertyStr_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoSysItemGunProperty)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoSysItemGunProperty other = (com.pearl.fcw.proto.model.ProtoSysItemGunProperty) obj;

    boolean result = true;
    result = result && color_ == other.color_;
    result = result && getBasePropertyStr()
        .equals(other.getBasePropertyStr());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + color_;
    hash = (37 * hash) + BASEPROPERTYSTR_FIELD_NUMBER;
    hash = (53 * hash) + getBasePropertyStr().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoSysItemGunProperty prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.model.ProtoSysItemGunProperty}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoSysItemGunProperty)
      com.pearl.fcw.proto.model.ProtoSysItemGunPropertyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemGunProperty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemGunProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoSysItemGunProperty.class, com.pearl.fcw.proto.model.ProtoSysItemGunProperty.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoSysItemGunProperty.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      color_ = 0;

      basePropertyStr_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemGunProperty_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoSysItemGunProperty getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoSysItemGunProperty.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoSysItemGunProperty build() {
      com.pearl.fcw.proto.model.ProtoSysItemGunProperty result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoSysItemGunProperty buildPartial() {
      com.pearl.fcw.proto.model.ProtoSysItemGunProperty result = new com.pearl.fcw.proto.model.ProtoSysItemGunProperty(this);
      result.color_ = color_;
      result.basePropertyStr_ = basePropertyStr_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoSysItemGunProperty) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoSysItemGunProperty)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoSysItemGunProperty other) {
      if (other == com.pearl.fcw.proto.model.ProtoSysItemGunProperty.getDefaultInstance()) return this;
      if (other.color_ != 0) {
        setColorValue(other.getColorValue());
      }
      if (!other.getBasePropertyStr().isEmpty()) {
        basePropertyStr_ = other.basePropertyStr_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoSysItemGunProperty parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoSysItemGunProperty) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int color_ = 0;
    /**
     * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
     */
    public int getColorValue() {
      return color_;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
     */
    public Builder setColorValue(int value) {
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
     */
    public com.pearl.fcw.proto.enums.EItemColor getColor() {
      com.pearl.fcw.proto.enums.EItemColor result = com.pearl.fcw.proto.enums.EItemColor.forNumber(color_);
      return result == null ? com.pearl.fcw.proto.enums.EItemColor.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
     */
    public Builder setColor(com.pearl.fcw.proto.enums.EItemColor value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      color_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemColor color = 1;</code>
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object basePropertyStr_ = "";
    /**
     * <pre>
     *似乎没有用
     * </pre>
     *
     * <code>optional string basePropertyStr = 2;</code>
     */
    public java.lang.String getBasePropertyStr() {
      java.lang.Object ref = basePropertyStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basePropertyStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *似乎没有用
     * </pre>
     *
     * <code>optional string basePropertyStr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBasePropertyStrBytes() {
      java.lang.Object ref = basePropertyStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basePropertyStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *似乎没有用
     * </pre>
     *
     * <code>optional string basePropertyStr = 2;</code>
     */
    public Builder setBasePropertyStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      basePropertyStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *似乎没有用
     * </pre>
     *
     * <code>optional string basePropertyStr = 2;</code>
     */
    public Builder clearBasePropertyStr() {
      
      basePropertyStr_ = getDefaultInstance().getBasePropertyStr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *似乎没有用
     * </pre>
     *
     * <code>optional string basePropertyStr = 2;</code>
     */
    public Builder setBasePropertyStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      basePropertyStr_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoSysItemGunProperty)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoSysItemGunProperty)
  private static final com.pearl.fcw.proto.model.ProtoSysItemGunProperty DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoSysItemGunProperty();
  }

  public static com.pearl.fcw.proto.model.ProtoSysItemGunProperty getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoSysItemGunProperty>
      PARSER = new com.google.protobuf.AbstractParser<ProtoSysItemGunProperty>() {
    public ProtoSysItemGunProperty parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoSysItemGunProperty(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoSysItemGunProperty> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoSysItemGunProperty> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoSysItemGunProperty getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

