// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

public interface ProtoPlayerItemPerformanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.model.ProtoPlayerItemPerformance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *破坏力
   * </pre>
   *
   * <code>optional float damage = 1;</code>
   */
  float getDamage();

  /**
   * <pre>
   *射速
   * </pre>
   *
   * <code>optional float speed = 2;</code>
   */
  float getSpeed();

  /**
   * <pre>
   *每个弹夹子弹数
   * </pre>
   *
   * <code>optional sint32 ammos = 3;</code>
   */
  int getAmmos();

  /**
   * <pre>
   *弹夹数量
   * </pre>
   *
   * <code>optional sint32 ammoCount = 4;</code>
   */
  int getAmmoCount();

  /**
   * <pre>
   *比系统道具威力上升
   * </pre>
   *
   * <code>optional float damageAdd = 5;</code>
   */
  float getDamageAdd();

  /**
   * <pre>
   *比系统道具射速上升
   * </pre>
   *
   * <code>optional float speedAdd = 6;</code>
   */
  float getSpeedAdd();
}
