// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

public interface ProtoFcRpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.model.ProtoFcRpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
