// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * Protobuf type {@code fcw.proto.model.ProtoPlayerItemCommon}
 */
public  final class ProtoPlayerItemCommon extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoPlayerItemCommon)
    ProtoPlayerItemCommonOrBuilder {
  // Use ProtoPlayerItemCommon.newBuilder() to construct.
  private ProtoPlayerItemCommon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoPlayerItemCommon() {
    isAsset_ = 0;
    isOpenQuality_ = 0;
    level_ = 0;
    materialNeed_ = 0;
    gpNeed_ = 0;
    type_ = 0;
    subtype_ = 0;
    wid_ = 0;
    durable_ = 0F;
    quantity_ = 0;
    minutesLeft_ = 0;
    seq_ = 0;
    isVip_ = 0;
    isNew_ = 0;
    star_ = 0;
    strength_ = 0;
    holeNum_ = 0;
    cResistanceFire_ = 0F;
    cResistanceBlast_ = 0F;
    cResistanceBullet_ = 0F;
    cResistanceKnife_ = 0F;
    cBloodAdd_ = 0F;
    cResistanceFireAdd_ = 0F;
    cResistanceBlastAdd_ = 0F;
    cResistanceBulletAdd_ = 0F;
    cResistanceKnifeAdd_ = 0F;
    cBloodAddAdd_ = 0F;
    rareLevel_ = 0;
    evaluateRmb_ = 0F;
    needTeamPlaceLevel_ = 0;
    pSuitable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoPlayerItemCommon(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isAsset_ = input.readSInt32();
            break;
          }
          case 80: {

            isOpenQuality_ = input.readSInt32();
            break;
          }
          case 160: {

            level_ = input.readSInt32();
            break;
          }
          case 240: {

            materialNeed_ = input.readSInt32();
            break;
          }
          case 248: {

            gpNeed_ = input.readSInt32();
            break;
          }
          case 320: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 328: {

            subtype_ = input.readSInt32();
            break;
          }
          case 400: {
            int rawValue = input.readEnum();

            wid_ = rawValue;
            break;
          }
          case 485: {

            durable_ = input.readFloat();
            break;
          }
          case 560: {

            quantity_ = input.readSInt32();
            break;
          }
          case 640: {

            minutesLeft_ = input.readSInt32();
            break;
          }
          case 720: {

            seq_ = input.readSInt32();
            break;
          }
          case 800: {

            isVip_ = input.readSInt32();
            break;
          }
          case 880: {

            isNew_ = input.readSInt32();
            break;
          }
          case 960: {

            star_ = input.readSInt32();
            break;
          }
          case 1040: {

            strength_ = input.readSInt32();
            break;
          }
          case 1120: {

            holeNum_ = input.readSInt32();
            break;
          }
          case 1205: {

            cResistanceFire_ = input.readFloat();
            break;
          }
          case 1285: {

            cResistanceBlast_ = input.readFloat();
            break;
          }
          case 1365: {

            cResistanceBullet_ = input.readFloat();
            break;
          }
          case 1445: {

            cResistanceKnife_ = input.readFloat();
            break;
          }
          case 1525: {

            cBloodAdd_ = input.readFloat();
            break;
          }
          case 1605: {

            cResistanceFireAdd_ = input.readFloat();
            break;
          }
          case 1685: {

            cResistanceBlastAdd_ = input.readFloat();
            break;
          }
          case 1765: {

            cResistanceBulletAdd_ = input.readFloat();
            break;
          }
          case 1845: {

            cResistanceKnifeAdd_ = input.readFloat();
            break;
          }
          case 1925: {

            cBloodAddAdd_ = input.readFloat();
            break;
          }
          case 2000: {

            rareLevel_ = input.readSInt32();
            break;
          }
          case 2013: {

            evaluateRmb_ = input.readFloat();
            break;
          }
          case 2080: {

            needTeamPlaceLevel_ = input.readSInt32();
            break;
          }
          case 2162: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x40000000) == 0x40000000)) {
              pSuitable_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x40000000;
            }
            pSuitable_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x40000000) == 0x40000000)) {
        pSuitable_ = pSuitable_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerItemCommon_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerItemCommon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoPlayerItemCommon.class, com.pearl.fcw.proto.model.ProtoPlayerItemCommon.Builder.class);
  }

  private int bitField0_;
  public static final int ISASSET_FIELD_NUMBER = 1;
  private int isAsset_;
  /**
   * <code>optional sint32 isAsset = 1;</code>
   */
  public int getIsAsset() {
    return isAsset_;
  }

  public static final int ISOPENQUALITY_FIELD_NUMBER = 10;
  private int isOpenQuality_;
  /**
   * <code>optional sint32 isOpenQuality = 10;</code>
   */
  public int getIsOpenQuality() {
    return isOpenQuality_;
  }

  public static final int LEVEL_FIELD_NUMBER = 20;
  private int level_;
  /**
   * <code>optional sint32 level = 20;</code>
   */
  public int getLevel() {
    return level_;
  }

  public static final int MATERIALNEED_FIELD_NUMBER = 30;
  private int materialNeed_;
  /**
   * <pre>
   *升级需要材料？
   * </pre>
   *
   * <code>optional sint32 materialNeed = 30;</code>
   */
  public int getMaterialNeed() {
    return materialNeed_;
  }

  public static final int GPNEED_FIELD_NUMBER = 31;
  private int gpNeed_;
  /**
   * <pre>
   *升级需要货币
   * </pre>
   *
   * <code>optional sint32 gpNeed = 31;</code>
   */
  public int getGpNeed() {
    return gpNeed_;
  }

  public static final int TYPE_FIELD_NUMBER = 40;
  private int type_;
  /**
   * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
   */
  public com.pearl.fcw.proto.enums.EItemType getType() {
    com.pearl.fcw.proto.enums.EItemType result = com.pearl.fcw.proto.enums.EItemType.forNumber(type_);
    return result == null ? com.pearl.fcw.proto.enums.EItemType.UNRECOGNIZED : result;
  }

  public static final int SUBTYPE_FIELD_NUMBER = 41;
  private int subtype_;
  /**
   * <code>optional sint32 subtype = 41;</code>
   */
  public int getSubtype() {
    return subtype_;
  }

  public static final int WID_FIELD_NUMBER = 50;
  private int wid_;
  /**
   * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
   */
  public int getWidValue() {
    return wid_;
  }
  /**
   * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
   */
  public com.pearl.fcw.proto.enums.EItemWId getWid() {
    com.pearl.fcw.proto.enums.EItemWId result = com.pearl.fcw.proto.enums.EItemWId.forNumber(wid_);
    return result == null ? com.pearl.fcw.proto.enums.EItemWId.UNRECOGNIZED : result;
  }

  public static final int DURABLE_FIELD_NUMBER = 60;
  private float durable_;
  /**
   * <code>optional float durable = 60;</code>
   */
  public float getDurable() {
    return durable_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 70;
  private int quantity_;
  /**
   * <code>optional sint32 quantity = 70;</code>
   */
  public int getQuantity() {
    return quantity_;
  }

  public static final int MINUTESLEFT_FIELD_NUMBER = 80;
  private int minutesLeft_;
  /**
   * <code>optional sint32 minutesLeft = 80;</code>
   */
  public int getMinutesLeft() {
    return minutesLeft_;
  }

  public static final int SEQ_FIELD_NUMBER = 90;
  private int seq_;
  /**
   * <code>optional sint32 seq = 90;</code>
   */
  public int getSeq() {
    return seq_;
  }

  public static final int ISVIP_FIELD_NUMBER = 100;
  private int isVip_;
  /**
   * <code>optional sint32 isVip = 100;</code>
   */
  public int getIsVip() {
    return isVip_;
  }

  public static final int ISNEW_FIELD_NUMBER = 110;
  private int isNew_;
  /**
   * <code>optional sint32 isNew = 110;</code>
   */
  public int getIsNew() {
    return isNew_;
  }

  public static final int STAR_FIELD_NUMBER = 120;
  private int star_;
  /**
   * <code>optional sint32 star = 120;</code>
   */
  public int getStar() {
    return star_;
  }

  public static final int STRENGTH_FIELD_NUMBER = 130;
  private int strength_;
  /**
   * <code>optional sint32 strength = 130;</code>
   */
  public int getStrength() {
    return strength_;
  }

  public static final int HOLENUM_FIELD_NUMBER = 140;
  private int holeNum_;
  /**
   * <pre>
   *已开孔未开槽+已开槽
   * </pre>
   *
   * <code>optional sint32 holeNum = 140;</code>
   */
  public int getHoleNum() {
    return holeNum_;
  }

  public static final int CRESISTANCEFIRE_FIELD_NUMBER = 150;
  private float cResistanceFire_;
  /**
   * <code>optional float cResistanceFire = 150;</code>
   */
  public float getCResistanceFire() {
    return cResistanceFire_;
  }

  public static final int CRESISTANCEBLAST_FIELD_NUMBER = 160;
  private float cResistanceBlast_;
  /**
   * <code>optional float cResistanceBlast = 160;</code>
   */
  public float getCResistanceBlast() {
    return cResistanceBlast_;
  }

  public static final int CRESISTANCEBULLET_FIELD_NUMBER = 170;
  private float cResistanceBullet_;
  /**
   * <code>optional float cResistanceBullet = 170;</code>
   */
  public float getCResistanceBullet() {
    return cResistanceBullet_;
  }

  public static final int CRESISTANCEKNIFE_FIELD_NUMBER = 180;
  private float cResistanceKnife_;
  /**
   * <code>optional float cResistanceKnife = 180;</code>
   */
  public float getCResistanceKnife() {
    return cResistanceKnife_;
  }

  public static final int CBLOODADD_FIELD_NUMBER = 190;
  private float cBloodAdd_;
  /**
   * <code>optional float cBloodAdd = 190;</code>
   */
  public float getCBloodAdd() {
    return cBloodAdd_;
  }

  public static final int CRESISTANCEFIREADD_FIELD_NUMBER = 200;
  private float cResistanceFireAdd_;
  /**
   * <code>optional float cResistanceFireAdd = 200;</code>
   */
  public float getCResistanceFireAdd() {
    return cResistanceFireAdd_;
  }

  public static final int CRESISTANCEBLASTADD_FIELD_NUMBER = 210;
  private float cResistanceBlastAdd_;
  /**
   * <code>optional float cResistanceBlastAdd = 210;</code>
   */
  public float getCResistanceBlastAdd() {
    return cResistanceBlastAdd_;
  }

  public static final int CRESISTANCEBULLETADD_FIELD_NUMBER = 220;
  private float cResistanceBulletAdd_;
  /**
   * <code>optional float cResistanceBulletAdd = 220;</code>
   */
  public float getCResistanceBulletAdd() {
    return cResistanceBulletAdd_;
  }

  public static final int CRESISTANCEKNIFEADD_FIELD_NUMBER = 230;
  private float cResistanceKnifeAdd_;
  /**
   * <code>optional float cResistanceKnifeAdd = 230;</code>
   */
  public float getCResistanceKnifeAdd() {
    return cResistanceKnifeAdd_;
  }

  public static final int CBLOODADDADD_FIELD_NUMBER = 240;
  private float cBloodAddAdd_;
  /**
   * <code>optional float cBloodAddAdd = 240;</code>
   */
  public float getCBloodAddAdd() {
    return cBloodAddAdd_;
  }

  public static final int RARELEVEL_FIELD_NUMBER = 250;
  private int rareLevel_;
  /**
   * <code>optional sint32 rareLevel = 250;</code>
   */
  public int getRareLevel() {
    return rareLevel_;
  }

  public static final int EVALUATERMB_FIELD_NUMBER = 251;
  private float evaluateRmb_;
  /**
   * <code>optional float evaluateRmb = 251;</code>
   */
  public float getEvaluateRmb() {
    return evaluateRmb_;
  }

  public static final int NEEDTEAMPLACELEVEL_FIELD_NUMBER = 260;
  private int needTeamPlaceLevel_;
  /**
   * <code>optional sint32 needTeamPlaceLevel = 260;</code>
   */
  public int getNeedTeamPlaceLevel() {
    return needTeamPlaceLevel_;
  }

  public static final int PSUITABLE_FIELD_NUMBER = 270;
  private com.google.protobuf.LazyStringList pSuitable_;
  /**
   * <pre>
   *无效字段
   * </pre>
   *
   * <code>repeated string pSuitable = 270;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPSuitableList() {
    return pSuitable_;
  }
  /**
   * <pre>
   *无效字段
   * </pre>
   *
   * <code>repeated string pSuitable = 270;</code>
   */
  public int getPSuitableCount() {
    return pSuitable_.size();
  }
  /**
   * <pre>
   *无效字段
   * </pre>
   *
   * <code>repeated string pSuitable = 270;</code>
   */
  public java.lang.String getPSuitable(int index) {
    return pSuitable_.get(index);
  }
  /**
   * <pre>
   *无效字段
   * </pre>
   *
   * <code>repeated string pSuitable = 270;</code>
   */
  public com.google.protobuf.ByteString
      getPSuitableBytes(int index) {
    return pSuitable_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isAsset_ != 0) {
      output.writeSInt32(1, isAsset_);
    }
    if (isOpenQuality_ != 0) {
      output.writeSInt32(10, isOpenQuality_);
    }
    if (level_ != 0) {
      output.writeSInt32(20, level_);
    }
    if (materialNeed_ != 0) {
      output.writeSInt32(30, materialNeed_);
    }
    if (gpNeed_ != 0) {
      output.writeSInt32(31, gpNeed_);
    }
    if (type_ != com.pearl.fcw.proto.enums.EItemType.ITEMTYPE_NONE.getNumber()) {
      output.writeEnum(40, type_);
    }
    if (subtype_ != 0) {
      output.writeSInt32(41, subtype_);
    }
    if (wid_ != com.pearl.fcw.proto.enums.EItemWId.WID_NONE.getNumber()) {
      output.writeEnum(50, wid_);
    }
    if (durable_ != 0F) {
      output.writeFloat(60, durable_);
    }
    if (quantity_ != 0) {
      output.writeSInt32(70, quantity_);
    }
    if (minutesLeft_ != 0) {
      output.writeSInt32(80, minutesLeft_);
    }
    if (seq_ != 0) {
      output.writeSInt32(90, seq_);
    }
    if (isVip_ != 0) {
      output.writeSInt32(100, isVip_);
    }
    if (isNew_ != 0) {
      output.writeSInt32(110, isNew_);
    }
    if (star_ != 0) {
      output.writeSInt32(120, star_);
    }
    if (strength_ != 0) {
      output.writeSInt32(130, strength_);
    }
    if (holeNum_ != 0) {
      output.writeSInt32(140, holeNum_);
    }
    if (cResistanceFire_ != 0F) {
      output.writeFloat(150, cResistanceFire_);
    }
    if (cResistanceBlast_ != 0F) {
      output.writeFloat(160, cResistanceBlast_);
    }
    if (cResistanceBullet_ != 0F) {
      output.writeFloat(170, cResistanceBullet_);
    }
    if (cResistanceKnife_ != 0F) {
      output.writeFloat(180, cResistanceKnife_);
    }
    if (cBloodAdd_ != 0F) {
      output.writeFloat(190, cBloodAdd_);
    }
    if (cResistanceFireAdd_ != 0F) {
      output.writeFloat(200, cResistanceFireAdd_);
    }
    if (cResistanceBlastAdd_ != 0F) {
      output.writeFloat(210, cResistanceBlastAdd_);
    }
    if (cResistanceBulletAdd_ != 0F) {
      output.writeFloat(220, cResistanceBulletAdd_);
    }
    if (cResistanceKnifeAdd_ != 0F) {
      output.writeFloat(230, cResistanceKnifeAdd_);
    }
    if (cBloodAddAdd_ != 0F) {
      output.writeFloat(240, cBloodAddAdd_);
    }
    if (rareLevel_ != 0) {
      output.writeSInt32(250, rareLevel_);
    }
    if (evaluateRmb_ != 0F) {
      output.writeFloat(251, evaluateRmb_);
    }
    if (needTeamPlaceLevel_ != 0) {
      output.writeSInt32(260, needTeamPlaceLevel_);
    }
    for (int i = 0; i < pSuitable_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 270, pSuitable_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isAsset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, isAsset_);
    }
    if (isOpenQuality_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(10, isOpenQuality_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(20, level_);
    }
    if (materialNeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(30, materialNeed_);
    }
    if (gpNeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(31, gpNeed_);
    }
    if (type_ != com.pearl.fcw.proto.enums.EItemType.ITEMTYPE_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(40, type_);
    }
    if (subtype_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(41, subtype_);
    }
    if (wid_ != com.pearl.fcw.proto.enums.EItemWId.WID_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(50, wid_);
    }
    if (durable_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(60, durable_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(70, quantity_);
    }
    if (minutesLeft_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(80, minutesLeft_);
    }
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(90, seq_);
    }
    if (isVip_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(100, isVip_);
    }
    if (isNew_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(110, isNew_);
    }
    if (star_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(120, star_);
    }
    if (strength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(130, strength_);
    }
    if (holeNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(140, holeNum_);
    }
    if (cResistanceFire_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(150, cResistanceFire_);
    }
    if (cResistanceBlast_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(160, cResistanceBlast_);
    }
    if (cResistanceBullet_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(170, cResistanceBullet_);
    }
    if (cResistanceKnife_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(180, cResistanceKnife_);
    }
    if (cBloodAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(190, cBloodAdd_);
    }
    if (cResistanceFireAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(200, cResistanceFireAdd_);
    }
    if (cResistanceBlastAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(210, cResistanceBlastAdd_);
    }
    if (cResistanceBulletAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(220, cResistanceBulletAdd_);
    }
    if (cResistanceKnifeAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(230, cResistanceKnifeAdd_);
    }
    if (cBloodAddAdd_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(240, cBloodAddAdd_);
    }
    if (rareLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(250, rareLevel_);
    }
    if (evaluateRmb_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(251, evaluateRmb_);
    }
    if (needTeamPlaceLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(260, needTeamPlaceLevel_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < pSuitable_.size(); i++) {
        dataSize += computeStringSizeNoTag(pSuitable_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getPSuitableList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoPlayerItemCommon)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoPlayerItemCommon other = (com.pearl.fcw.proto.model.ProtoPlayerItemCommon) obj;

    boolean result = true;
    result = result && (getIsAsset()
        == other.getIsAsset());
    result = result && (getIsOpenQuality()
        == other.getIsOpenQuality());
    result = result && (getLevel()
        == other.getLevel());
    result = result && (getMaterialNeed()
        == other.getMaterialNeed());
    result = result && (getGpNeed()
        == other.getGpNeed());
    result = result && type_ == other.type_;
    result = result && (getSubtype()
        == other.getSubtype());
    result = result && wid_ == other.wid_;
    result = result && (
        java.lang.Float.floatToIntBits(getDurable())
        == java.lang.Float.floatToIntBits(
            other.getDurable()));
    result = result && (getQuantity()
        == other.getQuantity());
    result = result && (getMinutesLeft()
        == other.getMinutesLeft());
    result = result && (getSeq()
        == other.getSeq());
    result = result && (getIsVip()
        == other.getIsVip());
    result = result && (getIsNew()
        == other.getIsNew());
    result = result && (getStar()
        == other.getStar());
    result = result && (getStrength()
        == other.getStrength());
    result = result && (getHoleNum()
        == other.getHoleNum());
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceFire())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceFire()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceBlast())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceBlast()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceBullet())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceBullet()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceKnife())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceKnife()));
    result = result && (
        java.lang.Float.floatToIntBits(getCBloodAdd())
        == java.lang.Float.floatToIntBits(
            other.getCBloodAdd()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceFireAdd())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceFireAdd()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceBlastAdd())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceBlastAdd()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceBulletAdd())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceBulletAdd()));
    result = result && (
        java.lang.Float.floatToIntBits(getCResistanceKnifeAdd())
        == java.lang.Float.floatToIntBits(
            other.getCResistanceKnifeAdd()));
    result = result && (
        java.lang.Float.floatToIntBits(getCBloodAddAdd())
        == java.lang.Float.floatToIntBits(
            other.getCBloodAddAdd()));
    result = result && (getRareLevel()
        == other.getRareLevel());
    result = result && (
        java.lang.Float.floatToIntBits(getEvaluateRmb())
        == java.lang.Float.floatToIntBits(
            other.getEvaluateRmb()));
    result = result && (getNeedTeamPlaceLevel()
        == other.getNeedTeamPlaceLevel());
    result = result && getPSuitableList()
        .equals(other.getPSuitableList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ISASSET_FIELD_NUMBER;
    hash = (53 * hash) + getIsAsset();
    hash = (37 * hash) + ISOPENQUALITY_FIELD_NUMBER;
    hash = (53 * hash) + getIsOpenQuality();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + MATERIALNEED_FIELD_NUMBER;
    hash = (53 * hash) + getMaterialNeed();
    hash = (37 * hash) + GPNEED_FIELD_NUMBER;
    hash = (53 * hash) + getGpNeed();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSubtype();
    hash = (37 * hash) + WID_FIELD_NUMBER;
    hash = (53 * hash) + wid_;
    hash = (37 * hash) + DURABLE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDurable());
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + MINUTESLEFT_FIELD_NUMBER;
    hash = (53 * hash) + getMinutesLeft();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + ISVIP_FIELD_NUMBER;
    hash = (53 * hash) + getIsVip();
    hash = (37 * hash) + ISNEW_FIELD_NUMBER;
    hash = (53 * hash) + getIsNew();
    hash = (37 * hash) + STAR_FIELD_NUMBER;
    hash = (53 * hash) + getStar();
    hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getStrength();
    hash = (37 * hash) + HOLENUM_FIELD_NUMBER;
    hash = (53 * hash) + getHoleNum();
    hash = (37 * hash) + CRESISTANCEFIRE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceFire());
    hash = (37 * hash) + CRESISTANCEBLAST_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceBlast());
    hash = (37 * hash) + CRESISTANCEBULLET_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceBullet());
    hash = (37 * hash) + CRESISTANCEKNIFE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceKnife());
    hash = (37 * hash) + CBLOODADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCBloodAdd());
    hash = (37 * hash) + CRESISTANCEFIREADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceFireAdd());
    hash = (37 * hash) + CRESISTANCEBLASTADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceBlastAdd());
    hash = (37 * hash) + CRESISTANCEBULLETADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceBulletAdd());
    hash = (37 * hash) + CRESISTANCEKNIFEADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCResistanceKnifeAdd());
    hash = (37 * hash) + CBLOODADDADD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCBloodAddAdd());
    hash = (37 * hash) + RARELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRareLevel();
    hash = (37 * hash) + EVALUATERMB_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEvaluateRmb());
    hash = (37 * hash) + NEEDTEAMPLACELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getNeedTeamPlaceLevel();
    if (getPSuitableCount() > 0) {
      hash = (37 * hash) + PSUITABLE_FIELD_NUMBER;
      hash = (53 * hash) + getPSuitableList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoPlayerItemCommon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.model.ProtoPlayerItemCommon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoPlayerItemCommon)
      com.pearl.fcw.proto.model.ProtoPlayerItemCommonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerItemCommon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerItemCommon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoPlayerItemCommon.class, com.pearl.fcw.proto.model.ProtoPlayerItemCommon.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoPlayerItemCommon.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isAsset_ = 0;

      isOpenQuality_ = 0;

      level_ = 0;

      materialNeed_ = 0;

      gpNeed_ = 0;

      type_ = 0;

      subtype_ = 0;

      wid_ = 0;

      durable_ = 0F;

      quantity_ = 0;

      minutesLeft_ = 0;

      seq_ = 0;

      isVip_ = 0;

      isNew_ = 0;

      star_ = 0;

      strength_ = 0;

      holeNum_ = 0;

      cResistanceFire_ = 0F;

      cResistanceBlast_ = 0F;

      cResistanceBullet_ = 0F;

      cResistanceKnife_ = 0F;

      cBloodAdd_ = 0F;

      cResistanceFireAdd_ = 0F;

      cResistanceBlastAdd_ = 0F;

      cResistanceBulletAdd_ = 0F;

      cResistanceKnifeAdd_ = 0F;

      cBloodAddAdd_ = 0F;

      rareLevel_ = 0;

      evaluateRmb_ = 0F;

      needTeamPlaceLevel_ = 0;

      pSuitable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x40000000);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerItemCommon_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerItemCommon getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoPlayerItemCommon.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoPlayerItemCommon build() {
      com.pearl.fcw.proto.model.ProtoPlayerItemCommon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerItemCommon buildPartial() {
      com.pearl.fcw.proto.model.ProtoPlayerItemCommon result = new com.pearl.fcw.proto.model.ProtoPlayerItemCommon(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.isAsset_ = isAsset_;
      result.isOpenQuality_ = isOpenQuality_;
      result.level_ = level_;
      result.materialNeed_ = materialNeed_;
      result.gpNeed_ = gpNeed_;
      result.type_ = type_;
      result.subtype_ = subtype_;
      result.wid_ = wid_;
      result.durable_ = durable_;
      result.quantity_ = quantity_;
      result.minutesLeft_ = minutesLeft_;
      result.seq_ = seq_;
      result.isVip_ = isVip_;
      result.isNew_ = isNew_;
      result.star_ = star_;
      result.strength_ = strength_;
      result.holeNum_ = holeNum_;
      result.cResistanceFire_ = cResistanceFire_;
      result.cResistanceBlast_ = cResistanceBlast_;
      result.cResistanceBullet_ = cResistanceBullet_;
      result.cResistanceKnife_ = cResistanceKnife_;
      result.cBloodAdd_ = cBloodAdd_;
      result.cResistanceFireAdd_ = cResistanceFireAdd_;
      result.cResistanceBlastAdd_ = cResistanceBlastAdd_;
      result.cResistanceBulletAdd_ = cResistanceBulletAdd_;
      result.cResistanceKnifeAdd_ = cResistanceKnifeAdd_;
      result.cBloodAddAdd_ = cBloodAddAdd_;
      result.rareLevel_ = rareLevel_;
      result.evaluateRmb_ = evaluateRmb_;
      result.needTeamPlaceLevel_ = needTeamPlaceLevel_;
      if (((bitField0_ & 0x40000000) == 0x40000000)) {
        pSuitable_ = pSuitable_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x40000000);
      }
      result.pSuitable_ = pSuitable_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoPlayerItemCommon) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoPlayerItemCommon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoPlayerItemCommon other) {
      if (other == com.pearl.fcw.proto.model.ProtoPlayerItemCommon.getDefaultInstance()) return this;
      if (other.getIsAsset() != 0) {
        setIsAsset(other.getIsAsset());
      }
      if (other.getIsOpenQuality() != 0) {
        setIsOpenQuality(other.getIsOpenQuality());
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getMaterialNeed() != 0) {
        setMaterialNeed(other.getMaterialNeed());
      }
      if (other.getGpNeed() != 0) {
        setGpNeed(other.getGpNeed());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getSubtype() != 0) {
        setSubtype(other.getSubtype());
      }
      if (other.wid_ != 0) {
        setWidValue(other.getWidValue());
      }
      if (other.getDurable() != 0F) {
        setDurable(other.getDurable());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (other.getMinutesLeft() != 0) {
        setMinutesLeft(other.getMinutesLeft());
      }
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (other.getIsVip() != 0) {
        setIsVip(other.getIsVip());
      }
      if (other.getIsNew() != 0) {
        setIsNew(other.getIsNew());
      }
      if (other.getStar() != 0) {
        setStar(other.getStar());
      }
      if (other.getStrength() != 0) {
        setStrength(other.getStrength());
      }
      if (other.getHoleNum() != 0) {
        setHoleNum(other.getHoleNum());
      }
      if (other.getCResistanceFire() != 0F) {
        setCResistanceFire(other.getCResistanceFire());
      }
      if (other.getCResistanceBlast() != 0F) {
        setCResistanceBlast(other.getCResistanceBlast());
      }
      if (other.getCResistanceBullet() != 0F) {
        setCResistanceBullet(other.getCResistanceBullet());
      }
      if (other.getCResistanceKnife() != 0F) {
        setCResistanceKnife(other.getCResistanceKnife());
      }
      if (other.getCBloodAdd() != 0F) {
        setCBloodAdd(other.getCBloodAdd());
      }
      if (other.getCResistanceFireAdd() != 0F) {
        setCResistanceFireAdd(other.getCResistanceFireAdd());
      }
      if (other.getCResistanceBlastAdd() != 0F) {
        setCResistanceBlastAdd(other.getCResistanceBlastAdd());
      }
      if (other.getCResistanceBulletAdd() != 0F) {
        setCResistanceBulletAdd(other.getCResistanceBulletAdd());
      }
      if (other.getCResistanceKnifeAdd() != 0F) {
        setCResistanceKnifeAdd(other.getCResistanceKnifeAdd());
      }
      if (other.getCBloodAddAdd() != 0F) {
        setCBloodAddAdd(other.getCBloodAddAdd());
      }
      if (other.getRareLevel() != 0) {
        setRareLevel(other.getRareLevel());
      }
      if (other.getEvaluateRmb() != 0F) {
        setEvaluateRmb(other.getEvaluateRmb());
      }
      if (other.getNeedTeamPlaceLevel() != 0) {
        setNeedTeamPlaceLevel(other.getNeedTeamPlaceLevel());
      }
      if (!other.pSuitable_.isEmpty()) {
        if (pSuitable_.isEmpty()) {
          pSuitable_ = other.pSuitable_;
          bitField0_ = (bitField0_ & ~0x40000000);
        } else {
          ensurePSuitableIsMutable();
          pSuitable_.addAll(other.pSuitable_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoPlayerItemCommon parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoPlayerItemCommon) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int isAsset_ ;
    /**
     * <code>optional sint32 isAsset = 1;</code>
     */
    public int getIsAsset() {
      return isAsset_;
    }
    /**
     * <code>optional sint32 isAsset = 1;</code>
     */
    public Builder setIsAsset(int value) {
      
      isAsset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 isAsset = 1;</code>
     */
    public Builder clearIsAsset() {
      
      isAsset_ = 0;
      onChanged();
      return this;
    }

    private int isOpenQuality_ ;
    /**
     * <code>optional sint32 isOpenQuality = 10;</code>
     */
    public int getIsOpenQuality() {
      return isOpenQuality_;
    }
    /**
     * <code>optional sint32 isOpenQuality = 10;</code>
     */
    public Builder setIsOpenQuality(int value) {
      
      isOpenQuality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 isOpenQuality = 10;</code>
     */
    public Builder clearIsOpenQuality() {
      
      isOpenQuality_ = 0;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <code>optional sint32 level = 20;</code>
     */
    public int getLevel() {
      return level_;
    }
    /**
     * <code>optional sint32 level = 20;</code>
     */
    public Builder setLevel(int value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 level = 20;</code>
     */
    public Builder clearLevel() {
      
      level_ = 0;
      onChanged();
      return this;
    }

    private int materialNeed_ ;
    /**
     * <pre>
     *升级需要材料？
     * </pre>
     *
     * <code>optional sint32 materialNeed = 30;</code>
     */
    public int getMaterialNeed() {
      return materialNeed_;
    }
    /**
     * <pre>
     *升级需要材料？
     * </pre>
     *
     * <code>optional sint32 materialNeed = 30;</code>
     */
    public Builder setMaterialNeed(int value) {
      
      materialNeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *升级需要材料？
     * </pre>
     *
     * <code>optional sint32 materialNeed = 30;</code>
     */
    public Builder clearMaterialNeed() {
      
      materialNeed_ = 0;
      onChanged();
      return this;
    }

    private int gpNeed_ ;
    /**
     * <pre>
     *升级需要货币
     * </pre>
     *
     * <code>optional sint32 gpNeed = 31;</code>
     */
    public int getGpNeed() {
      return gpNeed_;
    }
    /**
     * <pre>
     *升级需要货币
     * </pre>
     *
     * <code>optional sint32 gpNeed = 31;</code>
     */
    public Builder setGpNeed(int value) {
      
      gpNeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *升级需要货币
     * </pre>
     *
     * <code>optional sint32 gpNeed = 31;</code>
     */
    public Builder clearGpNeed() {
      
      gpNeed_ = 0;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
     */
    public com.pearl.fcw.proto.enums.EItemType getType() {
      com.pearl.fcw.proto.enums.EItemType result = com.pearl.fcw.proto.enums.EItemType.forNumber(type_);
      return result == null ? com.pearl.fcw.proto.enums.EItemType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
     */
    public Builder setType(com.pearl.fcw.proto.enums.EItemType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemType type = 40;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int subtype_ ;
    /**
     * <code>optional sint32 subtype = 41;</code>
     */
    public int getSubtype() {
      return subtype_;
    }
    /**
     * <code>optional sint32 subtype = 41;</code>
     */
    public Builder setSubtype(int value) {
      
      subtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 subtype = 41;</code>
     */
    public Builder clearSubtype() {
      
      subtype_ = 0;
      onChanged();
      return this;
    }

    private int wid_ = 0;
    /**
     * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
     */
    public int getWidValue() {
      return wid_;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
     */
    public Builder setWidValue(int value) {
      wid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
     */
    public com.pearl.fcw.proto.enums.EItemWId getWid() {
      com.pearl.fcw.proto.enums.EItemWId result = com.pearl.fcw.proto.enums.EItemWId.forNumber(wid_);
      return result == null ? com.pearl.fcw.proto.enums.EItemWId.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
     */
    public Builder setWid(com.pearl.fcw.proto.enums.EItemWId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      wid_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EItemWId wid = 50;</code>
     */
    public Builder clearWid() {
      
      wid_ = 0;
      onChanged();
      return this;
    }

    private float durable_ ;
    /**
     * <code>optional float durable = 60;</code>
     */
    public float getDurable() {
      return durable_;
    }
    /**
     * <code>optional float durable = 60;</code>
     */
    public Builder setDurable(float value) {
      
      durable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float durable = 60;</code>
     */
    public Builder clearDurable() {
      
      durable_ = 0F;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>optional sint32 quantity = 70;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>optional sint32 quantity = 70;</code>
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 quantity = 70;</code>
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }

    private int minutesLeft_ ;
    /**
     * <code>optional sint32 minutesLeft = 80;</code>
     */
    public int getMinutesLeft() {
      return minutesLeft_;
    }
    /**
     * <code>optional sint32 minutesLeft = 80;</code>
     */
    public Builder setMinutesLeft(int value) {
      
      minutesLeft_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 minutesLeft = 80;</code>
     */
    public Builder clearMinutesLeft() {
      
      minutesLeft_ = 0;
      onChanged();
      return this;
    }

    private int seq_ ;
    /**
     * <code>optional sint32 seq = 90;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>optional sint32 seq = 90;</code>
     */
    public Builder setSeq(int value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 seq = 90;</code>
     */
    public Builder clearSeq() {
      
      seq_ = 0;
      onChanged();
      return this;
    }

    private int isVip_ ;
    /**
     * <code>optional sint32 isVip = 100;</code>
     */
    public int getIsVip() {
      return isVip_;
    }
    /**
     * <code>optional sint32 isVip = 100;</code>
     */
    public Builder setIsVip(int value) {
      
      isVip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 isVip = 100;</code>
     */
    public Builder clearIsVip() {
      
      isVip_ = 0;
      onChanged();
      return this;
    }

    private int isNew_ ;
    /**
     * <code>optional sint32 isNew = 110;</code>
     */
    public int getIsNew() {
      return isNew_;
    }
    /**
     * <code>optional sint32 isNew = 110;</code>
     */
    public Builder setIsNew(int value) {
      
      isNew_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 isNew = 110;</code>
     */
    public Builder clearIsNew() {
      
      isNew_ = 0;
      onChanged();
      return this;
    }

    private int star_ ;
    /**
     * <code>optional sint32 star = 120;</code>
     */
    public int getStar() {
      return star_;
    }
    /**
     * <code>optional sint32 star = 120;</code>
     */
    public Builder setStar(int value) {
      
      star_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 star = 120;</code>
     */
    public Builder clearStar() {
      
      star_ = 0;
      onChanged();
      return this;
    }

    private int strength_ ;
    /**
     * <code>optional sint32 strength = 130;</code>
     */
    public int getStrength() {
      return strength_;
    }
    /**
     * <code>optional sint32 strength = 130;</code>
     */
    public Builder setStrength(int value) {
      
      strength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 strength = 130;</code>
     */
    public Builder clearStrength() {
      
      strength_ = 0;
      onChanged();
      return this;
    }

    private int holeNum_ ;
    /**
     * <pre>
     *已开孔未开槽+已开槽
     * </pre>
     *
     * <code>optional sint32 holeNum = 140;</code>
     */
    public int getHoleNum() {
      return holeNum_;
    }
    /**
     * <pre>
     *已开孔未开槽+已开槽
     * </pre>
     *
     * <code>optional sint32 holeNum = 140;</code>
     */
    public Builder setHoleNum(int value) {
      
      holeNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *已开孔未开槽+已开槽
     * </pre>
     *
     * <code>optional sint32 holeNum = 140;</code>
     */
    public Builder clearHoleNum() {
      
      holeNum_ = 0;
      onChanged();
      return this;
    }

    private float cResistanceFire_ ;
    /**
     * <code>optional float cResistanceFire = 150;</code>
     */
    public float getCResistanceFire() {
      return cResistanceFire_;
    }
    /**
     * <code>optional float cResistanceFire = 150;</code>
     */
    public Builder setCResistanceFire(float value) {
      
      cResistanceFire_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceFire = 150;</code>
     */
    public Builder clearCResistanceFire() {
      
      cResistanceFire_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceBlast_ ;
    /**
     * <code>optional float cResistanceBlast = 160;</code>
     */
    public float getCResistanceBlast() {
      return cResistanceBlast_;
    }
    /**
     * <code>optional float cResistanceBlast = 160;</code>
     */
    public Builder setCResistanceBlast(float value) {
      
      cResistanceBlast_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceBlast = 160;</code>
     */
    public Builder clearCResistanceBlast() {
      
      cResistanceBlast_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceBullet_ ;
    /**
     * <code>optional float cResistanceBullet = 170;</code>
     */
    public float getCResistanceBullet() {
      return cResistanceBullet_;
    }
    /**
     * <code>optional float cResistanceBullet = 170;</code>
     */
    public Builder setCResistanceBullet(float value) {
      
      cResistanceBullet_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceBullet = 170;</code>
     */
    public Builder clearCResistanceBullet() {
      
      cResistanceBullet_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceKnife_ ;
    /**
     * <code>optional float cResistanceKnife = 180;</code>
     */
    public float getCResistanceKnife() {
      return cResistanceKnife_;
    }
    /**
     * <code>optional float cResistanceKnife = 180;</code>
     */
    public Builder setCResistanceKnife(float value) {
      
      cResistanceKnife_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceKnife = 180;</code>
     */
    public Builder clearCResistanceKnife() {
      
      cResistanceKnife_ = 0F;
      onChanged();
      return this;
    }

    private float cBloodAdd_ ;
    /**
     * <code>optional float cBloodAdd = 190;</code>
     */
    public float getCBloodAdd() {
      return cBloodAdd_;
    }
    /**
     * <code>optional float cBloodAdd = 190;</code>
     */
    public Builder setCBloodAdd(float value) {
      
      cBloodAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cBloodAdd = 190;</code>
     */
    public Builder clearCBloodAdd() {
      
      cBloodAdd_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceFireAdd_ ;
    /**
     * <code>optional float cResistanceFireAdd = 200;</code>
     */
    public float getCResistanceFireAdd() {
      return cResistanceFireAdd_;
    }
    /**
     * <code>optional float cResistanceFireAdd = 200;</code>
     */
    public Builder setCResistanceFireAdd(float value) {
      
      cResistanceFireAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceFireAdd = 200;</code>
     */
    public Builder clearCResistanceFireAdd() {
      
      cResistanceFireAdd_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceBlastAdd_ ;
    /**
     * <code>optional float cResistanceBlastAdd = 210;</code>
     */
    public float getCResistanceBlastAdd() {
      return cResistanceBlastAdd_;
    }
    /**
     * <code>optional float cResistanceBlastAdd = 210;</code>
     */
    public Builder setCResistanceBlastAdd(float value) {
      
      cResistanceBlastAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceBlastAdd = 210;</code>
     */
    public Builder clearCResistanceBlastAdd() {
      
      cResistanceBlastAdd_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceBulletAdd_ ;
    /**
     * <code>optional float cResistanceBulletAdd = 220;</code>
     */
    public float getCResistanceBulletAdd() {
      return cResistanceBulletAdd_;
    }
    /**
     * <code>optional float cResistanceBulletAdd = 220;</code>
     */
    public Builder setCResistanceBulletAdd(float value) {
      
      cResistanceBulletAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceBulletAdd = 220;</code>
     */
    public Builder clearCResistanceBulletAdd() {
      
      cResistanceBulletAdd_ = 0F;
      onChanged();
      return this;
    }

    private float cResistanceKnifeAdd_ ;
    /**
     * <code>optional float cResistanceKnifeAdd = 230;</code>
     */
    public float getCResistanceKnifeAdd() {
      return cResistanceKnifeAdd_;
    }
    /**
     * <code>optional float cResistanceKnifeAdd = 230;</code>
     */
    public Builder setCResistanceKnifeAdd(float value) {
      
      cResistanceKnifeAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cResistanceKnifeAdd = 230;</code>
     */
    public Builder clearCResistanceKnifeAdd() {
      
      cResistanceKnifeAdd_ = 0F;
      onChanged();
      return this;
    }

    private float cBloodAddAdd_ ;
    /**
     * <code>optional float cBloodAddAdd = 240;</code>
     */
    public float getCBloodAddAdd() {
      return cBloodAddAdd_;
    }
    /**
     * <code>optional float cBloodAddAdd = 240;</code>
     */
    public Builder setCBloodAddAdd(float value) {
      
      cBloodAddAdd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float cBloodAddAdd = 240;</code>
     */
    public Builder clearCBloodAddAdd() {
      
      cBloodAddAdd_ = 0F;
      onChanged();
      return this;
    }

    private int rareLevel_ ;
    /**
     * <code>optional sint32 rareLevel = 250;</code>
     */
    public int getRareLevel() {
      return rareLevel_;
    }
    /**
     * <code>optional sint32 rareLevel = 250;</code>
     */
    public Builder setRareLevel(int value) {
      
      rareLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 rareLevel = 250;</code>
     */
    public Builder clearRareLevel() {
      
      rareLevel_ = 0;
      onChanged();
      return this;
    }

    private float evaluateRmb_ ;
    /**
     * <code>optional float evaluateRmb = 251;</code>
     */
    public float getEvaluateRmb() {
      return evaluateRmb_;
    }
    /**
     * <code>optional float evaluateRmb = 251;</code>
     */
    public Builder setEvaluateRmb(float value) {
      
      evaluateRmb_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float evaluateRmb = 251;</code>
     */
    public Builder clearEvaluateRmb() {
      
      evaluateRmb_ = 0F;
      onChanged();
      return this;
    }

    private int needTeamPlaceLevel_ ;
    /**
     * <code>optional sint32 needTeamPlaceLevel = 260;</code>
     */
    public int getNeedTeamPlaceLevel() {
      return needTeamPlaceLevel_;
    }
    /**
     * <code>optional sint32 needTeamPlaceLevel = 260;</code>
     */
    public Builder setNeedTeamPlaceLevel(int value) {
      
      needTeamPlaceLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 needTeamPlaceLevel = 260;</code>
     */
    public Builder clearNeedTeamPlaceLevel() {
      
      needTeamPlaceLevel_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList pSuitable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePSuitableIsMutable() {
      if (!((bitField0_ & 0x40000000) == 0x40000000)) {
        pSuitable_ = new com.google.protobuf.LazyStringArrayList(pSuitable_);
        bitField0_ |= 0x40000000;
       }
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPSuitableList() {
      return pSuitable_.getUnmodifiableView();
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public int getPSuitableCount() {
      return pSuitable_.size();
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public java.lang.String getPSuitable(int index) {
      return pSuitable_.get(index);
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public com.google.protobuf.ByteString
        getPSuitableBytes(int index) {
      return pSuitable_.getByteString(index);
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public Builder setPSuitable(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePSuitableIsMutable();
      pSuitable_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public Builder addPSuitable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePSuitableIsMutable();
      pSuitable_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public Builder addAllPSuitable(
        java.lang.Iterable<java.lang.String> values) {
      ensurePSuitableIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, pSuitable_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public Builder clearPSuitable() {
      pSuitable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x40000000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *无效字段
     * </pre>
     *
     * <code>repeated string pSuitable = 270;</code>
     */
    public Builder addPSuitableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePSuitableIsMutable();
      pSuitable_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoPlayerItemCommon)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoPlayerItemCommon)
  private static final com.pearl.fcw.proto.model.ProtoPlayerItemCommon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoPlayerItemCommon();
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerItemCommon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPlayerItemCommon>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPlayerItemCommon>() {
    public ProtoPlayerItemCommon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPlayerItemCommon(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoPlayerItemCommon> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPlayerItemCommon> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoPlayerItemCommon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

