// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * Protobuf type {@code fcw.proto.model.ProtoSysActivity}
 */
public  final class ProtoSysActivity extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoSysActivity)
    ProtoSysActivityOrBuilder {
  // Use ProtoSysActivity.newBuilder() to construct.
  private ProtoSysActivity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoSysActivity() {
    id_ = 0;
    path_ = "";
    action_ = 0;
    needAward_ = 0;
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoSysActivity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readSInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 160: {
            int rawValue = input.readEnum();

            action_ = rawValue;
            break;
          }
          case 240: {

            needAward_ = input.readSInt32();
            break;
          }
          case 250: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              items_ = new java.util.ArrayList<com.pearl.fcw.proto.model.ProtoSysItem>();
              mutable_bitField0_ |= 0x00000010;
            }
            items_.add(input.readMessage(com.pearl.fcw.proto.model.ProtoSysItem.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysActivity_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysActivity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoSysActivity.class, com.pearl.fcw.proto.model.ProtoSysActivity.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional sint32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int PATH_FIELD_NUMBER = 10;
  private volatile java.lang.Object path_;
  /**
   * <code>optional string path = 10;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>optional string path = 10;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 20;
  private int action_;
  /**
   * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
   */
  public int getActionValue() {
    return action_;
  }
  /**
   * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
   */
  public com.pearl.fcw.proto.enums.EActivityActionType getAction() {
    com.pearl.fcw.proto.enums.EActivityActionType result = com.pearl.fcw.proto.enums.EActivityActionType.forNumber(action_);
    return result == null ? com.pearl.fcw.proto.enums.EActivityActionType.UNRECOGNIZED : result;
  }

  public static final int NEEDAWARD_FIELD_NUMBER = 30;
  private int needAward_;
  /**
   * <code>optional sint32 needAward = 30;</code>
   */
  public int getNeedAward() {
    return needAward_;
  }

  public static final int ITEMS_FIELD_NUMBER = 31;
  private java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> items_;
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  public java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  public java.util.List<? extends com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  public com.pearl.fcw.proto.model.ProtoSysItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  public com.pearl.fcw.proto.model.ProtoSysItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeSInt32(1, id_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, path_);
    }
    if (action_ != com.pearl.fcw.proto.enums.EActivityActionType.NONE_ACTIVITY.getNumber()) {
      output.writeEnum(20, action_);
    }
    if (needAward_ != 0) {
      output.writeSInt32(30, needAward_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(31, items_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, id_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, path_);
    }
    if (action_ != com.pearl.fcw.proto.enums.EActivityActionType.NONE_ACTIVITY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(20, action_);
    }
    if (needAward_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(30, needAward_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(31, items_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoSysActivity)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoSysActivity other = (com.pearl.fcw.proto.model.ProtoSysActivity) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getPath()
        .equals(other.getPath());
    result = result && action_ == other.action_;
    result = result && (getNeedAward()
        == other.getNeedAward());
    result = result && getItemsList()
        .equals(other.getItemsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    hash = (37 * hash) + NEEDAWARD_FIELD_NUMBER;
    hash = (53 * hash) + getNeedAward();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysActivity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoSysActivity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.model.ProtoSysActivity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoSysActivity)
      com.pearl.fcw.proto.model.ProtoSysActivityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysActivity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysActivity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoSysActivity.class, com.pearl.fcw.proto.model.ProtoSysActivity.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoSysActivity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      path_ = "";

      action_ = 0;

      needAward_ = 0;

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysActivity_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoSysActivity getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoSysActivity.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoSysActivity build() {
      com.pearl.fcw.proto.model.ProtoSysActivity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoSysActivity buildPartial() {
      com.pearl.fcw.proto.model.ProtoSysActivity result = new com.pearl.fcw.proto.model.ProtoSysActivity(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.path_ = path_;
      result.action_ = action_;
      result.needAward_ = needAward_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoSysActivity) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoSysActivity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoSysActivity other) {
      if (other == com.pearl.fcw.proto.model.ProtoSysActivity.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      if (other.getNeedAward() != 0) {
        setNeedAward(other.getNeedAward());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000010);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoSysActivity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoSysActivity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <code>optional string path = 10;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string path = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string path = 10;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 10;</code>
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string path = 10;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private int action_ = 0;
    /**
     * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
     */
    public Builder setActionValue(int value) {
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
     */
    public com.pearl.fcw.proto.enums.EActivityActionType getAction() {
      com.pearl.fcw.proto.enums.EActivityActionType result = com.pearl.fcw.proto.enums.EActivityActionType.forNumber(action_);
      return result == null ? com.pearl.fcw.proto.enums.EActivityActionType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
     */
    public Builder setAction(com.pearl.fcw.proto.enums.EActivityActionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
     */
    public Builder clearAction() {
      
      action_ = 0;
      onChanged();
      return this;
    }

    private int needAward_ ;
    /**
     * <code>optional sint32 needAward = 30;</code>
     */
    public int getNeedAward() {
      return needAward_;
    }
    /**
     * <code>optional sint32 needAward = 30;</code>
     */
    public Builder setNeedAward(int value) {
      
      needAward_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 needAward = 30;</code>
     */
    public Builder clearNeedAward() {
      
      needAward_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        items_ = new java.util.ArrayList<com.pearl.fcw.proto.model.ProtoSysItem>(items_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.pearl.fcw.proto.model.ProtoSysItem, com.pearl.fcw.proto.model.ProtoSysItem.Builder, com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public com.pearl.fcw.proto.model.ProtoSysItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder setItems(
        int index, com.pearl.fcw.proto.model.ProtoSysItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder setItems(
        int index, com.pearl.fcw.proto.model.ProtoSysItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder addItems(com.pearl.fcw.proto.model.ProtoSysItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder addItems(
        int index, com.pearl.fcw.proto.model.ProtoSysItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder addItems(
        com.pearl.fcw.proto.model.ProtoSysItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder addItems(
        int index, com.pearl.fcw.proto.model.ProtoSysItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.pearl.fcw.proto.model.ProtoSysItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public com.pearl.fcw.proto.model.ProtoSysItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public com.pearl.fcw.proto.model.ProtoSysItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public java.util.List<? extends com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public com.pearl.fcw.proto.model.ProtoSysItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.pearl.fcw.proto.model.ProtoSysItem.getDefaultInstance());
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public com.pearl.fcw.proto.model.ProtoSysItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.pearl.fcw.proto.model.ProtoSysItem.getDefaultInstance());
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
     */
    public java.util.List<com.pearl.fcw.proto.model.ProtoSysItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.pearl.fcw.proto.model.ProtoSysItem, com.pearl.fcw.proto.model.ProtoSysItem.Builder, com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.pearl.fcw.proto.model.ProtoSysItem, com.pearl.fcw.proto.model.ProtoSysItem.Builder, com.pearl.fcw.proto.model.ProtoSysItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoSysActivity)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoSysActivity)
  private static final com.pearl.fcw.proto.model.ProtoSysActivity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoSysActivity();
  }

  public static com.pearl.fcw.proto.model.ProtoSysActivity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoSysActivity>
      PARSER = new com.google.protobuf.AbstractParser<ProtoSysActivity>() {
    public ProtoSysActivity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoSysActivity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoSysActivity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoSysActivity> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoSysActivity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

