// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

public interface ProtoSysActivityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.model.ProtoSysActivity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional sint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string path = 10;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 10;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
   */
  int getActionValue();
  /**
   * <code>optional .fcw.proto.enums.type.EActivityActionType action = 20;</code>
   */
  com.pearl.fcw.proto.enums.EActivityActionType getAction();

  /**
   * <code>optional sint32 needAward = 30;</code>
   */
  int getNeedAward();

  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> 
      getItemsList();
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItem getItems(int index);
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .fcw.proto.model.ProtoSysItem items = 31;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItemOrBuilder getItemsOrBuilder(
      int index);
}
