// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * Protobuf type {@code fcw.proto.model.ProtoSysItemResource}
 */
public  final class ProtoSysItemResource extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoSysItemResource)
    ProtoSysItemResourceOrBuilder {
  // Use ProtoSysItemResource.newBuilder() to construct.
  private ProtoSysItemResource(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoSysItemResource() {
    type_ = 0;
    res_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoSysItemResource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            type_ = input.readSInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              res_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            res_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        res_ = res_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemResource_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemResource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoSysItemResource.class, com.pearl.fcw.proto.model.ProtoSysItemResource.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   *指向SysItem的wId或者cId
   * </pre>
   *
   * <code>optional sint32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int RES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList res_;
  /**
   * <code>repeated string res = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getResList() {
    return res_;
  }
  /**
   * <code>repeated string res = 2;</code>
   */
  public int getResCount() {
    return res_.size();
  }
  /**
   * <code>repeated string res = 2;</code>
   */
  public java.lang.String getRes(int index) {
    return res_.get(index);
  }
  /**
   * <code>repeated string res = 2;</code>
   */
  public com.google.protobuf.ByteString
      getResBytes(int index) {
    return res_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeSInt32(1, type_);
    }
    for (int i = 0; i < res_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, res_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, type_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < res_.size(); i++) {
        dataSize += computeStringSizeNoTag(res_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getResList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoSysItemResource)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoSysItemResource other = (com.pearl.fcw.proto.model.ProtoSysItemResource) obj;

    boolean result = true;
    result = result && (getType()
        == other.getType());
    result = result && getResList()
        .equals(other.getResList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    if (getResCount() > 0) {
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + getResList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoSysItemResource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoSysItemResource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.model.ProtoSysItemResource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoSysItemResource)
      com.pearl.fcw.proto.model.ProtoSysItemResourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemResource_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemResource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoSysItemResource.class, com.pearl.fcw.proto.model.ProtoSysItemResource.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoSysItemResource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      res_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoSysItemResource_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoSysItemResource getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoSysItemResource.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoSysItemResource build() {
      com.pearl.fcw.proto.model.ProtoSysItemResource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoSysItemResource buildPartial() {
      com.pearl.fcw.proto.model.ProtoSysItemResource result = new com.pearl.fcw.proto.model.ProtoSysItemResource(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        res_ = res_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.res_ = res_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoSysItemResource) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoSysItemResource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoSysItemResource other) {
      if (other == com.pearl.fcw.proto.model.ProtoSysItemResource.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.res_.isEmpty()) {
        if (res_.isEmpty()) {
          res_ = other.res_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureResIsMutable();
          res_.addAll(other.res_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoSysItemResource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoSysItemResource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <pre>
     *指向SysItem的wId或者cId
     * </pre>
     *
     * <code>optional sint32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     *指向SysItem的wId或者cId
     * </pre>
     *
     * <code>optional sint32 type = 1;</code>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *指向SysItem的wId或者cId
     * </pre>
     *
     * <code>optional sint32 type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList res_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureResIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        res_ = new com.google.protobuf.LazyStringArrayList(res_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getResList() {
      return res_.getUnmodifiableView();
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public int getResCount() {
      return res_.size();
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public java.lang.String getRes(int index) {
      return res_.get(index);
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResBytes(int index) {
      return res_.getByteString(index);
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public Builder setRes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResIsMutable();
      res_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public Builder addRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResIsMutable();
      res_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public Builder addAllRes(
        java.lang.Iterable<java.lang.String> values) {
      ensureResIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, res_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public Builder clearRes() {
      res_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string res = 2;</code>
     */
    public Builder addResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureResIsMutable();
      res_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoSysItemResource)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoSysItemResource)
  private static final com.pearl.fcw.proto.model.ProtoSysItemResource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoSysItemResource();
  }

  public static com.pearl.fcw.proto.model.ProtoSysItemResource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoSysItemResource>
      PARSER = new com.google.protobuf.AbstractParser<ProtoSysItemResource>() {
    public ProtoSysItemResource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoSysItemResource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoSysItemResource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoSysItemResource> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoSysItemResource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

