// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * <pre>
 *玩家大厅信息
 * </pre>
 *
 * Protobuf type {@code fcw.proto.model.ProtoPlayerLocation}
 */
public  final class ProtoPlayerLocation extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoPlayerLocation)
    ProtoPlayerLocationOrBuilder {
  // Use ProtoPlayerLocation.newBuilder() to construct.
  private ProtoPlayerLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoPlayerLocation() {
    playerId_ = 0;
    channelId_ = 0;
    serverId_ = 0;
    roomId_ = 0;
    serverName_ = "";
    roomName_ = "";
    loginTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoPlayerLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            playerId_ = input.readInt32();
            break;
          }
          case 16: {

            channelId_ = input.readInt32();
            break;
          }
          case 24: {

            serverId_ = input.readInt32();
            break;
          }
          case 32: {

            roomId_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            serverName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            roomName_ = s;
            break;
          }
          case 56: {

            loginTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerLocation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoPlayerLocation.class, com.pearl.fcw.proto.model.ProtoPlayerLocation.Builder.class);
  }

  public static final int PLAYERID_FIELD_NUMBER = 1;
  private int playerId_;
  /**
   * <code>optional int32 playerId = 1;</code>
   */
  public int getPlayerId() {
    return playerId_;
  }

  public static final int CHANNELID_FIELD_NUMBER = 2;
  private int channelId_;
  /**
   * <code>optional int32 channelId = 2;</code>
   */
  public int getChannelId() {
    return channelId_;
  }

  public static final int SERVERID_FIELD_NUMBER = 3;
  private int serverId_;
  /**
   * <code>optional int32 serverId = 3;</code>
   */
  public int getServerId() {
    return serverId_;
  }

  public static final int ROOMID_FIELD_NUMBER = 4;
  private int roomId_;
  /**
   * <code>optional int32 roomId = 4;</code>
   */
  public int getRoomId() {
    return roomId_;
  }

  public static final int SERVERNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object serverName_;
  /**
   * <code>optional string serverName = 5;</code>
   */
  public java.lang.String getServerName() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string serverName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getServerNameBytes() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object roomName_;
  /**
   * <code>optional string roomName = 6;</code>
   */
  public java.lang.String getRoomName() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string roomName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getRoomNameBytes() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINTIME_FIELD_NUMBER = 7;
  private long loginTime_;
  /**
   * <pre>
   *登录服务器时间，毫秒
   * </pre>
   *
   * <code>optional int64 loginTime = 7;</code>
   */
  public long getLoginTime() {
    return loginTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playerId_ != 0) {
      output.writeInt32(1, playerId_);
    }
    if (channelId_ != 0) {
      output.writeInt32(2, channelId_);
    }
    if (serverId_ != 0) {
      output.writeInt32(3, serverId_);
    }
    if (roomId_ != 0) {
      output.writeInt32(4, roomId_);
    }
    if (!getServerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, serverName_);
    }
    if (!getRoomNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, roomName_);
    }
    if (loginTime_ != 0L) {
      output.writeInt64(7, loginTime_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, playerId_);
    }
    if (channelId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, channelId_);
    }
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, serverId_);
    }
    if (roomId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, roomId_);
    }
    if (!getServerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, serverName_);
    }
    if (!getRoomNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, roomName_);
    }
    if (loginTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, loginTime_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoPlayerLocation)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoPlayerLocation other = (com.pearl.fcw.proto.model.ProtoPlayerLocation) obj;

    boolean result = true;
    result = result && (getPlayerId()
        == other.getPlayerId());
    result = result && (getChannelId()
        == other.getChannelId());
    result = result && (getServerId()
        == other.getServerId());
    result = result && (getRoomId()
        == other.getRoomId());
    result = result && getServerName()
        .equals(other.getServerName());
    result = result && getRoomName()
        .equals(other.getRoomName());
    result = result && (getLoginTime()
        == other.getLoginTime());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerId();
    hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId();
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId();
    hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getServerName().hashCode();
    hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoomName().hashCode();
    hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLoginTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoPlayerLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *玩家大厅信息
   * </pre>
   *
   * Protobuf type {@code fcw.proto.model.ProtoPlayerLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoPlayerLocation)
      com.pearl.fcw.proto.model.ProtoPlayerLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerLocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoPlayerLocation.class, com.pearl.fcw.proto.model.ProtoPlayerLocation.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoPlayerLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      playerId_ = 0;

      channelId_ = 0;

      serverId_ = 0;

      roomId_ = 0;

      serverName_ = "";

      roomName_ = "";

      loginTime_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerLocation_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerLocation getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoPlayerLocation.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoPlayerLocation build() {
      com.pearl.fcw.proto.model.ProtoPlayerLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerLocation buildPartial() {
      com.pearl.fcw.proto.model.ProtoPlayerLocation result = new com.pearl.fcw.proto.model.ProtoPlayerLocation(this);
      result.playerId_ = playerId_;
      result.channelId_ = channelId_;
      result.serverId_ = serverId_;
      result.roomId_ = roomId_;
      result.serverName_ = serverName_;
      result.roomName_ = roomName_;
      result.loginTime_ = loginTime_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoPlayerLocation) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoPlayerLocation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoPlayerLocation other) {
      if (other == com.pearl.fcw.proto.model.ProtoPlayerLocation.getDefaultInstance()) return this;
      if (other.getPlayerId() != 0) {
        setPlayerId(other.getPlayerId());
      }
      if (other.getChannelId() != 0) {
        setChannelId(other.getChannelId());
      }
      if (other.getServerId() != 0) {
        setServerId(other.getServerId());
      }
      if (other.getRoomId() != 0) {
        setRoomId(other.getRoomId());
      }
      if (!other.getServerName().isEmpty()) {
        serverName_ = other.serverName_;
        onChanged();
      }
      if (!other.getRoomName().isEmpty()) {
        roomName_ = other.roomName_;
        onChanged();
      }
      if (other.getLoginTime() != 0L) {
        setLoginTime(other.getLoginTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoPlayerLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoPlayerLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int playerId_ ;
    /**
     * <code>optional int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }
    /**
     * <code>optional int32 playerId = 1;</code>
     */
    public Builder setPlayerId(int value) {
      
      playerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 playerId = 1;</code>
     */
    public Builder clearPlayerId() {
      
      playerId_ = 0;
      onChanged();
      return this;
    }

    private int channelId_ ;
    /**
     * <code>optional int32 channelId = 2;</code>
     */
    public int getChannelId() {
      return channelId_;
    }
    /**
     * <code>optional int32 channelId = 2;</code>
     */
    public Builder setChannelId(int value) {
      
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 channelId = 2;</code>
     */
    public Builder clearChannelId() {
      
      channelId_ = 0;
      onChanged();
      return this;
    }

    private int serverId_ ;
    /**
     * <code>optional int32 serverId = 3;</code>
     */
    public int getServerId() {
      return serverId_;
    }
    /**
     * <code>optional int32 serverId = 3;</code>
     */
    public Builder setServerId(int value) {
      
      serverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 serverId = 3;</code>
     */
    public Builder clearServerId() {
      
      serverId_ = 0;
      onChanged();
      return this;
    }

    private int roomId_ ;
    /**
     * <code>optional int32 roomId = 4;</code>
     */
    public int getRoomId() {
      return roomId_;
    }
    /**
     * <code>optional int32 roomId = 4;</code>
     */
    public Builder setRoomId(int value) {
      
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 roomId = 4;</code>
     */
    public Builder clearRoomId() {
      
      roomId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object serverName_ = "";
    /**
     * <code>optional string serverName = 5;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string serverName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string serverName = 5;</code>
     */
    public Builder setServerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string serverName = 5;</code>
     */
    public Builder clearServerName() {
      
      serverName_ = getDefaultInstance().getServerName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string serverName = 5;</code>
     */
    public Builder setServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roomName_ = "";
    /**
     * <code>optional string roomName = 6;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string roomName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string roomName = 6;</code>
     */
    public Builder setRoomName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string roomName = 6;</code>
     */
    public Builder clearRoomName() {
      
      roomName_ = getDefaultInstance().getRoomName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string roomName = 6;</code>
     */
    public Builder setRoomNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomName_ = value;
      onChanged();
      return this;
    }

    private long loginTime_ ;
    /**
     * <pre>
     *登录服务器时间，毫秒
     * </pre>
     *
     * <code>optional int64 loginTime = 7;</code>
     */
    public long getLoginTime() {
      return loginTime_;
    }
    /**
     * <pre>
     *登录服务器时间，毫秒
     * </pre>
     *
     * <code>optional int64 loginTime = 7;</code>
     */
    public Builder setLoginTime(long value) {
      
      loginTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *登录服务器时间，毫秒
     * </pre>
     *
     * <code>optional int64 loginTime = 7;</code>
     */
    public Builder clearLoginTime() {
      
      loginTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoPlayerLocation)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoPlayerLocation)
  private static final com.pearl.fcw.proto.model.ProtoPlayerLocation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoPlayerLocation();
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPlayerLocation>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPlayerLocation>() {
    public ProtoPlayerLocation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPlayerLocation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoPlayerLocation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPlayerLocation> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoPlayerLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

