// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.pearl.fcw.proto.model;

/**
 * Protobuf type {@code fcw.proto.model.ProtoPlayerAchievement}
 */
public  final class ProtoPlayerAchievement extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.model.ProtoPlayerAchievement)
    ProtoPlayerAchievementOrBuilder {
  // Use ProtoPlayerAchievement.newBuilder() to construct.
  private ProtoPlayerAchievement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProtoPlayerAchievement() {
    id_ = 0;
    sysCharacterId_ = 0;
    status_ = 0;
    sysAchievementId_ = java.util.Collections.emptyList();
    group_ = 0;
    level_ = 0;
    number_ = 0;
    backUp_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProtoPlayerAchievement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readSInt32();
            break;
          }
          case 16: {

            sysCharacterId_ = input.readSInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              sysAchievementId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            sysAchievementId_.add(input.readSInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              sysAchievementId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              sysAchievementId_.add(input.readSInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {

            group_ = input.readSInt32();
            break;
          }
          case 48: {

            level_ = input.readSInt32();
            break;
          }
          case 56: {

            number_ = input.readSInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            backUp_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        sysAchievementId_ = java.util.Collections.unmodifiableList(sysAchievementId_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerAchievement_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerAchievement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.model.ProtoPlayerAchievement.class, com.pearl.fcw.proto.model.ProtoPlayerAchievement.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional sint32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int SYSCHARACTERID_FIELD_NUMBER = 2;
  private int sysCharacterId_;
  /**
   * <code>optional sint32 sysCharacterId = 2;</code>
   */
  public int getSysCharacterId() {
    return sysCharacterId_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
   */
  public com.pearl.fcw.proto.enums.EAchievementStatus getStatus() {
    com.pearl.fcw.proto.enums.EAchievementStatus result = com.pearl.fcw.proto.enums.EAchievementStatus.forNumber(status_);
    return result == null ? com.pearl.fcw.proto.enums.EAchievementStatus.UNRECOGNIZED : result;
  }

  public static final int SYSACHIEVEMENTID_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Integer> sysAchievementId_;
  /**
   * <code>repeated sint32 sysAchievementId = 4;</code>
   */
  public java.util.List<java.lang.Integer>
      getSysAchievementIdList() {
    return sysAchievementId_;
  }
  /**
   * <code>repeated sint32 sysAchievementId = 4;</code>
   */
  public int getSysAchievementIdCount() {
    return sysAchievementId_.size();
  }
  /**
   * <code>repeated sint32 sysAchievementId = 4;</code>
   */
  public int getSysAchievementId(int index) {
    return sysAchievementId_.get(index);
  }
  private int sysAchievementIdMemoizedSerializedSize = -1;

  public static final int GROUP_FIELD_NUMBER = 5;
  private int group_;
  /**
   * <code>optional sint32 group = 5;</code>
   */
  public int getGroup() {
    return group_;
  }

  public static final int LEVEL_FIELD_NUMBER = 6;
  private int level_;
  /**
   * <pre>
   *下一个将要完成的成就的索引
   * </pre>
   *
   * <code>optional sint32 level = 6;</code>
   */
  public int getLevel() {
    return level_;
  }

  public static final int NUMBER_FIELD_NUMBER = 7;
  private int number_;
  /**
   * <pre>
   *完成数
   * </pre>
   *
   * <code>optional sint32 number = 7;</code>
   */
  public int getNumber() {
    return number_;
  }

  public static final int BACKUP_FIELD_NUMBER = 8;
  private volatile java.lang.Object backUp_;
  /**
   * <code>optional string backUp = 8;</code>
   */
  public java.lang.String getBackUp() {
    java.lang.Object ref = backUp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backUp_ = s;
      return s;
    }
  }
  /**
   * <code>optional string backUp = 8;</code>
   */
  public com.google.protobuf.ByteString
      getBackUpBytes() {
    java.lang.Object ref = backUp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backUp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeSInt32(1, id_);
    }
    if (sysCharacterId_ != 0) {
      output.writeSInt32(2, sysCharacterId_);
    }
    if (status_ != com.pearl.fcw.proto.enums.EAchievementStatus.ACHIEVEMENT_AWAIT.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (getSysAchievementIdList().size() > 0) {
      output.writeRawVarint32(34);
      output.writeRawVarint32(sysAchievementIdMemoizedSerializedSize);
    }
    for (int i = 0; i < sysAchievementId_.size(); i++) {
      output.writeSInt32NoTag(sysAchievementId_.get(i));
    }
    if (group_ != 0) {
      output.writeSInt32(5, group_);
    }
    if (level_ != 0) {
      output.writeSInt32(6, level_);
    }
    if (number_ != 0) {
      output.writeSInt32(7, number_);
    }
    if (!getBackUpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, backUp_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, id_);
    }
    if (sysCharacterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, sysCharacterId_);
    }
    if (status_ != com.pearl.fcw.proto.enums.EAchievementStatus.ACHIEVEMENT_AWAIT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sysAchievementId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt32SizeNoTag(sysAchievementId_.get(i));
      }
      size += dataSize;
      if (!getSysAchievementIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      sysAchievementIdMemoizedSerializedSize = dataSize;
    }
    if (group_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(5, group_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(6, level_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(7, number_);
    }
    if (!getBackUpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, backUp_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.model.ProtoPlayerAchievement)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.model.ProtoPlayerAchievement other = (com.pearl.fcw.proto.model.ProtoPlayerAchievement) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getSysCharacterId()
        == other.getSysCharacterId());
    result = result && status_ == other.status_;
    result = result && getSysAchievementIdList()
        .equals(other.getSysAchievementIdList());
    result = result && (getGroup()
        == other.getGroup());
    result = result && (getLevel()
        == other.getLevel());
    result = result && (getNumber()
        == other.getNumber());
    result = result && getBackUp()
        .equals(other.getBackUp());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + SYSCHARACTERID_FIELD_NUMBER;
    hash = (53 * hash) + getSysCharacterId();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getSysAchievementIdCount() > 0) {
      hash = (37 * hash) + SYSACHIEVEMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getSysAchievementIdList().hashCode();
    }
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (37 * hash) + BACKUP_FIELD_NUMBER;
    hash = (53 * hash) + getBackUp().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.model.ProtoPlayerAchievement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.model.ProtoPlayerAchievement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.model.ProtoPlayerAchievement)
      com.pearl.fcw.proto.model.ProtoPlayerAchievementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerAchievement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerAchievement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.model.ProtoPlayerAchievement.class, com.pearl.fcw.proto.model.ProtoPlayerAchievement.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.model.ProtoPlayerAchievement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      sysCharacterId_ = 0;

      status_ = 0;

      sysAchievementId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      group_ = 0;

      level_ = 0;

      number_ = 0;

      backUp_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.model.ApiProto.internal_static_fcw_proto_model_ProtoPlayerAchievement_descriptor;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerAchievement getDefaultInstanceForType() {
      return com.pearl.fcw.proto.model.ProtoPlayerAchievement.getDefaultInstance();
    }

    public com.pearl.fcw.proto.model.ProtoPlayerAchievement build() {
      com.pearl.fcw.proto.model.ProtoPlayerAchievement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.model.ProtoPlayerAchievement buildPartial() {
      com.pearl.fcw.proto.model.ProtoPlayerAchievement result = new com.pearl.fcw.proto.model.ProtoPlayerAchievement(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.sysCharacterId_ = sysCharacterId_;
      result.status_ = status_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        sysAchievementId_ = java.util.Collections.unmodifiableList(sysAchievementId_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.sysAchievementId_ = sysAchievementId_;
      result.group_ = group_;
      result.level_ = level_;
      result.number_ = number_;
      result.backUp_ = backUp_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.model.ProtoPlayerAchievement) {
        return mergeFrom((com.pearl.fcw.proto.model.ProtoPlayerAchievement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.model.ProtoPlayerAchievement other) {
      if (other == com.pearl.fcw.proto.model.ProtoPlayerAchievement.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getSysCharacterId() != 0) {
        setSysCharacterId(other.getSysCharacterId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.sysAchievementId_.isEmpty()) {
        if (sysAchievementId_.isEmpty()) {
          sysAchievementId_ = other.sysAchievementId_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureSysAchievementIdIsMutable();
          sysAchievementId_.addAll(other.sysAchievementId_);
        }
        onChanged();
      }
      if (other.getGroup() != 0) {
        setGroup(other.getGroup());
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      if (!other.getBackUp().isEmpty()) {
        backUp_ = other.backUp_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.model.ProtoPlayerAchievement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.model.ProtoPlayerAchievement) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int sysCharacterId_ ;
    /**
     * <code>optional sint32 sysCharacterId = 2;</code>
     */
    public int getSysCharacterId() {
      return sysCharacterId_;
    }
    /**
     * <code>optional sint32 sysCharacterId = 2;</code>
     */
    public Builder setSysCharacterId(int value) {
      
      sysCharacterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 sysCharacterId = 2;</code>
     */
    public Builder clearSysCharacterId() {
      
      sysCharacterId_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
     */
    public com.pearl.fcw.proto.enums.EAchievementStatus getStatus() {
      com.pearl.fcw.proto.enums.EAchievementStatus result = com.pearl.fcw.proto.enums.EAchievementStatus.forNumber(status_);
      return result == null ? com.pearl.fcw.proto.enums.EAchievementStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
     */
    public Builder setStatus(com.pearl.fcw.proto.enums.EAchievementStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .fcw.proto.enums.status.EAchievementStatus status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> sysAchievementId_ = java.util.Collections.emptyList();
    private void ensureSysAchievementIdIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        sysAchievementId_ = new java.util.ArrayList<java.lang.Integer>(sysAchievementId_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getSysAchievementIdList() {
      return java.util.Collections.unmodifiableList(sysAchievementId_);
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public int getSysAchievementIdCount() {
      return sysAchievementId_.size();
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public int getSysAchievementId(int index) {
      return sysAchievementId_.get(index);
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public Builder setSysAchievementId(
        int index, int value) {
      ensureSysAchievementIdIsMutable();
      sysAchievementId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public Builder addSysAchievementId(int value) {
      ensureSysAchievementIdIsMutable();
      sysAchievementId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public Builder addAllSysAchievementId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureSysAchievementIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sysAchievementId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 sysAchievementId = 4;</code>
     */
    public Builder clearSysAchievementId() {
      sysAchievementId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private int group_ ;
    /**
     * <code>optional sint32 group = 5;</code>
     */
    public int getGroup() {
      return group_;
    }
    /**
     * <code>optional sint32 group = 5;</code>
     */
    public Builder setGroup(int value) {
      
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 group = 5;</code>
     */
    public Builder clearGroup() {
      
      group_ = 0;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <pre>
     *下一个将要完成的成就的索引
     * </pre>
     *
     * <code>optional sint32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }
    /**
     * <pre>
     *下一个将要完成的成就的索引
     * </pre>
     *
     * <code>optional sint32 level = 6;</code>
     */
    public Builder setLevel(int value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *下一个将要完成的成就的索引
     * </pre>
     *
     * <code>optional sint32 level = 6;</code>
     */
    public Builder clearLevel() {
      
      level_ = 0;
      onChanged();
      return this;
    }

    private int number_ ;
    /**
     * <pre>
     *完成数
     * </pre>
     *
     * <code>optional sint32 number = 7;</code>
     */
    public int getNumber() {
      return number_;
    }
    /**
     * <pre>
     *完成数
     * </pre>
     *
     * <code>optional sint32 number = 7;</code>
     */
    public Builder setNumber(int value) {
      
      number_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *完成数
     * </pre>
     *
     * <code>optional sint32 number = 7;</code>
     */
    public Builder clearNumber() {
      
      number_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object backUp_ = "";
    /**
     * <code>optional string backUp = 8;</code>
     */
    public java.lang.String getBackUp() {
      java.lang.Object ref = backUp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backUp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string backUp = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBackUpBytes() {
      java.lang.Object ref = backUp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backUp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string backUp = 8;</code>
     */
    public Builder setBackUp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backUp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string backUp = 8;</code>
     */
    public Builder clearBackUp() {
      
      backUp_ = getDefaultInstance().getBackUp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string backUp = 8;</code>
     */
    public Builder setBackUpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backUp_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.model.ProtoPlayerAchievement)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.model.ProtoPlayerAchievement)
  private static final com.pearl.fcw.proto.model.ProtoPlayerAchievement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.model.ProtoPlayerAchievement();
  }

  public static com.pearl.fcw.proto.model.ProtoPlayerAchievement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoPlayerAchievement>
      PARSER = new com.google.protobuf.AbstractParser<ProtoPlayerAchievement>() {
    public ProtoPlayerAchievement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPlayerAchievement(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoPlayerAchievement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoPlayerAchievement> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.model.ProtoPlayerAchievement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

