{
	cmd="module_status_change",
	num= #$num#,
	list = {
		Mission = {
			state = #$mission#
		},
		DailyMission = {
			state = #$dailyMission#
		},
		Compose = {
			state = #$compose#
		},
		Online = {
			state = #$online#
		},
		Present = {
			state = #$present#
		},
		DailyCheck = {
			state = #$dailyCheck#
		},
		FreeChange = {
			state = #$freeChange#
		},
		Shot = {
			state = #$shot#
		}
	}
}