info = {
	meltingLevel = #$proto.playerMelting.level#,
	slotNum = #$proto.playerMelting.slotNum#,
	exp = #$proto.playerMelting.exp#,
	total_exp = #$proto.playerMelting.totalExp#,
	meltingEnergy = #$proto.playerMelting.num#,
	remaind = #$proto.playerMelting.remaindSecond#,
	residual = #$proto.playerMelting.remaindInt#,
	rate = #$proto.playerMelting.rate#,
	price = #$proto.playerMelting.price#,
	recycle_ratio = #$proto.playerMelting.recycleRatio#
}
