
-- 新闻资讯表
CREATE TABLE `CMS_NEWS` (
  `NEWS_ID_B` bigint(20) NOT NULL COMMENT '表主键--新闻编号',
  `NEWS_COLUMN_ID_B` bigint(20) DEFAULT NULL COMMENT '栏目编号（CMS_NEWS_COLUMN 表主键）',
  `HEADLINE_V` varchar(50) DEFAULT NULL COMMENT '正标题',
  `SUBHEAD_V` varchar(150) DEFAULT NULL COMMENT '副标题',
  `CONTENT_T` text COMMENT '新闻内容',
  `AUTHOR_V` varchar(32) DEFAULT NULL COMMENT '作者',
  `TOP_LEVEL_I` int(11) DEFAULT NULL COMMENT '置顶级别',
  `PRIORITY_LEVEL_I` int(4) DEFAULT NULL COMMENT '显示优先级',
  `HEADLINE_STATUS_I` int(1) DEFAULT NULL COMMENT '是否头条：1-是；0-不是',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '新闻状态：1-显示；0-不显示',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  `TYPE_I` int(4) DEFAULT NULL COMMENT '新闻类型：1-CMS；2-游戏；3-媒体',
  PRIMARY KEY (`NEWS_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='新闻资讯表';

-- 资讯栏目表
CREATE TABLE `CMS_NEWS_COLUMN` (
  `NEWS_COLUMN_ID_B` bigint(20) NOT NULL COMMENT '表主键--栏目编号',
  `COLUMN_NAME_V` varchar(64) DEFAULT NULL COMMENT '栏目名称',
  `STATUS_I` int(1) DEFAULT NULL COMMENT '栏目状态：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`NEWS_COLUMN_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资讯栏目表';

-- 初始化语句
INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (1, '游戏攻略', 1, now(), null, 1);

INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (2, '游戏试玩', 1, now(), null, 1);

INSERT INTO CMS_NEWS_COLUMN
(NEWS_COLUMN_ID_B, COLUMN_NAME_V, STATUS_I, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (3, '游戏MM', 1, now(), null, 1);
