// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface RequestShopExchangeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.RequestShopExchangeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 playerId = 1;</code>
   */
  int getPlayerId();

  /**
   * <pre>
   *当前页码
   * </pre>
   *
   * <code>optional int32 page = 2;</code>
   */
  int getPage();

  /**
   * <code>optional int32 isBlueprint = 3;</code>
   */
  int getIsBlueprint();

  /**
   * <code>optional .fcw.proto.enums.type.EItemType itemType = 4;</code>
   */
  int getItemTypeValue();
  /**
   * <code>optional .fcw.proto.enums.type.EItemType itemType = 4;</code>
   */
  com.pearl.fcw.proto.enums.EItemType getItemType();

  /**
   * <code>optional .fcw.proto.enums.type.EItemSubType itemSubType = 5;</code>
   */
  int getItemSubTypeValue();
  /**
   * <code>optional .fcw.proto.enums.type.EItemSubType itemSubType = 5;</code>
   */
  com.pearl.fcw.proto.enums.EItemSubType getItemSubType();
}
