// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface RequestRemoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.RequestRemove)
    com.google.protobuf.MessageOrBuilder {
}
