// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

/**
 * Protobuf type {@code fcw.proto.server.ResponseStorageList}
 */
public  final class ResponseStorageList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.server.ResponseStorageList)
    ResponseStorageListOrBuilder {
  // Use ResponseStorageList.newBuilder() to construct.
  private ResponseStorageList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponseStorageList() {
    page_ = 0;
    pages_ = 0;
    playerRank_ = 0;
    items_ = java.util.Collections.emptyList();
    currenttime_ = 0L;
    maxDuration_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ResponseStorageList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            page_ = input.readSInt32();
            break;
          }
          case 16: {

            pages_ = input.readSInt32();
            break;
          }
          case 24: {

            playerRank_ = input.readSInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              items_ = new java.util.ArrayList<com.pearl.fcw.proto.model.ProtoPlayerItem>();
              mutable_bitField0_ |= 0x00000008;
            }
            items_.add(input.readMessage(com.pearl.fcw.proto.model.ProtoPlayerItem.parser(), extensionRegistry));
            break;
          }
          case 40: {

            currenttime_ = input.readSInt64();
            break;
          }
          case 53: {

            maxDuration_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseStorageList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseStorageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.rpc.ResponseStorageList.class, com.pearl.fcw.proto.rpc.ResponseStorageList.Builder.class);
  }

  private int bitField0_;
  public static final int PAGE_FIELD_NUMBER = 1;
  private int page_;
  /**
   * <code>optional sint32 page = 1;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int PAGES_FIELD_NUMBER = 2;
  private int pages_;
  /**
   * <code>optional sint32 pages = 2;</code>
   */
  public int getPages() {
    return pages_;
  }

  public static final int PLAYERRANK_FIELD_NUMBER = 3;
  private int playerRank_;
  /**
   * <code>optional sint32 playerRank = 3;</code>
   */
  public int getPlayerRank() {
    return playerRank_;
  }

  public static final int ITEMS_FIELD_NUMBER = 4;
  private java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> items_;
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
   */
  public java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
   */
  public java.util.List<? extends com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
   */
  public com.pearl.fcw.proto.model.ProtoPlayerItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
   */
  public com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int CURRENTTIME_FIELD_NUMBER = 5;
  private long currenttime_;
  /**
   * <code>optional sint64 currenttime = 5;</code>
   */
  public long getCurrenttime() {
    return currenttime_;
  }

  public static final int MAXDURATION_FIELD_NUMBER = 6;
  private float maxDuration_;
  /**
   * <pre>
   *道具的公共最大耐久
   * </pre>
   *
   * <code>optional float maxDuration = 6;</code>
   */
  public float getMaxDuration() {
    return maxDuration_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (page_ != 0) {
      output.writeSInt32(1, page_);
    }
    if (pages_ != 0) {
      output.writeSInt32(2, pages_);
    }
    if (playerRank_ != 0) {
      output.writeSInt32(3, playerRank_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(4, items_.get(i));
    }
    if (currenttime_ != 0L) {
      output.writeSInt64(5, currenttime_);
    }
    if (maxDuration_ != 0F) {
      output.writeFloat(6, maxDuration_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, page_);
    }
    if (pages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, pages_);
    }
    if (playerRank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, playerRank_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, items_.get(i));
    }
    if (currenttime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(5, currenttime_);
    }
    if (maxDuration_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, maxDuration_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.rpc.ResponseStorageList)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.rpc.ResponseStorageList other = (com.pearl.fcw.proto.rpc.ResponseStorageList) obj;

    boolean result = true;
    result = result && (getPage()
        == other.getPage());
    result = result && (getPages()
        == other.getPages());
    result = result && (getPlayerRank()
        == other.getPlayerRank());
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && (getCurrenttime()
        == other.getCurrenttime());
    result = result && (
        java.lang.Float.floatToIntBits(getMaxDuration())
        == java.lang.Float.floatToIntBits(
            other.getMaxDuration()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getPages();
    hash = (37 * hash) + PLAYERRANK_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerRank();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + CURRENTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrenttime());
    hash = (37 * hash) + MAXDURATION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxDuration());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseStorageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.rpc.ResponseStorageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.server.ResponseStorageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.server.ResponseStorageList)
      com.pearl.fcw.proto.rpc.ResponseStorageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseStorageList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseStorageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.rpc.ResponseStorageList.class, com.pearl.fcw.proto.rpc.ResponseStorageList.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.rpc.ResponseStorageList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      page_ = 0;

      pages_ = 0;

      playerRank_ = 0;

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        itemsBuilder_.clear();
      }
      currenttime_ = 0L;

      maxDuration_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseStorageList_descriptor;
    }

    public com.pearl.fcw.proto.rpc.ResponseStorageList getDefaultInstanceForType() {
      return com.pearl.fcw.proto.rpc.ResponseStorageList.getDefaultInstance();
    }

    public com.pearl.fcw.proto.rpc.ResponseStorageList build() {
      com.pearl.fcw.proto.rpc.ResponseStorageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.rpc.ResponseStorageList buildPartial() {
      com.pearl.fcw.proto.rpc.ResponseStorageList result = new com.pearl.fcw.proto.rpc.ResponseStorageList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.page_ = page_;
      result.pages_ = pages_;
      result.playerRank_ = playerRank_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.currenttime_ = currenttime_;
      result.maxDuration_ = maxDuration_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.rpc.ResponseStorageList) {
        return mergeFrom((com.pearl.fcw.proto.rpc.ResponseStorageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.rpc.ResponseStorageList other) {
      if (other == com.pearl.fcw.proto.rpc.ResponseStorageList.getDefaultInstance()) return this;
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getPages() != 0) {
        setPages(other.getPages());
      }
      if (other.getPlayerRank() != 0) {
        setPlayerRank(other.getPlayerRank());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000008);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.getCurrenttime() != 0L) {
        setCurrenttime(other.getCurrenttime());
      }
      if (other.getMaxDuration() != 0F) {
        setMaxDuration(other.getMaxDuration());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.rpc.ResponseStorageList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.rpc.ResponseStorageList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int page_ ;
    /**
     * <code>optional sint32 page = 1;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>optional sint32 page = 1;</code>
     */
    public Builder setPage(int value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 page = 1;</code>
     */
    public Builder clearPage() {
      
      page_ = 0;
      onChanged();
      return this;
    }

    private int pages_ ;
    /**
     * <code>optional sint32 pages = 2;</code>
     */
    public int getPages() {
      return pages_;
    }
    /**
     * <code>optional sint32 pages = 2;</code>
     */
    public Builder setPages(int value) {
      
      pages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 pages = 2;</code>
     */
    public Builder clearPages() {
      
      pages_ = 0;
      onChanged();
      return this;
    }

    private int playerRank_ ;
    /**
     * <code>optional sint32 playerRank = 3;</code>
     */
    public int getPlayerRank() {
      return playerRank_;
    }
    /**
     * <code>optional sint32 playerRank = 3;</code>
     */
    public Builder setPlayerRank(int value) {
      
      playerRank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 playerRank = 3;</code>
     */
    public Builder clearPlayerRank() {
      
      playerRank_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        items_ = new java.util.ArrayList<com.pearl.fcw.proto.model.ProtoPlayerItem>(items_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.pearl.fcw.proto.model.ProtoPlayerItem, com.pearl.fcw.proto.model.ProtoPlayerItem.Builder, com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder setItems(
        int index, com.pearl.fcw.proto.model.ProtoPlayerItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder setItems(
        int index, com.pearl.fcw.proto.model.ProtoPlayerItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder addItems(com.pearl.fcw.proto.model.ProtoPlayerItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder addItems(
        int index, com.pearl.fcw.proto.model.ProtoPlayerItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder addItems(
        com.pearl.fcw.proto.model.ProtoPlayerItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder addItems(
        int index, com.pearl.fcw.proto.model.ProtoPlayerItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.pearl.fcw.proto.model.ProtoPlayerItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public java.util.List<? extends com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.pearl.fcw.proto.model.ProtoPlayerItem.getDefaultInstance());
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.pearl.fcw.proto.model.ProtoPlayerItem.getDefaultInstance());
    }
    /**
     * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 4;</code>
     */
    public java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.pearl.fcw.proto.model.ProtoPlayerItem, com.pearl.fcw.proto.model.ProtoPlayerItem.Builder, com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.pearl.fcw.proto.model.ProtoPlayerItem, com.pearl.fcw.proto.model.ProtoPlayerItem.Builder, com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private long currenttime_ ;
    /**
     * <code>optional sint64 currenttime = 5;</code>
     */
    public long getCurrenttime() {
      return currenttime_;
    }
    /**
     * <code>optional sint64 currenttime = 5;</code>
     */
    public Builder setCurrenttime(long value) {
      
      currenttime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint64 currenttime = 5;</code>
     */
    public Builder clearCurrenttime() {
      
      currenttime_ = 0L;
      onChanged();
      return this;
    }

    private float maxDuration_ ;
    /**
     * <pre>
     *道具的公共最大耐久
     * </pre>
     *
     * <code>optional float maxDuration = 6;</code>
     */
    public float getMaxDuration() {
      return maxDuration_;
    }
    /**
     * <pre>
     *道具的公共最大耐久
     * </pre>
     *
     * <code>optional float maxDuration = 6;</code>
     */
    public Builder setMaxDuration(float value) {
      
      maxDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *道具的公共最大耐久
     * </pre>
     *
     * <code>optional float maxDuration = 6;</code>
     */
    public Builder clearMaxDuration() {
      
      maxDuration_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.server.ResponseStorageList)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.server.ResponseStorageList)
  private static final com.pearl.fcw.proto.rpc.ResponseStorageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.rpc.ResponseStorageList();
  }

  public static com.pearl.fcw.proto.rpc.ResponseStorageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseStorageList>
      PARSER = new com.google.protobuf.AbstractParser<ResponseStorageList>() {
    public ResponseStorageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseStorageList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseStorageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseStorageList> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.rpc.ResponseStorageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

