// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface ResponseStrengthItemListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.ResponseStrengthItemList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional sint32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>optional sint32 pages = 2;</code>
   */
  int getPages();

  /**
   * <code>optional sint32 playerRank = 3;</code>
   */
  int getPlayerRank();

  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> 
      getItemsList();
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItem getItems(int index);
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   *星级经验阈值，一维索引是稀有度类型&#64;EItemRareType，二维索引是星级
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoList gstExp = 20;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoList> 
      getGstExpList();
  /**
   * <pre>
   *星级经验阈值，一维索引是稀有度类型&#64;EItemRareType，二维索引是星级
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoList gstExp = 20;</code>
   */
  com.pearl.fcw.proto.model.ProtoList getGstExp(int index);
  /**
   * <pre>
   *星级经验阈值，一维索引是稀有度类型&#64;EItemRareType，二维索引是星级
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoList gstExp = 20;</code>
   */
  int getGstExpCount();
  /**
   * <pre>
   *星级经验阈值，一维索引是稀有度类型&#64;EItemRareType，二维索引是星级
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoList gstExp = 20;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoListOrBuilder> 
      getGstExpOrBuilderList();
  /**
   * <pre>
   *星级经验阈值，一维索引是稀有度类型&#64;EItemRareType，二维索引是星级
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoList gstExp = 20;</code>
   */
  com.pearl.fcw.proto.model.ProtoListOrBuilder getGstExpOrBuilder(
      int index);

  /**
   * <pre>
   *每日合成可购买的星级经验，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombine = 21;</code>
   */
  java.util.List<java.lang.Integer> getEverydayGstExpInCombineList();
  /**
   * <pre>
   *每日合成可购买的星级经验，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombine = 21;</code>
   */
  int getEverydayGstExpInCombineCount();
  /**
   * <pre>
   *每日合成可购买的星级经验，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombine = 21;</code>
   */
  int getEverydayGstExpInCombine(int index);

  /**
   * <pre>
   *每日合成购买星级经验标记，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombineUseFlag = 22;</code>
   */
  java.util.List<java.lang.Integer> getEverydayGstExpInCombineUseFlagList();
  /**
   * <pre>
   *每日合成购买星级经验标记，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombineUseFlag = 22;</code>
   */
  int getEverydayGstExpInCombineUseFlagCount();
  /**
   * <pre>
   *每日合成购买星级经验标记，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGstExpInCombineUseFlag = 22;</code>
   */
  int getEverydayGstExpInCombineUseFlag(int index);

  /**
   * <pre>
   *每日合成购买星级经验花费，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGpointInCombine = 23;</code>
   */
  java.util.List<java.lang.Integer> getEverydayGpointInCombineList();
  /**
   * <pre>
   *每日合成购买星级经验花费，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGpointInCombine = 23;</code>
   */
  int getEverydayGpointInCombineCount();
  /**
   * <pre>
   *每日合成购买星级经验花费，索引是稀有度类型&#64;EItemRareType
   * </pre>
   *
   * <code>repeated sint32 everydayGpointInCombine = 23;</code>
   */
  int getEverydayGpointInCombine(int index);
}
