// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface ResponseMeltingInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.ResponseMeltingInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .fcw.proto.enums.status.EMeltingResult result = 1;</code>
   */
  int getResultValue();
  /**
   * <code>optional .fcw.proto.enums.status.EMeltingResult result = 1;</code>
   */
  com.pearl.fcw.proto.enums.EMeltingResult getResult();

  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 10;</code>
   */
  boolean hasPlayerMelting();
  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerMelting getPlayerMelting();
  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder getPlayerMeltingOrBuilder();

  /**
   * <pre>
   *奖励
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysItem item = 11;</code>
   */
  boolean hasItem();
  /**
   * <pre>
   *奖励
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysItem item = 11;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItem getItem();
  /**
   * <pre>
   *奖励
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysItem item = 11;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItemOrBuilder getItemOrBuilder();
}
