// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

/**
 * Protobuf type {@code fcw.proto.server.ResponseMeltingInfoGet}
 */
public  final class ResponseMeltingInfoGet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.server.ResponseMeltingInfoGet)
    ResponseMeltingInfoGetOrBuilder {
  // Use ResponseMeltingInfoGet.newBuilder() to construct.
  private ResponseMeltingInfoGet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponseMeltingInfoGet() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ResponseMeltingInfoGet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder subBuilder = null;
            if (playerMelting_ != null) {
              subBuilder = playerMelting_.toBuilder();
            }
            playerMelting_ = input.readMessage(com.pearl.fcw.proto.model.ProtoPlayerMelting.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(playerMelting_);
              playerMelting_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseMeltingInfoGet_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseMeltingInfoGet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.class, com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.Builder.class);
  }

  public static final int PLAYERMELTING_FIELD_NUMBER = 1;
  private com.pearl.fcw.proto.model.ProtoPlayerMelting playerMelting_;
  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
   */
  public boolean hasPlayerMelting() {
    return playerMelting_ != null;
  }
  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
   */
  public com.pearl.fcw.proto.model.ProtoPlayerMelting getPlayerMelting() {
    return playerMelting_ == null ? com.pearl.fcw.proto.model.ProtoPlayerMelting.getDefaultInstance() : playerMelting_;
  }
  /**
   * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
   */
  public com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder getPlayerMeltingOrBuilder() {
    return getPlayerMelting();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playerMelting_ != null) {
      output.writeMessage(1, getPlayerMelting());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playerMelting_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPlayerMelting());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet other = (com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet) obj;

    boolean result = true;
    result = result && (hasPlayerMelting() == other.hasPlayerMelting());
    if (hasPlayerMelting()) {
      result = result && getPlayerMelting()
          .equals(other.getPlayerMelting());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasPlayerMelting()) {
      hash = (37 * hash) + PLAYERMELTING_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerMelting().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.server.ResponseMeltingInfoGet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.server.ResponseMeltingInfoGet)
      com.pearl.fcw.proto.rpc.ResponseMeltingInfoGetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseMeltingInfoGet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseMeltingInfoGet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.class, com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (playerMeltingBuilder_ == null) {
        playerMelting_ = null;
      } else {
        playerMelting_ = null;
        playerMeltingBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseMeltingInfoGet_descriptor;
    }

    public com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet getDefaultInstanceForType() {
      return com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.getDefaultInstance();
    }

    public com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet build() {
      com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet buildPartial() {
      com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet result = new com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet(this);
      if (playerMeltingBuilder_ == null) {
        result.playerMelting_ = playerMelting_;
      } else {
        result.playerMelting_ = playerMeltingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet) {
        return mergeFrom((com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet other) {
      if (other == com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet.getDefaultInstance()) return this;
      if (other.hasPlayerMelting()) {
        mergePlayerMelting(other.getPlayerMelting());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.pearl.fcw.proto.model.ProtoPlayerMelting playerMelting_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.pearl.fcw.proto.model.ProtoPlayerMelting, com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder, com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder> playerMeltingBuilder_;
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public boolean hasPlayerMelting() {
      return playerMeltingBuilder_ != null || playerMelting_ != null;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerMelting getPlayerMelting() {
      if (playerMeltingBuilder_ == null) {
        return playerMelting_ == null ? com.pearl.fcw.proto.model.ProtoPlayerMelting.getDefaultInstance() : playerMelting_;
      } else {
        return playerMeltingBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public Builder setPlayerMelting(com.pearl.fcw.proto.model.ProtoPlayerMelting value) {
      if (playerMeltingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playerMelting_ = value;
        onChanged();
      } else {
        playerMeltingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public Builder setPlayerMelting(
        com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder builderForValue) {
      if (playerMeltingBuilder_ == null) {
        playerMelting_ = builderForValue.build();
        onChanged();
      } else {
        playerMeltingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public Builder mergePlayerMelting(com.pearl.fcw.proto.model.ProtoPlayerMelting value) {
      if (playerMeltingBuilder_ == null) {
        if (playerMelting_ != null) {
          playerMelting_ =
            com.pearl.fcw.proto.model.ProtoPlayerMelting.newBuilder(playerMelting_).mergeFrom(value).buildPartial();
        } else {
          playerMelting_ = value;
        }
        onChanged();
      } else {
        playerMeltingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public Builder clearPlayerMelting() {
      if (playerMeltingBuilder_ == null) {
        playerMelting_ = null;
        onChanged();
      } else {
        playerMelting_ = null;
        playerMeltingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder getPlayerMeltingBuilder() {
      
      onChanged();
      return getPlayerMeltingFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    public com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder getPlayerMeltingOrBuilder() {
      if (playerMeltingBuilder_ != null) {
        return playerMeltingBuilder_.getMessageOrBuilder();
      } else {
        return playerMelting_ == null ?
            com.pearl.fcw.proto.model.ProtoPlayerMelting.getDefaultInstance() : playerMelting_;
      }
    }
    /**
     * <code>optional .fcw.proto.model.ProtoPlayerMelting playerMelting = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.pearl.fcw.proto.model.ProtoPlayerMelting, com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder, com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder> 
        getPlayerMeltingFieldBuilder() {
      if (playerMeltingBuilder_ == null) {
        playerMeltingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.pearl.fcw.proto.model.ProtoPlayerMelting, com.pearl.fcw.proto.model.ProtoPlayerMelting.Builder, com.pearl.fcw.proto.model.ProtoPlayerMeltingOrBuilder>(
                getPlayerMelting(),
                getParentForChildren(),
                isClean());
        playerMelting_ = null;
      }
      return playerMeltingBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.server.ResponseMeltingInfoGet)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.server.ResponseMeltingInfoGet)
  private static final com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet();
  }

  public static com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseMeltingInfoGet>
      PARSER = new com.google.protobuf.AbstractParser<ResponseMeltingInfoGet>() {
    public ResponseMeltingInfoGet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMeltingInfoGet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseMeltingInfoGet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseMeltingInfoGet> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.rpc.ResponseMeltingInfoGet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

