// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface ResponseStrengthenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.ResponseStrengthen)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *强化结果
   * </pre>
   *
   * <code>optional sint32 result = 1;</code>
   */
  int getResult();

  /**
   * <pre>
   *强化对象
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> 
      getItemsList();
  /**
   * <pre>
   *强化对象
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItem getItems(int index);
  /**
   * <pre>
   *强化对象
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   *强化对象
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   *强化对象
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items = 10;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   *强化配件，稳定道具，增加成功率道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items2 = 11;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoPlayerItem> 
      getItems2List();
  /**
   * <pre>
   *强化配件，稳定道具，增加成功率道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items2 = 11;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItem getItems2(int index);
  /**
   * <pre>
   *强化配件，稳定道具，增加成功率道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items2 = 11;</code>
   */
  int getItems2Count();
  /**
   * <pre>
   *强化配件，稳定道具，增加成功率道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items2 = 11;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder> 
      getItems2OrBuilderList();
  /**
   * <pre>
   *强化配件，稳定道具，增加成功率道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoPlayerItem items2 = 11;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerItemOrBuilder getItems2OrBuilder(
      int index);

  /**
   * <pre>
   *强化失败后的返回道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoSysItem failAwards = 12;</code>
   */
  java.util.List<com.pearl.fcw.proto.model.ProtoSysItem> 
      getFailAwardsList();
  /**
   * <pre>
   *强化失败后的返回道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoSysItem failAwards = 12;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItem getFailAwards(int index);
  /**
   * <pre>
   *强化失败后的返回道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoSysItem failAwards = 12;</code>
   */
  int getFailAwardsCount();
  /**
   * <pre>
   *强化失败后的返回道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoSysItem failAwards = 12;</code>
   */
  java.util.List<? extends com.pearl.fcw.proto.model.ProtoSysItemOrBuilder> 
      getFailAwardsOrBuilderList();
  /**
   * <pre>
   *强化失败后的返回道具
   * </pre>
   *
   * <code>repeated .fcw.proto.model.ProtoSysItem failAwards = 12;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysItemOrBuilder getFailAwardsOrBuilder(
      int index);
}
