// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

/**
 * Protobuf type {@code fcw.proto.server.ResponseCharacterGet}
 */
public  final class ResponseCharacterGet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fcw.proto.server.ResponseCharacterGet)
    ResponseCharacterGetOrBuilder {
  // Use ResponseCharacterGet.newBuilder() to construct.
  private ResponseCharacterGet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponseCharacterGet() {
    enable_ = 0;
    name_ = "";
    matchRank_ = 0;
    fightnum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ResponseCharacterGet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            enable_ = input.readSInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 160: {

            matchRank_ = input.readSInt32();
            break;
          }
          case 240: {

            fightnum_ = input.readSInt32();
            break;
          }
          case 322: {
            com.pearl.fcw.proto.model.ProtoCharacterData.Builder subBuilder = null;
            if (items_ != null) {
              subBuilder = items_.toBuilder();
            }
            items_ = input.readMessage(com.pearl.fcw.proto.model.ProtoCharacterData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(items_);
              items_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseCharacterGet_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseCharacterGet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pearl.fcw.proto.rpc.ResponseCharacterGet.class, com.pearl.fcw.proto.rpc.ResponseCharacterGet.Builder.class);
  }

  public static final int ENABLE_FIELD_NUMBER = 1;
  private int enable_;
  /**
   * <code>optional sint32 enable = 1;</code>
   */
  public int getEnable() {
    return enable_;
  }

  public static final int NAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 10;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 10;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATCHRANK_FIELD_NUMBER = 20;
  private int matchRank_;
  /**
   * <code>optional sint32 matchRank = 20;</code>
   */
  public int getMatchRank() {
    return matchRank_;
  }

  public static final int FIGHTNUM_FIELD_NUMBER = 30;
  private int fightnum_;
  /**
   * <code>optional sint32 fightnum = 30;</code>
   */
  public int getFightnum() {
    return fightnum_;
  }

  public static final int ITEMS_FIELD_NUMBER = 40;
  private com.pearl.fcw.proto.model.ProtoCharacterData items_;
  /**
   * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
   */
  public boolean hasItems() {
    return items_ != null;
  }
  /**
   * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
   */
  public com.pearl.fcw.proto.model.ProtoCharacterData getItems() {
    return items_ == null ? com.pearl.fcw.proto.model.ProtoCharacterData.getDefaultInstance() : items_;
  }
  /**
   * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
   */
  public com.pearl.fcw.proto.model.ProtoCharacterDataOrBuilder getItemsOrBuilder() {
    return getItems();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enable_ != 0) {
      output.writeSInt32(1, enable_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, name_);
    }
    if (matchRank_ != 0) {
      output.writeSInt32(20, matchRank_);
    }
    if (fightnum_ != 0) {
      output.writeSInt32(30, fightnum_);
    }
    if (items_ != null) {
      output.writeMessage(40, getItems());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, enable_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, name_);
    }
    if (matchRank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(20, matchRank_);
    }
    if (fightnum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(30, fightnum_);
    }
    if (items_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(40, getItems());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pearl.fcw.proto.rpc.ResponseCharacterGet)) {
      return super.equals(obj);
    }
    com.pearl.fcw.proto.rpc.ResponseCharacterGet other = (com.pearl.fcw.proto.rpc.ResponseCharacterGet) obj;

    boolean result = true;
    result = result && (getEnable()
        == other.getEnable());
    result = result && getName()
        .equals(other.getName());
    result = result && (getMatchRank()
        == other.getMatchRank());
    result = result && (getFightnum()
        == other.getFightnum());
    result = result && (hasItems() == other.hasItems());
    if (hasItems()) {
      result = result && getItems()
          .equals(other.getItems());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ENABLE_FIELD_NUMBER;
    hash = (53 * hash) + getEnable();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + MATCHRANK_FIELD_NUMBER;
    hash = (53 * hash) + getMatchRank();
    hash = (37 * hash) + FIGHTNUM_FIELD_NUMBER;
    hash = (53 * hash) + getFightnum();
    if (hasItems()) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItems().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pearl.fcw.proto.rpc.ResponseCharacterGet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fcw.proto.server.ResponseCharacterGet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fcw.proto.server.ResponseCharacterGet)
      com.pearl.fcw.proto.rpc.ResponseCharacterGetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseCharacterGet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseCharacterGet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pearl.fcw.proto.rpc.ResponseCharacterGet.class, com.pearl.fcw.proto.rpc.ResponseCharacterGet.Builder.class);
    }

    // Construct using com.pearl.fcw.proto.rpc.ResponseCharacterGet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      enable_ = 0;

      name_ = "";

      matchRank_ = 0;

      fightnum_ = 0;

      if (itemsBuilder_ == null) {
        items_ = null;
      } else {
        items_ = null;
        itemsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pearl.fcw.proto.rpc.ApiProto.internal_static_fcw_proto_server_ResponseCharacterGet_descriptor;
    }

    public com.pearl.fcw.proto.rpc.ResponseCharacterGet getDefaultInstanceForType() {
      return com.pearl.fcw.proto.rpc.ResponseCharacterGet.getDefaultInstance();
    }

    public com.pearl.fcw.proto.rpc.ResponseCharacterGet build() {
      com.pearl.fcw.proto.rpc.ResponseCharacterGet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.pearl.fcw.proto.rpc.ResponseCharacterGet buildPartial() {
      com.pearl.fcw.proto.rpc.ResponseCharacterGet result = new com.pearl.fcw.proto.rpc.ResponseCharacterGet(this);
      result.enable_ = enable_;
      result.name_ = name_;
      result.matchRank_ = matchRank_;
      result.fightnum_ = fightnum_;
      if (itemsBuilder_ == null) {
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pearl.fcw.proto.rpc.ResponseCharacterGet) {
        return mergeFrom((com.pearl.fcw.proto.rpc.ResponseCharacterGet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pearl.fcw.proto.rpc.ResponseCharacterGet other) {
      if (other == com.pearl.fcw.proto.rpc.ResponseCharacterGet.getDefaultInstance()) return this;
      if (other.getEnable() != 0) {
        setEnable(other.getEnable());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getMatchRank() != 0) {
        setMatchRank(other.getMatchRank());
      }
      if (other.getFightnum() != 0) {
        setFightnum(other.getFightnum());
      }
      if (other.hasItems()) {
        mergeItems(other.getItems());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pearl.fcw.proto.rpc.ResponseCharacterGet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pearl.fcw.proto.rpc.ResponseCharacterGet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int enable_ ;
    /**
     * <code>optional sint32 enable = 1;</code>
     */
    public int getEnable() {
      return enable_;
    }
    /**
     * <code>optional sint32 enable = 1;</code>
     */
    public Builder setEnable(int value) {
      
      enable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 enable = 1;</code>
     */
    public Builder clearEnable() {
      
      enable_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 10;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 10;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 10;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 10;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int matchRank_ ;
    /**
     * <code>optional sint32 matchRank = 20;</code>
     */
    public int getMatchRank() {
      return matchRank_;
    }
    /**
     * <code>optional sint32 matchRank = 20;</code>
     */
    public Builder setMatchRank(int value) {
      
      matchRank_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 matchRank = 20;</code>
     */
    public Builder clearMatchRank() {
      
      matchRank_ = 0;
      onChanged();
      return this;
    }

    private int fightnum_ ;
    /**
     * <code>optional sint32 fightnum = 30;</code>
     */
    public int getFightnum() {
      return fightnum_;
    }
    /**
     * <code>optional sint32 fightnum = 30;</code>
     */
    public Builder setFightnum(int value) {
      
      fightnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 fightnum = 30;</code>
     */
    public Builder clearFightnum() {
      
      fightnum_ = 0;
      onChanged();
      return this;
    }

    private com.pearl.fcw.proto.model.ProtoCharacterData items_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.pearl.fcw.proto.model.ProtoCharacterData, com.pearl.fcw.proto.model.ProtoCharacterData.Builder, com.pearl.fcw.proto.model.ProtoCharacterDataOrBuilder> itemsBuilder_;
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public boolean hasItems() {
      return itemsBuilder_ != null || items_ != null;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public com.pearl.fcw.proto.model.ProtoCharacterData getItems() {
      if (itemsBuilder_ == null) {
        return items_ == null ? com.pearl.fcw.proto.model.ProtoCharacterData.getDefaultInstance() : items_;
      } else {
        return itemsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public Builder setItems(com.pearl.fcw.proto.model.ProtoCharacterData value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        items_ = value;
        onChanged();
      } else {
        itemsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public Builder setItems(
        com.pearl.fcw.proto.model.ProtoCharacterData.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        items_ = builderForValue.build();
        onChanged();
      } else {
        itemsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public Builder mergeItems(com.pearl.fcw.proto.model.ProtoCharacterData value) {
      if (itemsBuilder_ == null) {
        if (items_ != null) {
          items_ =
            com.pearl.fcw.proto.model.ProtoCharacterData.newBuilder(items_).mergeFrom(value).buildPartial();
        } else {
          items_ = value;
        }
        onChanged();
      } else {
        itemsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = null;
        onChanged();
      } else {
        items_ = null;
        itemsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public com.pearl.fcw.proto.model.ProtoCharacterData.Builder getItemsBuilder() {
      
      onChanged();
      return getItemsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    public com.pearl.fcw.proto.model.ProtoCharacterDataOrBuilder getItemsOrBuilder() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilder();
      } else {
        return items_ == null ?
            com.pearl.fcw.proto.model.ProtoCharacterData.getDefaultInstance() : items_;
      }
    }
    /**
     * <code>optional .fcw.proto.model.ProtoCharacterData items = 40;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.pearl.fcw.proto.model.ProtoCharacterData, com.pearl.fcw.proto.model.ProtoCharacterData.Builder, com.pearl.fcw.proto.model.ProtoCharacterDataOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.pearl.fcw.proto.model.ProtoCharacterData, com.pearl.fcw.proto.model.ProtoCharacterData.Builder, com.pearl.fcw.proto.model.ProtoCharacterDataOrBuilder>(
                getItems(),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:fcw.proto.server.ResponseCharacterGet)
  }

  // @@protoc_insertion_point(class_scope:fcw.proto.server.ResponseCharacterGet)
  private static final com.pearl.fcw.proto.rpc.ResponseCharacterGet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pearl.fcw.proto.rpc.ResponseCharacterGet();
  }

  public static com.pearl.fcw.proto.rpc.ResponseCharacterGet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseCharacterGet>
      PARSER = new com.google.protobuf.AbstractParser<ResponseCharacterGet>() {
    public ResponseCharacterGet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseCharacterGet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseCharacterGet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseCharacterGet> getParserForType() {
    return PARSER;
  }

  public com.pearl.fcw.proto.rpc.ResponseCharacterGet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

