// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.pearl.fcw.proto.rpc;

public interface ResponseFinishGuideOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.ResponseFinishGuide)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *玩家当前已开启但是未完成的玩家成就
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoPlayerAchievement playerAchievement = 1;</code>
   */
  boolean hasPlayerAchievement();
  /**
   * <pre>
   *玩家当前已开启但是未完成的玩家成就
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoPlayerAchievement playerAchievement = 1;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerAchievement getPlayerAchievement();
  /**
   * <pre>
   *玩家当前已开启但是未完成的玩家成就
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoPlayerAchievement playerAchievement = 1;</code>
   */
  com.pearl.fcw.proto.model.ProtoPlayerAchievementOrBuilder getPlayerAchievementOrBuilder();

  /**
   * <pre>
   *对应的系统成就	
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysAchievement nextSysAchievement = 2;</code>
   */
  boolean hasNextSysAchievement();
  /**
   * <pre>
   *对应的系统成就	
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysAchievement nextSysAchievement = 2;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysAchievement getNextSysAchievement();
  /**
   * <pre>
   *对应的系统成就	
   * </pre>
   *
   * <code>optional .fcw.proto.model.ProtoSysAchievement nextSysAchievement = 2;</code>
   */
  com.pearl.fcw.proto.model.ProtoSysAchievementOrBuilder getNextSysAchievementOrBuilder();
}
