CREATE TABLE `CHANNEL` (
  `CHANNEL_ID_B` bigint(20) NOT NULL COMMENT '渠道表主键',
  `GAME_NAME_V` varchar(40) DEFAULT NULL COMMENT '游戏名称',
  `GAME_SERVICE_V` varchar(20) DEFAULT NULL COMMENT '游戏区服',
  `GAME_NUMBER_V` varchar(45) DEFAULT NULL COMMENT '游戏编号',
  `PARTNER_ID_V` varchar(20) DEFAULT NULL COMMENT '联运合作商id',
  `PROXY_ID_V` varchar(20) DEFAULT NULL COMMENT '代理ip',
  `PROXY_PORT_S` int(11) DEFAULT NULL COMMENT '代理端口',
  `STATUS_T` tinyint(4) DEFAULT NULL COMMENT '区服状态：1-正常，0-关闭',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`CHANNEL_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='渠道表';

CREATE TABLE `GAME_CD_KEY` (
  `ID_B` bigint(20) NOT NULL COMMENT '主键',
  `CHANNEL_ID_B` bigint(20) NOT NULL COMMENT '区服ID',
  `GAME_CD_KEY_TYPE_ID_B` bigint(20) NOT NULL COMMENT '激活码用途ID',
  `USER_ID_B` bigint(20) DEFAULT '0' COMMENT '激活者ID',
  `CD_KEY_V` varchar(64) NOT NULL COMMENT '激活码',
  `EXPIRE_DATE_D` datetime NOT NULL COMMENT '过期时间',
  `ENABLE_I` int(1) DEFAULT '1' COMMENT '是否可用(0:disable;1:enable)',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`ID_B`),
  UNIQUE KEY `CD_KEY_V` (`CD_KEY_V`),
  KEY `USER_ID_B` (`USER_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='激活码表';

CREATE TABLE `GAME_CD_KEY_CHANNEL` (
  `ID_B` bigint(20) NOT NULL COMMENT '主键区服ID',
  `GAME_CD_KEY_TYPE_ID_B` bigint(20) NOT NULL DEFAULT '0' COMMENT '激活码用途ID',
  `ENABLE_I` int(1) DEFAULT '1' COMMENT '是否可用(0:disable;1:enable)',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`ID_B`),
  KEY `GAME_CD_KEY_TYPE_ID_B` (`GAME_CD_KEY_TYPE_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='区服运营状态表';

CREATE TABLE `GAME_CD_KEY_TYPE` (
  `ID_B` bigint(20) NOT NULL COMMENT '激活码种类主键',
  `NAME_V` varchar(128) NOT NULL COMMENT '名称',
  `ENABLE_I` int(1) DEFAULT '1' COMMENT '是否可用(0:disable;1:enable)',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='激活码用途表';

CREATE TABLE `QUESTION` (
  `QUESTION_ID_B` bigint(20) NOT NULL COMMENT '表主键',
  `QUESTION_INFO_V` varchar(100) DEFAULT NULL COMMENT '问题描述',
  `ORDER_BY_ID_T` tinyint(4) DEFAULT NULL COMMENT '问题显示时的顺序',
  `STATUS_T` tinyint(4) DEFAULT NULL COMMENT '问题是否有效：1-有效；0-无效',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`QUESTION_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='安全问题';

CREATE TABLE `USERS` (
  `USER_ID_B` bigint(20) NOT NULL COMMENT '用户主键',
  `USER_NAME_V` varchar(45) DEFAULT NULL COMMENT '用户名',
  `PASSWORD_V` varchar(20) DEFAULT NULL COMMENT '密码',
  `ID_NAME_V` varchar(45) DEFAULT NULL COMMENT '真实姓名',
  `ID_NUMBER_V` varchar(45) DEFAULT NULL COMMENT '身份证号',
  `STATUS_T` tinyint(4) DEFAULT NULL COMMENT '用户状态',
  `BALANCE_I` int(11) DEFAULT NULL COMMENT '余额',
  `CREATE_DATE_D` datetime DEFAULT NULL COMMENT '创建日期',
  `LAST_MODIFY_DATE_D` datetime DEFAULT NULL COMMENT '最后修改日期',
  `VERSION_B` bigint(20) DEFAULT NULL COMMENT '版本号',
  `EMAIL_V` varchar(20) DEFAULT NULL COMMENT '电子邮箱',
  `MOBILE_V` varchar(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL_STATUS_T` tinyint(4) DEFAULT NULL COMMENT '邮箱状态：1-邮箱已绑定，0-邮箱未绑定',
  `MOBILE_STATUS_T` tinyint(4) DEFAULT NULL COMMENT '手机状态：1-手机已绑定，0-手机未绑定',
  `QUESTION_ID_B` bigint(20) DEFAULT NULL COMMENT 'QUESTION表的主键',
  `ANSWER_V` varchar(100) DEFAULT NULL COMMENT '安全问题的答案',
  PRIMARY KEY (`USER_ID_B`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 初始化语句
INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (1, '问题1：我是什么星座的？', 1, 1, now(), null, 1);

INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (2, '问题2：我的宠物是？', 2, 1, now(), null, 1);

INSERT INTO QUESTION
(QUESTION_ID_B, QUESTION_INFO_V, ORDER_BY_ID_T, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (3, '问题3：我的豪宅在哪里？', 3, 1, now(), null, 1);

INSERT INTO CHANNEL
(CHANNEL_ID_B, GAME_NAME_V, GAME_SERVICE_V, GAME_NUMBER_V, PARTNER_ID_V, PROXY_ID_V, PROXY_PORT_S, STATUS_T, CREATE_DATE_D, LAST_MODIFY_DATE_D, VERSION_B) 
VALUES (201210241639001000, '游戏王', '12', 'fc0001', 'xuelei0001', 
'10.10.14.13', 3700, 1, now(), null, 1);
