{
	cmd = "battlefield_defense_invitation",
	attackTeam_pid=#$attackTeam_pid#,
	attackTeam_name="#$attackTeam_name#",	
	attackTeam_teamSpaceLevel=#$attackTeam_teamSpaceLevel#,
	defenseTeam_pid=#$defenseTeam_pid#,
	defenseTeam_name="#$defenseTeam_name#",
	defenseTeam_teamSpaceLevel=#$defenseTeam_teamSpaceLevel#,
	receiver_pid=#$receiver_pid#,
	serverid=#$serverid#,
	channelid=#$channelid#,
	roomid=#$roomid#,
	roompwd="#$roompwd#",
	restype=#$restype#,
	config="#$config#",
	canRobRes=#$canRobRes#,
	atknum=#$atknum#
}	