package com.pearl.fcw.utils.smarty4j;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.lilystudio.smarty4j.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.pearl.fcw.utils.O2oUtil;
import com.pearl.fcw.utils.Smarty4jUtil.Ctx;

public class TeamItemList implements Ctx {
private Logger logger = LoggerFactory.getLogger(getClass());

@SuppressWarnings({ "unchecked", "rawtypes" })
public String get(Context context) throws Exception {
StringBuilder sb = new StringBuilder();
sb.append("teamResourceWar={ ");
sb.append("\r\n");
sb.append("	placeLevel=");
sb.append(context.get("placeLevel"));
sb.append(", ");
sb.append("\r\n");
sb.append("	isLeader=");
sb.append(context.get("isLeader"));
sb.append(", ");
sb.append("\r\n");
sb.append("	resoucesNum=");
sb.append(context.get("resoucesNum"));
sb.append(", ");
sb.append("\r\n");
sb.append("	time = ");
sb.append(context.get("time"));
sb.append(", ");
sb.append("\r\n");
sb.append("	fc=");
sb.append(context.get("fc"));
sb.append(", ");
sb.append("\r\n");
sb.append("	playerRes=");
sb.append(context.get("playerRes"));
sb.append(", ");
sb.append("\r\n");
sb.append("	teamStorage={ ");
sb.append("\r\n");
if( O2oUtil.compare(context.get("storageType"),"==",1) || O2oUtil.compare(context.get("storageType"),"==",5) ){
if( O2oUtil.compare(context.get("storageType"),"==",1) ){
sb.append("				defense={ ");
sb.append("\r\n");
sb.append("					curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("					pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList292 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList292=(List<?>)context.get("itemList");
else if (context.get("itemList").getClass().isArray()) itemList292=Stream.of((Object[])context.get("itemList")).collect(Collectors.toList());
}
itemList292.forEach(teamItem->{
try{
sb.append("					{ ");
sb.append("\r\n");
sb.append("						isEvolve=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"oilOrWallUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("						level=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("						teamItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						sysItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						display = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						name = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						description = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						maxquantity=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						buycd=\"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						durable = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"durable"));
sb.append(", ");
sb.append("\r\n");
sb.append("						resteamprice={ ");
sb.append("\r\n");
sb.append("							id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("							cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("						},	 ");
sb.append("\r\n");
sb.append("						resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList981 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList981=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList981=Stream.of((Object[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList981.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e2){
logger.error(e2.toString());
}
});
sb.append("						},	    					 ");
sb.append("\r\n");
sb.append("						performance={ ");
sb.append("\r\n");
sb.append("							hp={ ");
sb.append("\r\n");
sb.append("								property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("								level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("								value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("								curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("								maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							}, ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
}catch(Exception e2){
logger.error(e2.toString());
}
});
sb.append("				}, ");
sb.append("\r\n");
}
sb.append("			 ");
sb.append("\r\n");
if( O2oUtil.compare(context.get("storageType"),"==",5) ){
sb.append("				machine={ ");
sb.append("\r\n");
sb.append("					curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("					pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList73 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList73=(List<?>)context.get("itemList");
else if (context.get("itemList").getClass().isArray()) itemList73=Stream.of((Object[])context.get("itemList")).collect(Collectors.toList());
}
itemList73.forEach(teamItem->{
try{
sb.append("					{ ");
sb.append("\r\n");
sb.append("						isEvolve=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"oilOrWallUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("						level=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("						teamItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						sysItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						display = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						name = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						description = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						maxquantity=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("						buycd=\"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("						resteamprice={ ");
sb.append("\r\n");
sb.append("							id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("							cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("							unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("						},	 ");
sb.append("\r\n");
sb.append("						resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList591 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList591=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList591=Stream.of((Object[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList591.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e4){
logger.error(e4.toString());
}
});
sb.append("						}, ");
sb.append("\r\n");
sb.append("						performance={ ");
sb.append("\r\n");
sb.append("							hp={ ");
sb.append("\r\n");
sb.append("								property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("								level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("								value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("								curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("								maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							}, ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
}catch(Exception e4){
logger.error(e4.toString());
}
});
sb.append("				}, ");
sb.append("\r\n");
}
}
if( O2oUtil.compare(context.get("storageType"),"==",2) ){
sb.append("			attack={ ");
sb.append("\r\n");
sb.append("				curPage=");
sb.append(context.get("curPage"));
sb.append(", ");
sb.append("\r\n");
sb.append("				pages=");
sb.append(context.get("pages"));
sb.append(", ");
sb.append("\r\n");
List itemList251 = new ArrayList<>();
if (null!=context.get("itemList")){
if (context.get("itemList") instanceof List) itemList251=(List<?>)context.get("itemList");
else if (context.get("itemList").getClass().isArray()) itemList251=Stream.of((Object[])context.get("itemList")).collect(Collectors.toList());
}
itemList251.forEach(teamItem->{
try{
sb.append("				{ ");
sb.append("\r\n");
sb.append("					isEvolve=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"towerIsUpgrade"));
sb.append(", ");
sb.append("\r\n");
sb.append("					level=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"level"));
sb.append(", ");
sb.append("\r\n");
sb.append("					teamItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"id"));
sb.append(", ");
sb.append("\r\n");
sb.append("					sysItemId = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("					display = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.displayName"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					name = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.name"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					description = \"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"sysItem.description"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					maxquantity=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"maxQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("					value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"showQuantity"));
sb.append(", ");
sb.append("\r\n");
sb.append("					buycd=\"");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"buyCD"));
sb.append("\", ");
sb.append("\r\n");
sb.append("					durable = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"durable"));
sb.append(", ");
sb.append("\r\n");
sb.append("					bullet = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"bullet"));
sb.append(", ");
sb.append("\r\n");
sb.append("					resteamprice={ ");
sb.append("\r\n");
sb.append("						id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.id"));
sb.append(", ");
sb.append("\r\n");
sb.append("						unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unitType"));
sb.append(", ");
sb.append("\r\n");
sb.append("						cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.cost"));
sb.append(", ");
sb.append("\r\n");
sb.append("						unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"currentCreatePayMent.unit"));
sb.append(" ");
sb.append("\r\n");
sb.append("					},		 ");
sb.append("\r\n");
sb.append("					resteamprices={ ");
sb.append("\r\n");
List teamItemsysItemresTeamPricesList452 = new ArrayList<>();
if (null!=O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")){
if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList") instanceof List) teamItemsysItemresTeamPricesList452=(List<?>)O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList");
else if (O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList").getClass().isArray()) teamItemsysItemresTeamPricesList452=Stream.of((Object[])O2oUtil.getSmarty4jProperty(teamItem,"sysItem.resTeamPricesList")).collect(Collectors.toList());
}
teamItemsysItemresTeamPricesList452.forEach(pay->{
try{
sb.append("							{id=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"id"));
sb.append(",unittype=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unitType"));
sb.append(",cost=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"cost"));
sb.append(",unit=");
sb.append(O2oUtil.getSmarty4jPropertyNil(pay,"unit"));
sb.append(",},  ");
sb.append("\r\n");
}catch(Exception e6){
logger.error(e6.toString());
}
});
sb.append("					}, ");
sb.append("\r\n");
sb.append("					performance={ ");
sb.append("\r\n");
sb.append("						power={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property1.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property1.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property1.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property1.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property1.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						fireSpeed={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property2.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property2.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property2.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property2.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property2.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						hp={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property3.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						fireDistance={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property4.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property4.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property4.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property4.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property4.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("						rotateSpeed={ ");
sb.append("\r\n");
sb.append("							property = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property5.property"));
sb.append(", ");
sb.append("\r\n");
sb.append("							level = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property5.level"));
sb.append(", ");
sb.append("\r\n");
sb.append("							value = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property5.value"));
sb.append(", ");
sb.append("\r\n");
sb.append("							curExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property5.curExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("							maxExp = ");
sb.append(O2oUtil.getSmarty4jPropertyNil(teamItem,"property5.maxExp"));
sb.append(", ");
sb.append("\r\n");
sb.append("						}, ");
sb.append("\r\n");
sb.append("					}, ");
sb.append("\r\n");
sb.append("				}, ");
sb.append("\r\n");
}catch(Exception e6){
logger.error(e6.toString());
}
});
sb.append("			}, ");
sb.append("\r\n");
}
if( O2oUtil.compare(context.get("storageType"),"==",3) ){
sb.append("			scene={}, ");
sb.append("\r\n");
}
sb.append("	}, ");
sb.append("\r\n");
sb.append("} ");
sb.append("\r\n");
return sb.toString();
}

}