// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.pearl.fcw.proto.protocol;

public final class ApiProto {
  private ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fcw_proto_protocol_Head_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fcw_proto_protocol_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\022fcw.proto.protocol\"~\n\004" +
      "Head\0220\n\004type\030\001 \001(\0162\".fcw.proto.protocol." +
      "EServerMessage\022\014\n\004path\030\002 \001(\t\022\r\n\005queId\030\003 " +
      "\001(\t\022\r\n\005rpcId\030\004 \001(\021\022\013\n\003uId\030\005 \001(\021\022\013\n\003pId\030\006" +
      " \001(\021*\201\004\n\016EServerMessage\022\026\n\022SM_ResponseTe" +
      "xtRPC\020\000\022\030\n\024SM_ResponseBinaryRPC\020\001\022\017\n\013SM_" +
      "SendChat\020\002\022\031\n\025SM_BroadcastProxyChat\020\003\022\033\n" +
      "\027SM_BroadcastChannelChat\020\004\022\024\n\020SM_Request" +
      "Status\020\005\022\030\n\024SM_RequestOnlineInfo\020\006\022\023\n\017SM" +
      "_NotifyClient\020\007\022\032\n\026SM_UpdateCharacterInf",
      "o\020\010\022\032\n\026SM_BroadcastServerChat\020\t\022\026\n\022SM_Re" +
      "questKeywords\020\n\022\030\n\024SM_RequestServerList\020" +
      "\013\022\027\n\023SM_RequestLevelList\020\014\022\024\n\020SM_Request" +
      "Notice\020\r\022\021\n\rSM_KickPlayer\020\016\022\020\n\014SM_SysCon" +
      "fig\020\017\022\022\n\016SM_ExpiredPack\020\020\022\023\n\017SM_SyncRPCQ" +
      "ueue\020\021\022\027\n\023SM_RequestBlackList\020\022\022\032\n\026SM_Up" +
      "dateBillBoardList\020\023\022\023\n\017SM_ResetSysData\020\024" +
      "BL\n\034com.pearl.fcw.proto.protocolB\010ApiPro" +
      "toP\001\240\001\001\252\002\034Com.Pearl.Fcw.Proto.Protocolb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fcw_proto_protocol_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fcw_proto_protocol_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fcw_proto_protocol_Head_descriptor,
        new java.lang.String[] { "Type", "Path", "QueId", "RpcId", "UId", "PId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
