-- 彩盒
CREATE TABLE `INFO_LUCKY_PACKAGE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `PLAYER_ID` INT(11) DEFAULT NULL COMMENT '玩家id',
  `PACKAGE_LEVEL` INT(2) DEFAULT NULL COMMENT '彩盒等级：1-青铜；2-白银；3-黄金',
  `PAY_TYPE` INT(2) DEFAULT NULL COMMENT '抽奖方式：1-使用卡；2-勋章兑换',
  `SYSTEM_ID` INT(11) DEFAULT NULL COMMENT '道具id',
  `SYSTEM_NUMBER` INT(11) DEFAULT NULL COMMENT '道具数',
  `USE_TYPE` INT(2) DEFAULT NULL COMMENT '使用类型',
  `CREATE_DATE` DATETIME DEFAULT NULL COMMENT '创建日期',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB COMMENT='彩盒操作统计表（只记当天操作明细）';

CREATE TABLE `INFO_REPORT_LUCKY_PACKAGE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `USING_NUMBER_GOLD` INT(11) DEFAULT NULL COMMENT '金卡使用人数',
  `USER_NUMBER_GOLD` INT(11) DEFAULT NULL COMMENT '金卡使用次数',
  `USING_NUMBER_SILVER` INT(11) DEFAULT NULL COMMENT '银卡使用人数',
  `USER_NUMBER_SILVER` INT(11) DEFAULT NULL COMMENT '银卡使用次数',
  `USING_NUMBER_COPPER` INT(11) DEFAULT NULL COMMENT '铜卡使用人数',
  `USER_NUMBER_COPPER` INT(11) DEFAULT NULL COMMENT '铜卡使用次数',
  `STATISTIC_DATE` DATE DEFAULT NULL COMMENT '统计日期',
  PRIMARY KEY (`ID`),
  INDEX `DATE_INDEX` (`STATISTIC_DATE`)
) ENGINE=InnoDB COMMENT='彩盒统计汇总表';

CREATE TABLE `dc`.`INFO_REPORT_CHARACTER_ACCOUNT`(
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `ROLE1` INT COMMENT '火箭兵',
  `ROLE2` INT COMMENT '重机枪手',
  `ROLE3` INT COMMENT '狙击手',
  `ROLE4` INT COMMENT '突击手',
  `ROLE5` INT COMMENT '火焰兵',
  `ROLE6` INT COMMENT '护士',
  `ROLE7` INT COMMENT '工程兵',
  `MAP_NAME` INT COMMENT '地图',
  `GAME_MODEL` INT COMMENT '模式',
  `STATISTIC_DATE` DATE COMMENT '统计哪天的数据',
  `CREATE_DATE` DATETIME,
  PRIMARY KEY (`ID`),
  INDEX `DATE_INDEX` (`STATISTIC_DATE`)
) ENGINE=INNODB CHARSET=utf8;
  
-- procedure
DELIMITER $$
USE `dc`$$
DROP PROCEDURE IF EXISTS `P_LUCKY_PACKAGE`$$

CREATE DEFINER=`pdedc`@`%` PROCEDURE `P_LUCKY_PACKAGE`()
BEGIN

    DROP TABLE IF EXISTS `TEMP_PACKAGE`;

    CREATE TEMPORARY TABLE `TEMP_PACKAGE` (
      ID INT,
      PLAYER_ID INT,
      PACKAGE_LEVEL INT
    );

    INSERT INTO `TEMP_PACKAGE`
      SELECT T.ID, T.PLAYER_ID, T.PACKAGE_LEVEL    
      FROM `INFO_LUCKY_PACKAGE` T
      WHERE T.PAY_TYPE=1 AND T.CREATE_DATE<CURDATE();

    -- gold
    SELECT @NUM1 := COUNT(DISTINCT PLAYER_ID),
           @NUM2 := COUNT(ID)
    FROM `TEMP_PACKAGE`
    WHERE PACKAGE_LEVEL=3;

    -- silver
    SELECT @NUM3 := COUNT(DISTINCT PLAYER_ID),
           @NUM4 := COUNT(ID)
    FROM `TEMP_PACKAGE`
    WHERE PACKAGE_LEVEL=2;

    -- copper
    SELECT @NUM5 := COUNT(DISTINCT PLAYER_ID),
           @NUM6 := COUNT(ID)
    FROM `TEMP_PACKAGE`
    WHERE PACKAGE_LEVEL=1;

    -- add all datas of yesterday to report
    INSERT INTO INFO_REPORT_LUCKY_PACKAGE(`USING_NUMBER_GOLD`,`USER_NUMBER_GOLD`,`USING_NUMBER_SILVER`,`USER_NUMBER_SILVER`,`USING_NUMBER_COPPER`,`USER_NUMBER_COPPER`,`STATISTIC_DATE`)
    VALUES (@NUM1, @NUM2, @NUM3, @NUM4, @NUM5, @NUM6, DATE_FORMAT(NOW(), '%Y-%m-%d'));

    DROP TABLE `TEMP_PACKAGE`;

    -- remove all datas of yesterday
    DELETE FROM INFO_LUCKY_PACKAGE WHERE CREATE_DATE<CURDATE();

END$$
DELIMITER ;

-- 出页面table的语句
SELECT  `STATISTIC_DATE`, `USING_NUMBER_GOLD`, `USER_NUMBER_GOLD`, `USING_NUMBER_SILVER`, `USER_NUMBER_SILVER`, `USING_NUMBER_COPPER`, `USER_NUMBER_COPPER`
FROM `INFO_REPORT_LUCKY_PACKAGE`
WHERE `STATISTIC_DATE` BETWEEN '2013-05-27' AND '2013-05-28'
ORDER BY `STATISTIC_DATE`;




