// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.pearl.fcw.proto.server;

public final class ApiProto {
  private ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fcw_proto_server_RequestResetSysData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fcw_proto_server_RequestResetSysData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fcw_proto_server_RequestPlayerOnline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fcw_proto_server_RequestPlayerOnline_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fcw_proto_server_ResponsePlayerOnline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fcw_proto_server_ResponsePlayerOnline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\020fcw.proto.server\032\020enums/" +
      "type.proto\032\013model.proto\"(\n\023RequestResetS" +
      "ysData\022\021\n\tclassName\030\001 \003(\t\"\364\001\n\023RequestPla" +
      "yerOnline\022\016\n\006userId\030\001 \001(\021\022\020\n\010userName\030\002 " +
      "\001(\t\022\014\n\004name\030\003 \001(\t\022\n\n\002ip\030\004 \001(\t\0225\n\007vipType" +
      "\030\005 \001(\0162$.fcw.proto.enums.type.EPlayerVip" +
      "Type\022\024\n\014internetCafe\030\006 \001(\021\022=\n\013accountTyp" +
      "e\030\007 \001(\0162(.fcw.proto.enums.type.EPlayerAc" +
      "countType\022\025\n\rclientVersion\030\010 \001(\t\"\347\002\n\024Res" +
      "ponsePlayerOnline\022\013\n\003uid\030\001 \001(\021\022\020\n\010player",
      "Id\030\002 \001(\021\022\014\n\004name\030\003 \001(\t\022\014\n\004rank\030\004 \001(\021\022\013\n\003" +
      "exp\030\005 \001(\021\022\017\n\007profile\030\006 \001(\t\022\016\n\006param7\030\007 \001" +
      "(\t\022\r\n\005isNew\030\010 \001(\021\022\r\n\005isVip\030\t \001(\021\022\024\n\014inte" +
      "rnetCafe\030\n \001(\021\022\033\n\023sysItemIValueInBuff\030\013 " +
      "\001(\021\022\014\n\004icon\030\014 \001(\t\022\024\n\014isCheckToday\030\r \001(\021\022" +
      "\013\n\003top\030\016 \001(\021\022\020\n\010fightNum\030\017 \001(\021\022\017\n\007winRat" +
      "e\030\020 \001(\002\022\016\n\006teamId\030\021 \001(\021\022\020\n\010teamName\030\022 \001(" +
      "\t\022\021\n\tteamLevel\030\023 \001(\021\022\014\n\004isGm\030\024 \001(\021BH\n\032co" +
      "m.pearl.fcw.proto.serverB\010ApiProtoP\001\240\001\001\252" +
      "\002\032Com.Pearl.Fcw.Proto.Serverb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pearl.fcw.proto.enums.ApiProto.getDescriptor(),
          com.pearl.fcw.proto.model.ApiProto.getDescriptor(),
        }, assigner);
    internal_static_fcw_proto_server_RequestResetSysData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fcw_proto_server_RequestResetSysData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fcw_proto_server_RequestResetSysData_descriptor,
        new java.lang.String[] { "ClassName", });
    internal_static_fcw_proto_server_RequestPlayerOnline_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fcw_proto_server_RequestPlayerOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fcw_proto_server_RequestPlayerOnline_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Name", "Ip", "VipType", "InternetCafe", "AccountType", "ClientVersion", });
    internal_static_fcw_proto_server_ResponsePlayerOnline_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fcw_proto_server_ResponsePlayerOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fcw_proto_server_ResponsePlayerOnline_descriptor,
        new java.lang.String[] { "Uid", "PlayerId", "Name", "Rank", "Exp", "Profile", "Param7", "IsNew", "IsVip", "InternetCafe", "SysItemIValueInBuff", "Icon", "IsCheckToday", "Top", "FightNum", "WinRate", "TeamId", "TeamName", "TeamLevel", "IsGm", });
    com.pearl.fcw.proto.enums.ApiProto.getDescriptor();
    com.pearl.fcw.proto.model.ApiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
