// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.pearl.fcw.proto.server;

public interface ResponsePlayerOnlineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fcw.proto.server.ResponsePlayerOnline)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional sint32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>optional sint32 playerId = 2;</code>
   */
  int getPlayerId();

  /**
   * <code>optional string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional sint32 rank = 4;</code>
   */
  int getRank();

  /**
   * <code>optional sint32 exp = 5;</code>
   */
  int getExp();

  /**
   * <code>optional string profile = 6;</code>
   */
  java.lang.String getProfile();
  /**
   * <code>optional string profile = 6;</code>
   */
  com.google.protobuf.ByteString
      getProfileBytes();

  /**
   * <code>optional string param7 = 7;</code>
   */
  java.lang.String getParam7();
  /**
   * <code>optional string param7 = 7;</code>
   */
  com.google.protobuf.ByteString
      getParam7Bytes();

  /**
   * <code>optional sint32 isNew = 8;</code>
   */
  int getIsNew();

  /**
   * <code>optional sint32 isVip = 9;</code>
   */
  int getIsVip();

  /**
   * <pre>
   *网咖登录标记
   * </pre>
   *
   * <code>optional sint32 internetCafe = 10;</code>
   */
  int getInternetCafe();

  /**
   * <pre>
   *已经启用buff的玩家道具对应的系统道具的iValue值
   * </pre>
   *
   * <code>optional sint32 sysItemIValueInBuff = 11;</code>
   */
  int getSysItemIValueInBuff();

  /**
   * <pre>
   *头像
   * </pre>
   *
   * <code>optional string icon = 12;</code>
   */
  java.lang.String getIcon();
  /**
   * <pre>
   *头像
   * </pre>
   *
   * <code>optional string icon = 12;</code>
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <pre>
   *当天是否已签到
   * </pre>
   *
   * <code>optional sint32 isCheckToday = 13;</code>
   */
  int getIsCheckToday();

  /**
   * <pre>
   *排名
   * </pre>
   *
   * <code>optional sint32 top = 14;</code>
   */
  int getTop();

  /**
   * <pre>
   *战斗力
   * </pre>
   *
   * <code>optional sint32 fightNum = 15;</code>
   */
  int getFightNum();

  /**
   * <pre>
   *胜率
   * </pre>
   *
   * <code>optional float winRate = 16;</code>
   */
  float getWinRate();

  /**
   * <pre>
   *玩家参与的战队ID
   * </pre>
   *
   * <code>optional sint32 teamId = 17;</code>
   */
  int getTeamId();

  /**
   * <pre>
   *战队名称
   * </pre>
   *
   * <code>optional string teamName = 18;</code>
   */
  java.lang.String getTeamName();
  /**
   * <pre>
   *战队名称
   * </pre>
   *
   * <code>optional string teamName = 18;</code>
   */
  com.google.protobuf.ByteString
      getTeamNameBytes();

  /**
   * <pre>
   *战队等级
   * </pre>
   *
   * <code>optional sint32 teamLevel = 19;</code>
   */
  int getTeamLevel();

  /**
   * <pre>
   *是否GM玩家
   * </pre>
   *
   * <code>optional sint32 isGm = 20;</code>
   */
  int getIsGm();
}
